### ISSUE TITLE
QA: Soak testing

### ISSUE THREAD

**Issue by anvabr** [hashgraph/guardian#1011]
### Problem description
At present Guardian instances are only used consistently for a relatively short time period. There is no knowledge of whether the system will degrade performance in any way after multiple days/weeks of consistent load.

### Requirements

- Develop an automated test infrastructure, to be run for at least 1 month for each release, with constant and varied test load.
- Ensure system operational metrics are collected during the test.
- Monitor and analyse the above to make sure the system can be operated to enterprise-grade SLAs in a BAU state.

### Definition of done
Soak tests are triggered and automatically run for each release.
As a result the team has a reasonable idea of the BAU operations of Guardian.

### Acceptance criteria

- Soak tests cover iREC and VERRA demo scenarios, with consistent load
- Test results from input for development work.

**Comment by Bartleonid** [comment]
Prerequisites:

- Running guardian on azure instance target instance
- Access to source azure instance from which tests will be executed
-iREC and VERRA load test scripts developed using JMeter
-Access to Monitoring tools

NFA Requirements: Reliability test
Duration:
1. 1 day
2. 1 week
3. 1 month
Number of concurrent users for consistent load? 
Which user flows to be tested during reliability test?
