### ISSUE TITLE
Release 2.2.0-prerelease issues

### ISSUE THREAD

**Issue by samuraitruong** [hashgraph/guardian#1042]
### Problem description
Below are few issue i found for this version

1. Missing front-end release image

```
docker pull  gcr.io/hedera-registry/frontend:2.2.0-prerelease
Error response from daemon: manifest for gcr.io/hedera-registry/frontend:2.2.0-prerelease not found: manifest unknown: Failed to fetch "2.2.0-prerelease" from request "/v2/hedera-registry/frontend/manifests/2.2.0-prerelease".
```
2. Deployed guardian 2.2.0 on previous version 2.1.3 and below features are not compatible
2.1. Can not view tokens (those token was created in 2.1.3)
403 Forbidden
Http failure response for http://localhost:4000/api/v1/tokens: 403 Forbidden
Forbidden
![image](https://user-images.githubusercontent.com/1183138/176066231-57a4405d-1bb4-4871-959c-5e818a2e7410.png)

2.2 Can not view existing schema return empty list

Schemas were created in database in previous version

![image](https://user-images.githubusercontent.com/1183138/176066558-ed0858c5-4b67-4680-9ea9-02cd96767b11.png)

<img width="1789" alt="image" src="https://user-images.githubusercontent.com/1183138/176066484-76ff3394-4ae4-4cfb-b5f5-fb7ec8076356.png">

2.3 can not view policy from previous version (cause by token error)

### Step to reproduce
1. install 2.1.3 and setup policies/token/schema
2. switch to 2.2.0 releases
3. use front-end (use. latest tag) to verify all above

I am not sure that all cause by front-end containers is not the latest code that will work with 2.2.0 or not, please double check

**Comment by prernaadev01** [comment]
@samuraitruong Thank you for this ticket. 
1. We have fixed the front end release image and moved to Main.
2. Versioning compatibility issue is because of change of Root Authority to Standard Registry. We would request you to clear your database and try again once.

**Comment by samuraitruong** [comment]
Thanks @prernaadev01 in the future may I request the migration steps or backward compatible consideration when design new features/changes. Since we soon have production running  and can not wipe out database anymore

**Comment by voycey** [comment]
> @samuraitruong Thank you for this ticket.
> 
> 1. We have fixed the front end release image and moved to Main.
> 2. Versioning compatibility issue is because of change of Root Authority to Standard Registry. We would request you to clear your database and try again once.

Hi @prernaadev01 

Can Envision look at creating migrations for this kind of stuff? Clearing out the database in Production (2 weeks away for us) is not an option, this should be handled as part of a deployment script.

https://orkhan.gitbook.io/typeorm/docs/migrations
https://mikro-orm.io/docs/migrations

**Comment by prernaadev01** [comment]
@voycey Thank you for your recommendations. We are working on it and have created a ticket #1048 to track the progress. We will consider your suggestions and will make this live in our upcoming release.
