### ISSUE TITLE
Establish Migration Procedure 

### ISSUE THREAD

**Issue by prernaadev01** [hashgraph/guardian#1048]
### Problem description
Currently, When we make a release, migration of the versions are not getting compatible and this will cause an issue in case of Production.

### Requirements
We need to establish a proper Migration Procedure during the releases so that Guardian can be upgraded without affecting other things such as DB data etc.

### Definition of done
Defining and implementing 

### Acceptance criteria
What are the criteria by which we determine if the issue has been resolved?

**Comment by prernaadev01** [comment]
@Stepan-Kirjakov Community have suggested some of the migration ways. Please look at it. https://orkhan.gitbook.io/typeorm/docs/migrations
https://mikro-orm.io/docs/migrations

**Comment by voycey** [comment]
Good practice is that any DB schema or structure changes are captured as code and on each deployment the migrations are run meaning that during each release the DB is in exactly the state it should be for that release.

This also gives an opportunity for any transformations that are necessary to data to be performed too (such as changing topic_ids in the database for example)
