### ISSUE TITLE
Contextual comments are lacking in the files

### ISSUE THREAD

**Issue by sergmetelin** [hashgraph/guardian#105]
As a Developer that is looking at the Open Source Guardian Code, I want to able to see comments at the beginning of important files that give an introduction as to what the code below is all about. 

**Definition of Done:** Commenting should follow TSDOC Format

### Description

Files are uncommented in the https://github.com/hashgraph/guardian/blob/main/guardian-service/src/api/

Can we please add information on what these files are and provide some basic commenting? 

### Steps to reproduce

Example: https://github.com/hashgraph/guardian/blob/main/guardian-service/src/api/approve.service.ts

### Hedera network

other

### Version

any

**Comment by envisionblockchainpm** [comment]
This has been completed. Here is the Pull Request for DOD / Acceptance Criteria for this ticket: 
https://github.com/hashgraph/guardian/pull/124 

@sergmetelin @danielnorkin @anvabr
