### ISSUE TITLE
Trustchain validity is compromised on 2.2.0 

### ISSUE THREAD

**Issue by mattsmithies** [hashgraph/guardian#1055]
### Bypassed the trustchain approval process (approval docs)

It seems that I am able to push documents to the Guardian and I have the ability to continue on with all the documents without prior approval of previous steps.

In our first R&D policy we have this basic flow, based on iREC through @justin-atwell:

1. An actor can sign up as a registrant
2. An actor needs to be approved by RA
3. The actor may create a farm
4. The farm must be approved by RA
5. The actor now may create an issue to the farm.
6. The issue must be approved by RA
7. Tokens are minted after that approval

### Step to reproduce

1. I have upgraded to the latest version of the Guardian
4. I have updated my .zip file to be a .policy file
8. I have run through my script for testing
9. And it turns out that I can submit docs and not get approval and be able to mint tokens with one approval event at the end of the policy.

### Expected behavior

Every single document must be approved by the RA/admin (in this case) before the actor can continue down the policy.

_note, I have not updated our API calls since the previous version, whether we were able to bypass the majority of approval events_

### Screenshots

This of a list of applications that still have the choice of approval or rejection.

![Screenshot 2022-07-01 at 16 11 00](https://user-images.githubusercontent.com/6974163/176921510-2920df04-2cc9-4825-a257-9116ad04dcb5.png)

This is the list of farms that may still be approved or rejected

![Screenshot 2022-07-01 at 16 12 07](https://user-images.githubusercontent.com/6974163/176921656-4f113c27-2899-463f-bf46-d8208e78d2aa.png)

I have manually clicked approve for the issue requests to trigger the mint of tokens.

![Screenshot 2022-07-01 at 16 12 54](https://user-images.githubusercontent.com/6974163/176921771-bda5fa10-d351-47b9-8e18-29dc801fdb24.png)

This is the trustchain where some documents were not explicitly approved by RA

![Screenshot 2022-07-01 at 16 10 12](https://user-images.githubusercontent.com/6974163/176921394-35797b3d-8cc6-4f1b-b754-e5b23f6fdbd8.png)

This is a short video of [my testing script running](https://www.loom.com/share/0ee390416eb2477aa0bf456b4a90ee5a (edited) ) against the new version of the Guardian

**Comment by anvabr** [comment]
@mattsmithies could you please attach the policy file itself? thanks!

**Comment by mattsmithies** [comment]
@anvabr you'll need to rename the extension for the new version of the guardian, can't upload a '.policy' file here

[dovu_test_policy.zip](https://github.com/hashgraph/guardian/files/9030562/dovu_test_policy.zip)
