### ISSUE TITLE
Designated account to 'own' minted tokens

### ISSUE THREAD

**Issue by anvabr** [hashgraph/guardian#1068]
### Problem description
Currently after MRVs are processed (and aggregated according to the policy rules) when tokens are minted as the result they get assigned/minted into the account that owns the corresponding VC. For some use-cases, for example those listed below, this is unacceptable:

- designated custodian accounts
- non tradeable tokens
- non-transferrable tokens

### Requirements
Introduce a new policy element (block) which would allow policy creators to require the configuration/input of the designated account for minting tokens. It should be possible to place the block in various places in the policy workflow, thereby allowing different users to specify the account. For example:

- at the project creation, so project owner can specify the 'target' address
- at the installation of the sensor, so the Installer can specify the 'target' address for the sensor

### Definition of done

- Required policy definition language elements support by Guardian
- Example usage of the elements is demonstrated in the sample policies
- The elements are documented

### Acceptance criteria
It should be possible to configure different addresses for different sensors, or a single address for all sensors, or any combination thereof.

**Comment by samuraitruong** [comment]
@anvabr  what about the simple solution that allow configure 'token address' in mint-token block received minted token?

**Comment by anvabr** [comment]
> @anvabr what about the simple solution that allow configure 'token address' in mint-token block received minted token?

It needs to be dynamic, as each Installer can have its own. We are already working on this, give us a little time it'd be done properly soon.
