### ISSUE TITLE
Web3.storage, an alternative to IPFS

### ISSUE THREAD

**Issue by prernaadev01** [hashgraph/guardian#1112]
### Problem description
Currently, as NFT.Storage is giving lots of issues such as file fetch delay, outage etc, we need to find an alternative to it to improve the performance and make the storage and operations more stable.

### Requirements
After having a call with Filecoin, they have suggested to use Web3.Storage for IPFS, which will improve performance. Here is the link: [https://web3.storage/](https://web3.storage/)

### Definition of done
Looking and doing complete research on Web3.Storage

### Acceptance criteria
Complete info and plan on implementing the above.

**Comment by prernaadev01** [comment]
@brianjohnson5972 Thank you for your comment. Can you please explain in detail about your requirement. Also, it would be really helpful if you can give us one of the UseCase on it.

**Comment by justin-atwell** [comment]
@brianjohnson5972, we just talked about this and it would be helpful if we knew what the needs were to prioritize it.

**Comment by brianjohnson5972** [comment]
Aside from not ending up in this same scenario again:
1) Testing using your own ipfs insulation
2) You plan on producing a lot of data and another provider is cheaper
