### ISSUE TITLE
feature request - data source to get list current aggregated mrv

### ISSUE THREAD

**Issue by samuraitruong** [hashgraph/guardian#1121]
### Problem description
In our system we have 2 ways to submit MRV, (realtime and manual) all MRV will aggregated and mint token. we don't want to process the 'manual mrv' when there are some aggregating mrv that submit by IoT device. The purpose of this are just make sure the data don't mix up in the VP. 

To solve this problem at the moment we will check aggregated_vc collection  before sending realtime MRV. If the collection empty we will trigger our custom logic to submit manual MRV this requires our backend to have access to mongodb and it not very accuracy because it work outside guardian

Updated:

Currently guardian aggregate MRV base on `owner` fields when data ingress via dataSource block (or whatever requestVCDocument blocks), we can archive our separation by add 2 separate flow logic to control different type of MRV (manual, realtime). this method working for us until now, But we going to implement more data separation such as we want mint the token per Site/Plan/Project they are dynamic and we don't want to build 1 policy per each of them, So I think it is great if we can add the separation attributes into 'Aggregation Block` that will works along with `Owner` field.   (sorry for solution again).

### Requirements
- Policy data sources block should have the way to display aggregated MRV (maybe applied the filter on VC document)
- A separation attributes config for 'AggregateBlock` such as the list of fields (projectId, siteId, meter id)
### Definition of done
- Policy data source block
- API

### Acceptance criteria
What are the criteria by which we determine if the issue has been resolved?

**Comment by anvabr** [comment]
@samuraitruong if I read this right you would like to distinguish between types of MRV data? This is possible via custom attributes assigned to VCs in sendToGuardianBlock, which then can be used for filtering.

![jjj](https://user-images.githubusercontent.com/32775532/188475513-25349ae1-e3eb-46fa-b870-5202cb5b4e9d.png)

**Comment by anvabr** [comment]
@samuraitruong is this still relevant for you? Did my answer address your query?

**Comment by samuraitruong** [comment]
@anvabr  sorry for late response

No it not what I need, My need is the policy can have data source block to display current data in **aggregated_vc** collection

DataSourceAddOn block now only support VC or VP, I would like to have another source 'Data Type' that get data from `aggregated_vc`. If we have this support I can build the policy to allow viewing current aggregating MRV 

![image](https://user-images.githubusercontent.com/1183138/203448241-2a976c23-7256-44dd-9313-d524253d8e66.png)

**Comment by dlin-me** [comment]
At Tymlez, we have two types of MRVs, one type is real time MRVs that come as data emitted from sensors, the other type of MRVs is manual batch inputs. As much as possible, we want to avoid manual  MRVs mingled with realtime MRVs in a VP.

Our current custom logic works around this by submitting manual MRVs only when there's no existing realtime MRVs in the `aggreagted_vs` collection.

Essentially, we need the ability to aggregate VCs by given attribute. However, this could result in dangling VCs. For example, when a batch of manual MRVs added up to 1.5 tonne of carbon, the remaining MRV for the 1.5 tonne of carbon will never get a chance to mint if no further manual MRVs submission.

**Comment by anvabr** [comment]
> Essentially, we need the ability to aggregate VCs by given attribute. However, this could result in dangling VCs. For example, when a batch of manual MRVs added up to 1.5 tonne of carbon, the remaining MRV for the 1.5 tonne of carbon will never get a chance to mint if no further manual MRVs submission.

Thank you for the explanation, now I understand the initial request and agree this is a good idea. I'll discuss with dev and come back to you.

**Comment by samuraitruong** [comment]
@Anvarbr this original request was raised when we try implement what David describe above. Mrv aggregate can be separate by issuer so we can archive our requirement without this feature. Maybe my description created confusion but the title is what we need

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by samuraitruong** [comment]
Also. It is great if we can update aggregate block to allow setting some MRV attributes to separate data.  We may use this for our purpose without make policy block include the logic as your designed above. FYI we archived this requirement by using diff owner when sending mrv data to guardian using externalDataSource block

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
