### ISSUE TITLE
UI/UX implementation of the 'Package' Policy Import Export

### ISSUE THREAD

**Issue by envisionblockchainpm** [hashgraph/guardian#119]
### Requirements
Review the design of the import/export UI elements and decide whether it can be repurposed for 'package' import export as per #50 or a new UI element needs to be created. Depending on the decision implement the UI part of functionality.

### DOD

- Acceptance criteria is fulfilled
- Documentation is updated to describe the new functionality

### Acceptance criteria
- Guardian UI contains facilities using which users can import/export 'packages' of policy and related artefacts.
- A confirmation screen listing the content of the .zip. (Role, Schemas, Policy Version, and Policy Description) is displayed post-import.

**Comment by danielnorkin** [comment]
As a user of the Guardian who imports the Policy .zip in the "Policy Creation Grid Screen" I should see a confirmation screen of everything that is included in the .zip. (Role, Schemas, Policy Version, and Policy Description)

**Comment by envisionblockchainpm** [comment]
Adding 8 Story Points and Assigning to Mendel

**Comment by envisionblockchainpm** [comment]
We decided that we will not show the UI of the components being exported as of yesterday 12/10. @mendelenvisionblockchain @danielnorkin @popowycz
