### ISSUE TITLE
Instructions in step 2 are invalid. Populating ID and Key info in .env and config files does nothing once the application is built and run

### ISSUE THREAD

**Issue by ed-marquez** [hashgraph/guardian#12]
See step 2 in: https://github.com/hashgraph/guardian#installation

Step 2 instructions are not valid, therefore confusing/unnecessary. 

**Repro steps:** 
I added my testnet credentials to the files, once the app is built and run the credentials have to be entered again or generated randomly. 

On that same note, when adding the credentials, if I add the public key instead of the private key of the account I get useful errors for the Installer accounts (something along the lines of "Invalid key length"). The error message for the RootAuthority is not helpful

**Comment by envisionblockchainpm** [comment]
As of today, @Pyatakov needs to provide @danielnorkin witih Text and he will verify the instructions. Alex is working on this one.

**Comment by envisionblockchainpm** [comment]
@danielnorkin As of today, we need to discuss this with you. Assigning this to you.

**Comment by danielnorkin** [comment]
@ed-marquez - Thanks for the ticket. We have updated the Readme in step 2 of the usage guide to address this. "Please keep in mind that this Hedera Operator ID and Operator Key is used for this reference implementation as a placeholder until there is a wallet integration. There will be other steps in the Demo Usage Guide that will require the generation of Operator IDs and Operator Keys. It is important to mention that the Operator IDs and Operator Keys in the .env will be used to generate demo accounts."

We understand that this is confusing, but it's a placeholder until we integrate a wallet to make the creation of demo accounts more simple. 

Please see the commit that addresses the change in the readme. Also, please note that this is in the Develop branch. And will be doing a release next week, which will push all code from Develop to main. https://github.com/hashgraph/guardian/commit/2e21f84589754a8b8e957bc6d24e42987e7a7f5f
