### ISSUE TITLE
Support lists in forms

### ISSUE THREAD

**Issue by anvabr** [hashgraph/guardian#120]
### Requirements
As a Guardian user, I want to be able to use lists within forms.

### Pre-requisite
Schema definition language includes provision for defining lists #41 

### DOD

- Forms support lists.
- Form input validation supports lists (as per #43).
- UI documentation is updated to include description of lists functionality.

### Acceptance Criteria

- When a user is using a schema containing a list it is represented in the UI in the Form where they are able to multi-select values in the lists.

### Alternatives

N/A

**Comment by envisionblockchainpm** [comment]
Assigning this one to Artem our new Full-Stack Developer pending ZenHub Access.
