### ISSUE TITLE
Assigning more than one role to interfaceContainerblock

### ISSUE THREAD

**Issue by prernaadev01** [hashgraph/guardian#1205]
### Problem description
I'm running into an issue where I cannot assign more than one role to an interfaceContainerBlock. If I have permissions as owner and esg_rep  for "Approve Rep Application", I can only see those steps as the owner. Here's my policy. Can someone see if this is a bug or something I'm doing wrong?

### Expected behavior
Need to assign more than one role to an InternfaceContainerBlock

**Comment by artembuslaev** [comment]
I also want to note that if you want to grant permissions to a block, you will also need to grant the same permissions to parent and child blocks. As example: if you want to set permissions for approve_application_page with full functionality, you should set same permissions in child and parent blocks.
![image](https://user-images.githubusercontent.com/68849616/186156443-a11c325e-d057-43c9-a37b-2598b57f389f.png)
