### ISSUE TITLE
UI/UX design for lists in Forms

### ISSUE THREAD

**Issue by anvabr** [hashgraph/guardian#121]
### Requirements
As a Guardian user, I want to be able to use lists within forms.

### Pre-requisite
Schema definition language includes provision for defining lists #41

### DOD
- Mock-up of the UI is created and reviewed by the stakeholder (Matt at DOVU)

### Acceptance Criteria

- The design supports the following: when a user is using a schema containing a list it is represented in the UI in the Form where they are able to multi-select values in the lists.

**Comment by envisionblockchainpm** [comment]
Adding 8 Story Points and Assigning to Mendel
