### ISSUE TITLE
Multiple guardian service instance policy error

### ISSUE THREAD

**Issue by samuraitruong** [hashgraph/guardian#1213]
### Problem description
In our production we have multiple instance of guardian-services running, When create & publish policy was handle by instance A  then later other API request going to instance B cause some inconsistent error

This happen because policy engine are using memory cache and not sync between multiple instance.

Current setup we have
```
2x guardian-service (this where problem come)
1 x auth-service
1 x logger-service
1 x ipfs-service
1 x api-gateway
Nats cluster with 2 replicas
single instance of MongoDB
```
### Step to reproduce
- Run 2 or more instance of guardian-service
- publish policy
- view policy or update policy data
- 

### Expected behavior
Policy state need to sync between multiple instances
### Screenshots
NA

**Comment by Pyatakov** [comment]
It's no longer relevant
