### ISSUE TITLE
UI/UX design for required fields

### ISSUE THREAD

**Issue by anvabr** [hashgraph/guardian#122]
### Requirements
As a Guardian user, I want to be told which fields are required within forms.

### Pre-requisite
Schema definition language includes provision for defining required items #118 

### DOD

- Mock-up of the UI is created and reviewed by the stakeholder

### Acceptance Criteria

The mock-ups show UI which supports the following functionality:
- When a user is using a schema containing required items it is represented in the UI in the Form
- Users are unable to submit a form if/when the required fields are empty, on an attempt to do so the omissions are clearly indicated.

**Comment by envisionblockchainpm** [comment]
Adding 8 Story Points and Assigning to Mendel

**Comment by envisionblockchainpm** [comment]
The Control is not something that we can get from any Framework, it is custom. It will take some time. We can't afford this time or Framework as per @mendelenvisionblockchain
