### ISSUE TITLE
Cannot get past profile completion for Standard Registry

### ISSUE THREAD

**Issue by AlexIvanHoward** [hashgraph/guardian#1268]
### Problem description
An error occurs when trying to complete the setup of the Standard Registry profile via the Demo Admin Panel of the Guardian. This occurred for the first time when I cloned the latest version of the main branch after merge #1265. (Prior to this I've been using the version of branch main as cloned somewhere during the first week of August 2022, so I cannot say for sure that it was this latest merge that introduced the problem.) 

### Step to reproduce
1. Clone the latest version of the main branch, as after merge #1265. 
2. Follow steps 1 to 5 of the installation guide [here](https://docs.hedera.com/guardian/getting-started/getting-started/installation).
3. Log into the "Standard Registry" account (or the "Verra" account) via the Demo Admin Panel, as served at http://localhost:3000/login.
4. Complete the fields under "Profile" > "Finish Setup" and click the "Connect" button at the bottom of the screen (see screenshot1.PNG for the values I used).
5. The loader will appear (see screenshot2.PNG), run until full and then take you back to the "Profile" > "Finish Setup" screen with the error shown below in screenshot3.PNG.

### Expected behavior
That the profile setup for the Standard Registry will complete without errors when all required fields have been filled in with valid values. 

### Screenshots
screenshot1.PNG:
<img src="https://user-images.githubusercontent.com/11308324/187984408-df3117df-8bd7-4271-bfeb-0219e6461508.PNG" width=50% height=50%>

screenshot2.PNG:
<img src="https://user-images.githubusercontent.com/11308324/187984149-4b0c0a2b-2dee-4ca8-845a-8d2d285a28e5.PNG" width=50% height=50%>

screenshot3.PNG:
<img src="https://user-images.githubusercontent.com/11308324/187984146-fdc49c56-f78b-49df-8118-2400f57235cb.PNG" width=50% height=50%>

**Comment by prernaadev01** [comment]
@AlexIvanHoward Thank you for raising the ticket. Can you please clear your cache memory once and try to rerun Guardian once. Thanks again

**Comment by AlexIvanHoward** [comment]
@prernaadev01 Aahhh, thank you! Sorry, I was pretty sure I did clear the cache as one of my many attempts at getting the Guardian to work again, but seems like I might not have done it after all. Sorry again!
