### ISSUE TITLE
Enum values in schemas created in bulk and/or from external source

### ISSUE THREAD

**Issue by anvabr** [hashgraph/guardian#1288]
### Problem description
There are use-cases in which Policy requires large number of 'enum' values in Schema to be added by users, which in turn then determine execution path of the policy. Current tools available for policy creator are limited.

### Requirements
Implement ability to add external source of enum values for use within the schemas, and thereby within policy, to avoid storying them directly in the schema.

### Definition of done
Users can provide a URL to the IPFS-stored file or type/paste values in the window directly.

### Acceptance criteria
This feature enables to realisation of the parent Epic.

**Comment by kirill-tolochko** [comment]
Maybe later we need to discuss structure and possible separators for values in the files for import. ATM separator is just the new line in the file.
