### ISSUE TITLE
Storing policy files in Github repo

### ISSUE THREAD

**Issue by prernaadev01** [hashgraph/guardian#1291]
### Problem description
Currently, we are storing only .policy files if each Policy in Demo Artifacts folder. We need to have complete policy files along with Schema files in the Github repo folder.

### Requirements
Storing all the Policy and Schema files of all Policies (IREC, Verra) in the Demo Artifacts folder. For Reference : https://github.com/hashgraph/guardian/tree/main/Demo%20Artifacts

### Definition of done
Storing and accessing all the files of the Policies in the Github repo.
Documentation to be updated

### Acceptance criteria
Demo Artifacts folder is updated as mentioned above

**Comment by Pyatakov** [comment]
Closing, as it was done
