### ISSUE TITLE
Restart Service functionality during policy editing not working

### ISSUE THREAD

**Issue by ed-marquez** [hashgraph/guardian#13]
While editing a policy, there's an action to restart the service: 
![image](https://user-images.githubusercontent.com/72571340/137556099-0e8f7c09-cad4-4829-8db8-a0bdf8282323.png)

The functionality wasn't clear to me at first. My understanding is that it's supposed to restart the guardian-ui-service running on docker. 

Two observations:
- If that's the intended functionality, then it's not working as intended. It only terminates the ui-service but does not restart it
- The purpose of having the functionality there is not clear (not sure if it's documented somewhere)

**Comment by envisionblockchainpm** [comment]
This will be started on Monday, 11/21 as per todays Scrum.
