### ISSUE TITLE
[Critical] - api-gateway crashing after mint > 1000 token 

### ISSUE THREAD

**Issue by samuraitruong** [hashgraph/guardian#1309]
### Problem description
After mint more than 1000 token on 1 policy, system keep crashing
```
 Error: guardians (get-block-data) send: Cannot run getMore on cursor 4558216390246917294, which was created in session 80f16dc8-423f-4870-8c6f-20ff82d8a3e9 - 47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=, without an lsid at PolicyEngine.<anonymous> (/usr/api-gateway/dist/helpers/service-requests-base.js:58:23) at Generator.next (<anonymous>) at fulfilled (/usr/api-gateway/dist/helpers/service-requests-base.js:5:58) at processTicksAndRejections (node:internal/process/task_queues:96:5) NR-LINKING|MzQ5NzYzMXxBUE18QVBQTElDQVRJT058MTU4NjE1MjUxOQ|guardian-api-gateway-b698b766b-xrhpv|edc734ebab7ea1291137324a252189f0|d2fd934fde92ef6e|guardian-api-gateway|
```
this happen when open the policy to view list of all VP
### Step to reproduce
1.  run 2.3.1
2. Mint > 1000 token per policy
3. Bug will happen

### Expected behavior
- fix above issue
- ideally, api-gateway should not crashed if any error happen when there an issue, error logs will be write into the log (if we have APM we can alarm & monitor them but should not crash the process
-

**Comment by prernaadev01** [comment]
@samuraitruong We have tried reproducing this error but couldn't do it. Can you please clarify us on the following things:
1) Do you have 1000 VPs? and can you see all of them? Or issue occurs when they are minting (or after mint) more than 1000 tokens and they have 1 VP and they can't see it.
2) Where is the issue occurring, is it at interfaceSourceBlock (grid with documents), or is it at filterAddonBlock (when you select in drop-down document to filter documents in the grid) or somewhere else.
3) Can you also let us know mongo version?
4) Also we would suggest you to use pagination block if problem is in interfaceSourceBlock.

**Comment by samuraitruong** [comment]
@prernaadev01  this issue related to missing database index before I think it already fixed with the latest release

- mongo v5
- I believe the guardian crashed when we view VP list using DocumentSourceBlock. (our front-end connect via guardian API to get list of VP)

At the moment we believe this issue no longer happen on 2.6.1 since the index added to VP collection.
