### ISSUE TITLE
Tying a Policy Version to a Policy Version Topic

### ISSUE THREAD

**Issue by jameslevingston** [hashgraph/guardian#1326]
### Problem description

When a new policy version is published, there doesn't appear to be an explicit tie on the ledger between that policy version's publish event and the policy version topic for that policy version.

This means that we can't tie downstream messages for registrants, dynamic topics, etc. to a specific policy version using only ledger data.

### Step to reproduce

1. Create a new policy
2. Publish a version of that policy
3. From the Policies tab in the Guardian, note the Hedera topic id associated with that policy version you just published
4. Look at that HCS topic on a ledger explorer. E.g., [LedgerWorks Explore](https://explore.lworks.io/), https://hashscan.io/, etc.
5. Note there is a publish-policy event for the newly published policy version and a follow-up create-topic event for the topic corresponding to that published policy. However, there is no direct tie between these two messages to know which policy version a topic corresponds to

#### Publish-Policy Event
`{"id":"0bc6e6cd-a44e-4ee4-aff2-dcddf2d82d73","status":"ISSUE","type":"Instance-Policy","action":"publish-policy","lang":"en-US","uuid":"b4045988-857d-4b6a-8a50-cbba850da27a","name":"Makin' offsets","description":"The iRec with my tweaks","topicDescription":"iRec Description","version":"0.0.1","policyTag":"Tag_1663645371957","owner":"did:hedera:testnet:4bZHswdCajL7BVHexnyVSeMMpd5cutAq33xunCd99dbP;hedera:testnet:tid=0.0.48288995","topicId":"0.0.48288996","instanceTopicId":null,"cid":"bafkreid7rnymdrdfror5qeuj6onurrtbepbvc3up3je6ohdwswiv6wyw34","url":"https://ipfs.io/ipfs/bafkreid7rnymdrdfror5qeuj6onurrtbepbvc3up3je6ohdwswiv6wyw34"}`

#### Create-Topic Event

`{"id":"f8aaa9ce-c0b3-4842-b17f-1c87c8fbf20b","status":"ISSUE","type":"Topic","action":"create-topic","lang":"en-US","name":"Makin' offsets","description":"iRec Description","owner":"did:hedera:testnet:4bZHswdCajL7BVHexnyVSeMMpd5cutAq33xunCd99dbP;hedera:testnet:tid=0.0.48288995","messageType":"INSTANCE_POLICY_TOPIC","childId":"0.0.48288998","parentId":null,"rationale":"1663645511.574776818"}`

### Expected behavior
When looking solely at ledger/IPFS data, a policy version can be tied directly to the topic created for that policy version.

**Comment by anvabr** [comment]
There is a problem in the message: "instanceTopicId":null. The idea was that it would contain the right topicID. This is fixed now.

As it was rightly noted, rationale in 'create-topic' references 'publish-policy', so this can also be used for this. However it'd be easier to only use instanceTopicId (which is fixed now).
