### ISSUE TITLE
Getting connection error while try to access 3000 port and run the application 

### ISSUE THREAD

**Issue by jahidulrudro** [hashgraph/guardian#1351]
Hi 
I am running guardian with docker after build the docker compose dv yml file and try to access my url with 3000 port its responding with below error at my console  and at browser window i am getting 502 Bad Gateway

connect() failed (111: Connection refused) while connecting to upstream, client: 58.26.40.10,

**Comment by prernaadev01** [comment]
@jahidulrudro Thank you for the ticket. We tried replicating this issue internally, but we are not able to do it. So, we would request you to share more info with us such as Logs, Screenshots of the browser, Docker compose file if changed, Request URL being made. This will help us to solve it asap.

**Comment by prernaadev01** [comment]
As we haven't heard back since 13 days, we are closing this ticket. Thanks
