### ISSUE TITLE
Vault import failed as file name is too long

### ISSUE THREAD

**Issue by samuraitruong** [hashgraph/guardian#1405]
### Problem description
- when import the existing wallet into harshicop vault. we using sha512 to generate the unique key cause the file name is too long (file name limit is base on the os that running the vault container)

If hash name is generate unique lookup key. I think MD5 or Sha1 or Sha256 is acceptable to avoid this error. I have tested by change to sha256, the migration works as expected.

### Step to reproduce
1. setup hosted vault run in docker
2. run guardian with auth-service to migrate all key into vaule
3. error occurred as below logs
4. 
### Screenshots
```
Error: 1 error occurred:
        * open /vault/file/logical/b6aeef0a-86f1-db86-fad8-78682a5aff34/5c82bc2f-4fa3-69f5-8af7-dfd053b72b6c/metadata/_mvniVZiTEJfY44lT28bSl8uYc3ICG4NGEfMnXg1LS8ZL33DnQ6h4t6jCrV3SWLnqbuqCQI6H68sVCDEQTLp0sZEJZQq8OTEmJUjyDZOLfj8DvTaVIHSMi6W3xKrHZ3RrJaH011W5XX4uIjnuyRUlDJzMSWAwh3iXp7HqTonsYpNyD5CJhSQpD9YdNMcjcuN4TIU3CaJHIGuleoZfnqXuktfNRDliwBIGv3ucVDYz50yFGa30o8raE0RxLh10F7Eu2EkBuCgM7onU8WIjcjnwwzgPLc: file name too long


    at handleVaultResponse (/usr/auth-service/node_modules/node-vault/src/index.js:58:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-10-17T04:22:37.386Z [AUTH_SERVICE]: Error: 1 error occurred:
        * open /vault/file/logical/b6aeef0a-86f1-db86-fad8-78682a5aff34/5c82bc2f-4fa3-69f5-8af7-dfd053b72b6c/metadata/_mvniVZiTEJfY44lT28bSl8uYc3ICG4NGEfMnXg1LS8ZL33DnQ6h4t6jCrV3SWLnqbuqCQI6H68sVCDEQTLp0sZEJZQq8OTEmJUjyDZOLfj8DvTaVIHSMi6W3xKrHZ3RrJaH011W5XX4uIjnuyRUlDJzMSWAwh3iXp7HqTonsYpNyD5CJhSQpD9YdNMcjcuN4TIU3CaJHIGuleoZfnqXuktfNRDliwBIGv3ucVDYz50yFGa30o8raE0RxLh10F7Eu2EkBuCgM7onU8WIjcjnwwzgPLc: file name too long


    at handleVaultResponse (/usr/auth-service/node_modules/node-vault/src/index.js:58:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by ashutoshreact2022** [comment]
Hi @samuraitruong To reproduce this issue, we would request you to send some more info such as Docker Version and Wallet image version. Thanks

**Comment by samuraitruong** [comment]
@ashutoshreact2022  this is very simple to reproduce so far it always happen on all our development environment using macos (both intel + m1`) -  MACOS Montery - Docker latest version

It also happen on our production environment which run on GKE cluster : 1.22.12-gke.2300 and vault was install using 
helm chart  - https://github.com/hashicorp/vault-helm
