### ISSUE TITLE
AWS Ec2 Instance | Docker Setup Successfully | Getting error in final step

### ISSUE THREAD

**Issue by erdeepaksharma** [hashgraph/guardian#1416]
### Problem description
I am using AWS ec2 (Ubuntu) machine to set up the guardian and everything looks fine but when I run the "docker-compose up -d --build" command then it stop on the "ng build" command. Please check in the following screenshot.

![image](https://user-images.githubusercontent.com/9428174/196234206-65d31c78-48a2-41a5-8efd-3eefb3fb6d47.png)

NOTE: I tried, and it's working fine on my local system (window 10)

### Requirements
How can I set up this on my aws-ec2 instance

**Comment by Bartleonid** [comment]
Reproduced on Mac M1 chip
![screenshot_444.png](https://images.zenhubusercontent.com/5df7f0e943709742f9d295dc/348cd30b-7868-45fc-b567-bede69c12bac)

**Comment by ashutoshreact2022** [comment]
Hi @erdeepaksharma Thank you for raising the ticket. We have looked into it. Can you please try the following:
Please replace web-proxy/Dockerfile with the below code:
FROM node:16 as frontendBuilder
WORKDIR /usr/interfaces
COPY ./interfaces/package*.json ./
COPY ./interfaces/tsconfig.json ./
ADD ./interfaces/src ./src/.
RUN npm install --force
RUN npm pack
WORKDIR /usr/local/frontend
COPY ./frontend/. /usr/local/frontend
RUN npm install --force /usr/interfaces/guardian-interfaces-*.tgz
RUN npm install --force
RUN npm run build
FROM nginx:latest
ENV PLATFORM="docker"
COPY ./web-proxy/configs/default.conf /etc/nginx/conf.d/default.conf
COPY --from=frontendBuilder /usr/local/frontend/dist/guardian /usr/share/nginx/html
EXPOSE 80

**Comment by prernaadev01** [comment]
Hi @erdeepaksharma Thank you for raising the ticket. We have looked into it. Can you please try the following:
Please replace web-proxy/Dockerfile with the below code:
FROM node:16 as frontendBuilder
WORKDIR /usr/interfaces
COPY ./interfaces/package*.json ./
COPY ./interfaces/tsconfig.json ./
ADD ./interfaces/src ./src/.
RUN npm install --force
RUN npm pack
WORKDIR /usr/local/frontend
COPY ./frontend/. /usr/local/frontend
RUN npm install --force /usr/interfaces/guardian-interfaces-*.tgz
RUN npm install --force
RUN npm run build
FROM nginx:latest
ENV PLATFORM="docker"
COPY ./web-proxy/configs/default.conf /etc/nginx/conf.d/default.conf
COPY --from=frontendBuilder /usr/local/frontend/dist/guardian /usr/share/nginx/html
EXPOSE 80
