### ISSUE TITLE
Mint-Token worker task loop forever

### ISSUE THREAD

**Issue by samuraitruong** [hashgraph/guardian#1434]
### Problem description
I am not sure how this happen, It look like when worker slow and some some token action keep loop forever, please see the screenshot

Actually 1 of mint action was successful and token minted but the job queue keep sending new task.

### Screenshots
<img width="831" alt="image" src="https://user-images.githubusercontent.com/1183138/197683586-13b0241f-95cc-46bf-943e-ee9f4e17f6ee.png">

**Comment by simvalery** [comment]
The number of retries is limited to 25, after which it'll terminate execution and return an error
