### ISSUE TITLE
Load testing on MGS

### ISSUE THREAD

**Issue by prernaadev01** [hashgraph/guardian#1453]
### Problem description
As we are coming closer to launch of MGS, we need to perform detailed load testing on the application.

### Requirements
Need to perform end to end load testing on API and UI of MGS application in both positive and negative cases

### Definition of done
Load Testing to be successful with documentation

### Acceptance criteria
100% working as mentioned above

**Comment by Bartleonid** [comment]
Blocked by  “Topic not set”  https://envision-blockchain.slack.com/archives/C042Z385THQ/p1666107477736919 Supposedly issue might be due to INITIALIZATION_TOPIC_ID not set up. As a result cannot create test users.
