### ISSUE TITLE
NFTs created from a policy do not include expected memo/metadata timestamp value

### ISSUE THREAD

**Issue by paul-burtjr** [hashgraph/guardian#1465]
### Problem description
In the memo field of newly minted tokens we are NOT finding a Verifiable Link. We also do not find the value populated for the metadata field on the NFT serials.

This was found using the 2.5.1 version of the guardian

### Step to reproduce
1. Go to the guardian, as a standard registry import iREC 4 : 1662642008.325450377
2. Add and approve a registrant
3. Create and approve a device
4. Create and approve an issue request
5. Retrieve the initialized tokenId created for this policy
7. Send a request to GET the nft from the ledger via the `/tokens/{tokenId}`
8. Check the memo field for the Verifiable Link (timestamp)
9. Send a request to GET the nft serial from the ledger `/tokens/{tokenId}/nfts/{serialNumber}`
10. Check the metadata field for the Verifiable Link (timestamp)

### Expected behavior
Expected to find a Verifiable Link (timestamp) in the NFT data

**Comment by cohuebn** [comment]
For context, when I run the same scenario using the [2.4.2](https://github.com/hashgraph/guardian/releases/tag/v2.4.2) version of the Guardian with the exact same policy, I see a timestamp in the memo field. So this appears to either be a regression or data change that our team was not aware of.

**Comment by paul-burtjr** [comment]
Example NFT missing memo: https://explore.lworks.io/testnet/tokens/0.0.48776465/nfts/111
