### ISSUE TITLE
Use agnostic `ipfs://` prefix for every URL instead of fixed ipfs.io gateway

### ISSUE THREAD

**Issue by Neurone** [hashgraph/guardian#1472]
### Problem description
Guardian currently uses ipfs.io as a default gateway for every IPFS URL in VCs.

Using a specific centralized gateway exposes you to several issues, especially in production environments (availability of the service, connection to external servers, security, etc.), and it does not allow you to take full advantage of the decentralized 
nature of IPFS. This behavior also forces the client to parse the URL and extract the CID if it wants to use a local or custom node.

### Requirements
Replace all `http://ipfs.io/ipfs/` URLs in VCs and documentation with the agostic `ipfs://` prefix.

### Definition of done
Every VC created by Guardian doesn't contain references to centralized services. Documentation is updated accordingly.

### Acceptance criteria
Unit tests will be created to verify this behavior, and Guardian will use the gateway configured by the user in the `IPFS_PUBLIC_GATEWAY` configuration variable as the default gateway for tests and operations.

**Comment by cj-oci** [comment]
This will be good direction towards decentralization. This way Guardian assets are not tied to a single gateway point of failure.
