### ISSUE TITLE
Step 6 of Demo Usage Guide should explicitly mention token connection to the mint step

### ISSUE THREAD

**Issue by sergmetelin** [hashgraph/guardian#15]
Step 6 of the Demo Usage Guide in README.md doesn't currently mention that the `mint_token` workflow step needs to be connected to the token created in the previous step. 

It needs to be added

**Comment by danielnorkin** [comment]
@sergmetelin - There is no connection to the token in step 6. The adding of a token to the "mint token" block happens in step 7. It actually says it in the demo usage guide. However, to highlight it more, I have added a screenshot.
