### ISSUE TITLE
Can we have env var to control MQ_MESSAGE_CHUNK

### ISSUE THREAD

**Issue by samuraitruong** [hashgraph/guardian#1550]
### Problem description
At the moment MQ_MESSAGE_CHUNK is hard coded to 1MB, We wish that can control by environment var
Also I think default value better to set to 5MB instead of 1MB

### Requirements
- Make MQ_MESSAGE_CHUNK read from process.env.MQ_MESSAGE_CHUNK with default value 

### Definition of done
How do we know we've fully dealt with it?

### Acceptance criteria
What are the criteria by which we determine if the issue has been resolved?

**Comment by prernaadev01** [comment]
@samuraitruong Quick update on this :
We have MQ_MESSAGE_CHUNK setting in .env/.env.docker files of all services. If you want to control message chunk size, you can change the value of this setting, BUT value should be same in all services, AND if you use value more than 1MB then make sure that in nats configuration settings max_payload has a value more than MQ_MESSAGE_CHUNK  setting. Also nats do not recommend to use value of max_payload over 8MB. MQ_MESSAGE_CHUNK is given in bytes, if this setting has incorrect value or this setting is missing - 1MB will be used

**Comment by samuraitruong** [comment]
@prernaadev01  Thanks, we have 1 central place to set the var in production so the value will always the same cross all the service. But make sure it not confuse anyone please update readme or document with above constraints.
