### ISSUE TITLE
Tutorials: Code User Guide

### ISSUE THREAD

**Issue by blockchain-biopharma** [hashgraph/guardian#156]
The goal Hedera wants is so someone has access to the Guide

Tomorrow Shawn to go through in Scrum and let the Dev Team we need them for this.  
(Daniel) Write up Intro + (Andreas) Write up a Glossary (BOTH EPICS).
(Dev Team Member) Records the Video Without Voiceover Clearly, just the different steps. Andreas then needs to look at that video and Create a script from that
Andreas to provide Daniel Script and What to Say.
Daniel then needs to do the voiceover for the video based on the Script
Daniel needs to create the Markdown File for the Repo
Andreas will put the code into the Markdown File that is used in the Code Video (NOT the UI Video).

**Comment by envisionblockchainpm** [comment]
Next step is on Andrey to translate from Russian to English.
