### ISSUE TITLE
Enable spatial data types in schemas

### ISSUE THREAD

**Issue by anvabr** [hashgraph/guardian#1563]
### Problem description
Spatial data is important for Guardian as many environmental projects involve geographic regions. Currently there is no standard way to represent this data in Guardian, however widely used de-facto standard formats for spatial data persistence and exchange exists such as  [GeoJSON]( https://geojson.org ), [WKT/WKB](https://en.wikipedia.org/wiki/Well-known_text_representation_of_geometry#Well-known_binary). 

See also #1930 follow-up ticket.

### Requirements
Introduce support of geojson.org datatype into Guardian schemas such that:

- Data values in such fields get validated when appropriate (e.g. changed, saved, loaded etc)
- Data representing geographic regions can be shown in the UI in a graphic format (using a 3rd party map provider)
- Accuracy/precision of the geo data published as metadata

### Definition of done

- Guardian support geospatial data types in schemas/APIs
- Users can enter GeoJSON data as data (perhaps generated by [QGIS](https://www.qgis.org/en/site/), R, [ArcGIS](https://www.arcgis.com/index.html)), or via drawing on the map.
- Guardian UI can display geographic information on a map
- The usage of such data is documented
- At least one sample policy contains examples of geo-spatial data usage

### Acceptance criteria
DOD criteria above is fulfilled.

**Comment by voycey** [comment]
@anvabr Could you also consider the support of WKT? We can convert to GeoJSON if necessary but there are some things that GeoJSON cannot support (circles for example)

https://macwright.com/2015/03/23/geojson-second-bite.html#what-you-cant-do-with-geojson

**Comment by nextalias** [comment]
ESRI shape files is a common interchange format.

Gdal is the most common translation tool used for vector and raster formats.
https://gdal.org/
