### ISSUE TITLE
Schema updated with same version

### ISSUE THREAD

**Issue by samuraitruong** [hashgraph/guardian#1573]
### Problem description
When edit the. policy schema after published  then republished policy, the schema was published with same version

### Step to reproduce
1. create policy with a schema then published as 1.0.0
2. Update policy with changes in schema then republish policy
3. the policy is published and the updated schema will be published with same version.

### Screenshots
![image](https://user-images.githubusercontent.com/1183138/206329371-4c24d36d-774b-45d3-bcc5-cc3a34f9c8f2.png)

**Comment by prernaadev01** [comment]
@samuraitruong Thank you for the ticket.
Can you please help us out in reproducing this issue. We tried it internally, but couldn't do it.
Also, can you please explain us more of how you were able to republish the policy in Guardian?
Thanks,
Prernaa
