### ISSUE TITLE
Documentation to Guardian APIs

### ISSUE THREAD

**Issue by tvsotiya** [hashgraph/guardian#159]
**Requirements**
High-Priority Community User Request: you please give me a link to the documentation of the Guardian's API?

**Pre-requisite**
API Documentation. As of 11/13, this should have been provided?? @Pyatakov please assist with the above?

**Definition of Done**
PDF, MD, README, or other API Documentation Links to be Provided?

**Acceptance Criteria:**
Documentation Links

### Solution

Add link to documentation

**Comment by envisionblockchainpm** [comment]
@tvsotiya Just checked with our Solutions Architect, and this info is in the README File in the Repo. This is both Swagger API and Postman API Documentation for the OS Guardian. Let me know if you have issues finding it.

**Comment by envisionblockchainpm** [comment]
Documentation Links were sent to the Stakeholder.

**Comment by envisionblockchainpm** [comment]
Here is a link to the README: https://github.com/hashgraph/guardian/blob/main/README.md

@tvsotiya

**Comment by envisionblockchainpm** [comment]
We just realized that we are missing the parameters and are investigating it. We are reopening this ticket, providing a hot fix for the release, and we will keep you updated.

**Comment by envisionblockchainpm** [comment]
This ticket can be moved to Closed as this was fixed and Patched.
