### ISSUE TITLE
Component Specific Policy Field Export

### ISSUE THREAD

**Issue by blockchain-biopharma** [hashgraph/guardian#161]
**Requirements**
As a user I want the ability to, when exporting a policy to, to select specific components of the policy to be exported instead of everything in one shot.

**Pre-requisite**
Policy Field  Information Architecture. Unit Tests.

**Definition of Done**
IA Diagram. Unit Testing Results. 

**Acceptance Criteria:**
PDF or Other Documentation of DOD?

**Comment by anvabr** [comment]
@danielnorkin is this really required?
