### ISSUE TITLE
Expose subscribed event or log messages to an external application

### ISSUE THREAD

**Issue by felipeneuhauss** [hashgraph/guardian#1634]
### Problem description
The proposal is to integrate the Guardian application with external monitoring tools to expose internal ` nats events` or strategic logs, messages, errors, and so on.

### Requirements
 We need to build a new layer (js file) where we can define the channel where errors, tracing, or subscribed events will be exposed. 

Here is a simple documentation of how we can obtain these events: https://docs.hedera.com/guardian/guardian/standard-registry/external-events. However, the idea is to provide the integration with [grafana](https://grafana.com/oss/loki/).

Either the tracking level or the channel used will be provided via env variables.

MONITORING_CHANNEL=grafana // cloud
MONITORING_LEVEL="fatal" //  "critical", "error", "warning", "log", "info", and "debug"
MONITORING_EVENTS=true // to activate the script that will log 

**Note:** If the Guardian application is running in a cloud service like AWS or Google App Engine any `console.log` in the code will automatically register messages in its built-in logging solution such as AWS Cloud Watch or Google Logging.

To avoid the amount of code changed we can explore something like that to intercept the application errors.

```
app.use(function(req, res, next) {
  next(createError(404));
});

// error handler
app.use(function(err, req, res, next) {
  // set locals, only providing error in development
 console.log('Erro request:', JSON.stringify({
    statusCode: err.status,
    message: err.message,
    stack: req.app.get('env') === 'development' ? err.stack : undefined
  }));
  res.status(err.status || 500)
  res.send({
    statusCode: err.status,
    message: err.message,
    stack: req.app.get('env') === 'development' ? err.stack : undefined
  })
});
```

### Definition of done
The easy integration with external tools to expose internal data such as logs, errors, and nats events.

### Acceptance criteria
An easy configuration that allows the client to switch between different technologies to log data externally.

**Comment by Neurone** [comment]
Hi, I try to recap the task.

We need to:
- Monitor the state of all services/microservices that compose Guardian
- Make external tools able to read this information
- Leverage enterprise environment settings. This means we should expect clients already use other tools to monitor their environments, and we should be compliant with those tools

Potential solution:
- Expose application events, so clients can understand what's happening inside the product as a whole and what's happened in the past
- Expose service metrics to understand the current and past status of the service (CPU, RAM, disk, etc.)

Details of the potential solution:
- Define interesting applications events to expose externally
- Define interesting metrics to expose externally
- Expose application events
  - JS library to log events (logger)
  - Embed the logger in every service
  - Update the code to expose interesting events
  - Configure the logger to send events to nats
- Expose metrics
  - Embed Prometheus in every service
  - Expose updated metrics
- Create a new `application-events` service that
  - Reads events from nats
  - Saves those events for processing
  - Sends those events to external tools
  - Can be configured to
    - Process and send events to different enterprise tools/enterprise services
    - Process and send events to different agnostic tools (i.e., get/post to URL endpoints, send emails)
- Create a `metric-service` service that
  - Scrapes exposed metrics periodically from every service
  - Saves those metrics for processing
  - Exposes all updated metrics to be used by external enterpirse and agnostic scraping tools
  - Can be configured to
    - Prepare/format data for specific external scraping tool needs
    - Periodically send metrics to nats so that they can be processed as events and pushed to external tools
- `application-events` and `metrics-service` uses the exact mechanisms to expose events and metrics as any other service, so we don't have custom behaviors. This means they will have the same configuration options to expose data as other services and specific configurations for their purposes.
- Configuration for all the above features will be integrated with the new Environment concept introduced with issue #1607 (https://github.com/hashgraph/guardian/issues/1607)
- Create documentation for all the common configurations
- Create dedicated documentation for the new `application-events` and `metrics-service`
  - Some optional / nice-to-have features, in order of priority:
    - Create a [Grafana](https://grafana.com/grafana/) dashboard (JSON file) to reads metrics from Guardian
    - Provide a pre-configured `grafana-service` for visualization of metrics in Guardian
    - Use Guardian-CLI to create proper configuration files.
    - Use Guardian-CLI to send test events to nats.

Additional notes:
- The component `guardian-service` already exposes events via nats (https://docs.hedera.com/guardian/guardian/standard-registry/external-events). Let's evaluate if we can leverage and extend that mechanism to all the other services.
