### ISSUE TITLE
Develop Production Deployment of Hashicorp Vault

### ISSUE THREAD

**Issue by hnamazianeu** [hashgraph/guardian#1650]
### Problem description
This user story is intended to create config and docker compose files as well as developing scripts required for deployment of Vault Architecture in production. A Makefile in which up/down procedures are included is required to make the whole process simple.

### Definition of done
Vault architecture and configurations in production must include following requirements:
- The Vault Architecture consists of an instance of Hashicorp Vault as key manager engine and an instance of Hashicorp Consul in persistence layer
- All instances must be running in docker containers
- Root key or Username/Password must not be exposed in plain text
- Each service must be provided by specific credential (certificate, private key)
- TLS communication must be enabled
- TLS PKIs must be encrypted (PEM format with passphrase is recommended)
- Scripts to generate self-signed certificates must be provided
- Vault-CA* to generate certificates can be configured (if necessary in case of not existing valid certificates)
- Unsealing process of vault must not be skipped
- Unsealing keys must be stored securely by multi-party
- Unsealing keys (number of keys) must be configurable
- Vault storage must not chosen as In-Memory or file; Hashicorp Consul is preferred
- Vault UI can be enabled/disabled through environment variables
- Make commands must be provided to simplify the processes

### Acceptance criteria
The whole Vault architecture must be deployed in docker containers by running scripts via simple Make command procedure. Additionally all CRUD operations must be tested successfully via a simple Make test command.

**Comment by voycey** [comment]
Hi @hnamazianeu, 

I am working on something similar to this but it is specific to GCP that runs only on Cloud Run (making it super cheap), its probably not what you are after exactly - would it matter the cloud for this?

**Comment by hnamazianeu** [comment]
> Hi @hnamazianeu,
> 
> I am working on something similar to this but it is specific to GCP that runs only on Cloud Run (making it super cheap), its probably not what you are after exactly - would it matter the cloud for this?

I'm trying to prepare a op-premise Vault deployment with production config, as mentioned in [1650](https://github.com/hashgraph/guardian/issues/1650) regardless to the cloud itself
