### ISSUE TITLE
Schemas corrupted during policy import

### ISSUE THREAD

**Issue by AlexIvanHoward** [hashgraph/guardian#1678]
### Problem description

There appears to be a bug in the Guardian that corrupts some schemas when one imports a policy (whether via message identifier or as a file). The affected schemas are the ones that have fields of which the types are other schemas which also have fields of type schema, i.e. doubly nested schema fields. The policies won't publish or go into dry run mode if the user does not fix the corrupted files.

### Step to reproduce
1. Import the 'Improved Cookstove Policy' via testnet message id 1671834296.269067003
2. Note the error that is displayed to the user regarding its failure to import the 'Document Review: Project Listing Application (DR-PLA)' schema (see screenshot below).
3. Import the 'Document Review: Project Listing Application (DR-PLA)' schema individually via message identifier 1671834259.305678291
4. Once imported, open the schema for editing and scroll down to the 'Project location' field. Notice that it is empty. It's field type should have been 'Location'. Set die field type to 'Location' and save the updated schema.
5. Although no other errors were displayed during the policy import process, the 'GeoLine' and 'GeoPolygon' schemas were also corrupted. Open the GeoLine and GeoPolygon schemas for editing. Notice how their field types are empty. They should all be set to 'GeoCoordinate' for the policy to work.

### Expected behavior
Schemas with other schemas as their field types, regardless of whether or not those schemas also make use of further schemas as their field types, should import successfully without being corrupted in any way. No field types should be cleared during the import.

### Screenshots
![FailedToImportDRPLA](https://user-images.githubusercontent.com/11308324/213913608-b6cab20b-fc47-4039-89b1-c491dc49a681.PNG)

**Comment by prernaadev01** [comment]
@simvalery The new timestamps of the policies are:
Improved Cookstove Policy: 1675717221.801390365
ICP - Agent Application Subpolicy: 1675689595.565224878
ICP - PDD Validation Subpolicy: 1675716931.544642703
ICP - MR Verification Subpolicy: 1675717076.245262673

**Comment by kirill-tolochko** [comment]
Wasn't able to reproduce this one.
