### ISSUE TITLE
Remove hardcoded transaction fee 

### ISSUE THREAD

**Issue by anvabr** [hashgraph/guardian#1712]
### Problem description
Hedera SDK has an issue where transaction fees are incorrectly calculated, it is recorded [here](https://github.com/hashgraph/hedera-sdk-js/issues/1425).

In order to progress with our delivery and test for the retirement functionality we have hardcoded 0.05 hbar transaction fee to pay for the `ContractCallQuery` transactions to reitre tokens. 

### Requirements
Once Hedera SDK team fixes the problem remove the hardcoded value

### Definition of done
Fees are calculated dynamically

### Acceptance criteria
N/A

**Comment by prernaadev01** [comment]
Ticket is created for Hedera: https://github.com/hashgraph/hedera-sdk-js/issues/1425
