### ISSUE TITLE
"Help Text" field type for schemas

### ISSUE THREAD

**Issue by AlexIvanHoward** [hashgraph/guardian#1717]
### Problem description
There is currently no way to provide explanations/information/hints to the user of a schema in-between two questions. This is problematic in a case where one would, for example, want to say to the schema user, "The next three questions will guide you through identifying your baseline scenario. A baseline scenario is \<and then some brief explanation of what a baseline scenario is.\>"

### Requirements
Add a 'Help text' field type to the list of simple field types available when designing a schema. This field type should not require any input from the user. It should simply give the schema designer the means to provide instructions/useful information to the future schema users. Fields of type 'Help text' should not be captured in the VCs resulting from schemas that employ the ''Help text' field type, because they do not collect any input from the schema users.

### Definition of done
There is a 'Help text' simple field type available to schema designers that will allow the schema designers to provide users of the schema with additional/auxiliary information in-between two questions.

### Acceptance criteria
There is a 'Help text' simple field type available to schema designers that will allow the schema designers to provide users of the schema with additional/auxiliary information in-between two questions.

**Comment by kirill-tolochko** [comment]
If you try to put anything in the text field in the api you get the error:
`setData: {"type":"JSON_SCHEMA_VALIDATION_ERROR","details":[{"instancePath":"/field1/field20","schemaPath":"#bb8a2f8c-0729-4329-b4f4-1536df2d9685/properties/field20/type","keyword":"type","params":{"type":"null"},"message":"must be null"}]}`

but if you try to put null to this field, you get the response:

```
setData: credential is not valid JSON-LD: {
  "type": "MISSING_PROPERTIES_IN_CONTEXT",
  "details": [
    "field1.undefined"
  ]
}
```

**Comment by kirill-tolochko** [comment]
We decided not to fix this issue, users shouldn't put any data in this field anyway

**Comment by christiaanpauw** [comment]
@kirill-tolochko Are you sure you correctly understood the feature request? Your response looks like it is the response to another issue.

**Comment by kirill-tolochko** [comment]
@christiaanpauw I think I did understand it correctly. This one was just check, that it's not possible to put anything in this field using API.

Main point of the feature request is to have some kind of uneditable field with text (something like the hint) to the future users of the schema. And this help text shouldn't be presented in the VC. Correct?
