### ISSUE TITLE
User driven MRV data interface

### ISSUE THREAD

**Issue by ieumuzair** [hashgraph/guardian#1741]
Guardian's forms, where the user inputs data, should be accessible for all users on a mobile device. In order to address these changes, media queries and minimal changes to the components TypeScript and HTML files are required so that nothing changes on a device with a larger screen. All of our media queries will be applied at a maximum width of 810px to ensure that our changes are consistent with the login page and some additions to the components TypeScript and HTML have and will be made depending on the form at hand.

**Comment by PensoGlide** [comment]
The proposal for this topic is to use, as agreed, CSS media queries with a screen width of 810px or less as well as
minimal changes to components TypeScript and HTML.

For the time being, we have concentrated on the flow of the iREC policies and other forms that are visible to the user but we will test the new designs with other workflows. The following forms will be modified:

- Users first registration into Guardian;
- User creating a device;
- User creating an issue once taking part in a policy;
- User policy registration application;
- User creating a retire request;
- User Create / Join Multi Policy;

- Standard Registry first registration into Guardian;
- Standard Registry creating a new token;
- Standard Registry publishing a draft of a policy;
- Standard Registry importing policies.

The links to all of the Figma designs that will be followed can be checked [here](https://www.figma.com/file/6KjQq4sXIY2miUG3DZJROo/Guardian?node-id=0%3A1&t=R8AI9Ah0gopbvhXb-1).
