### ISSUE TITLE
CLI integration

### ISSUE THREAD

**Issue by ieumuzair** [hashgraph/guardian#1743]
Guardian-Cli is a useful command-line application developed for simplifying management of guardian project from cloning the repository to checkout to a specific release version, start/stop the project by docker and PM2 as well as cleaning the project and more features. It is supposed guardian-cli to be pushed into npm registry in order that users can install it as global package and use cli commands entire their machine or servers.

**Comment by dubgeis** [comment]
This may become Hex Trust or another custodian @ieumuzair
