### ISSUE TITLE
Backup tools, documentations and methodologies

### ISSUE THREAD

**Issue by ieumuzair** [hashgraph/guardian#1750]
**Problem Description**
-----------------------------
Clients (the implementer company) should be able to backup (both fully and incrementally) and recover their installation and data. Supporting partial recovery of the data is a desirable feature, but not mandatory.

**Requirements what needs to be done**
---------------------------------------------
A policy related to backup tools, documentation, and methodologies for Hedera Guardian system will outline the 1) tools 2) documentation and 3) guidelines for ensuring the safety and security of critical data in case of system failures, disasters, or cyberattacks.

- Tools are the software/scripts that the user would actually need to run to back up and restore a Guardian installation.
- Documentation is the recipe the user follows to back up and restore an instance of Guardian.
- Guidelines are more general suggestions, to give hints in case of different architectures or special cases (ie. "if you are running a load balancer before the guardian-service, remember to do this and that before the restore '', "if you are using AWS S3, remember to set parameter X to value Y before the step Z", etc.)

**Definition of done**
-----------------------------
The user is having a document that has scripts and/or tools plus instructions for running a backup/ restore process.

**Acceptance criteria**
------------------------------

1. The end result or deliverable of this RFP topic is a document(s) that must actually "work" as a tool and must be implementable.
2. Developing and providing the actual runnable code to back up, or providing the actual scripts which the DevOps team can cut & paste to backup/restore a Guardian installation, are acceptable answers.

**Comment by zulfalia32** [comment]
**Problem Description**
---------------------------
Clients (the implementer company) should be able to backup (both fully and incrementally) and recover their installation and data. Supporting partial recovery of the data is a desirable feature, but not mandatory.

**Requirements what needs to be done**
----------------------------
A policy related to backup tools, documentation, and methodologies for Hedera Guardian system will outline the  1) tools 2) documentation and 3) guidelines for ensuring the safety and security of critical data in case of system failures, disasters, or cyberattacks. 

- Tools are the software/scripts that the user would actually need to run to back up and restore a Guardian installation. 
- Documentation is the recipe the user follows to back up and restore  an instance of Guardian. 
- Guidelines are more general suggestions, to give hints in case of different architectures or special cases (ie. "if you are running a load balancer before the guardian-service, remember to do this and that before the restore '', "if you are using AWS S3, remember to set parameter X to value Y before the step Z", etc.)

**Definition of done**
----------------------------
The user is having a document that has scripts and/or tools plus instructions for running a backup/ restore process. 

**Acceptance criteria**
----------------------------

1. The end result or deliverable of this RFP topic is a document(s) that must actually "work" as a tool and must be implementable. 
2. Developing and providing the actual runnable code to back up, or providing the actual scripts which the DevOps team can  cut & paste to backup/restore a Guardian installation, are acceptable answers.
