### ISSUE TITLE
Missing docker images for Apple M1 & M2 since 2.9.0

### ISSUE THREAD

**Issue by samuraitruong** [hashgraph/guardian#1773]
### Problem description

It look like since 2.9.0 no longer support on ARM architectures. it maybe the variant of node:16 has change

### Step to reproduce
- Docker pull on Apple M1 or M2
- see below error
```
docker pull gcr.io/hedera-registry/api-gateway:2.9.2
2.9.2: Pulling from hedera-registry/api-gateway
no matching manifest for linux/arm64/v8 in the manifest list entries
```
### Expected behavior
We should lock the base docker image into the node 16 LTS.
Note that on same machine. 2.8.0 works

**Comment by prernaadev01** [comment]
We have updated an example for docker configuration for M1 in our documentation.
