### ISSUE TITLE
Guardian Time-Zone Fix/Workaround

### ISSUE THREAD

**Issue by blockchain-biopharma** [hashgraph/guardian#179]
**Requirements**
As a Guardian OS Software User, I would like the time zone to work for the time zone that I'm in. As per @Pyatakov this may be an issue with Docker. Team to investigate. This relates to Issue#31 the Community posted.

**Pre-requisite**
Docker Setup on Local Machine

**Definition of Done**
Community and stakeholder teams able to configure for their time zone.

**Acceptance Criteria:**
Community and stakeholder teams able to configure for their time zone.

**Comment by prernaadev01** [comment]
@Pyatakov @simvalery @anvabr @blockchain-biopharma Need to discuss in detail regarding this ticket.
