### ISSUE TITLE
Tutorial Script

### ISSUE THREAD

**Issue by envisionblockchainpm** [hashgraph/guardian#188]
**Requirements**
High-Priority Community User of The Guardian, I want to see the Script of my Tutorial

**Pre-requisite**
- Tutorial Discovery Meeting

**Definition of Done**
- Tutorial Output File

**Acceptance Criteria:**
- Tutorial Output File

**Comment by envisionblockchainpm** [comment]
There is a dependency on the gentleman commenting the code.

**Comment by envisionblockchainpm** [comment]
Stepan is done commenting the code but it needs to be translated. @anvabr

**Comment by anvabr** [comment]
Need the location of the artefact which contains the commented code please @danielnorkin @Stepan-Kirjakov

**Comment by envisionblockchainpm** [comment]
This was completed by Andrey, we need to figure out how to commit this.

**Comment by envisionblockchainpm** [comment]
This has been completed. The script is done and it's in the MD file.  Closing.
