### ISSUE TITLE
Drop down menu is not displayed in Safari

### ISSUE THREAD

**Issue by anvabr** [hashgraph/guardian#1880]
### Problem description
When using v2.10.0 Guaridan on Mac OS and Safari the items in the drop down menu are not displayed as per the screenshot:

![image](https://user-images.githubusercontent.com/32775532/223379412-d7afa083-2a19-4f84-8b88-20a51cff4d49.png)

### Step to reproduce
See the screenshot above

### Expected behavior
It should look equivalent to how it looks in Chrome.

### Screenshots
See above

**Comment by artembuslaev** [comment]
[https://github.com/hashgraph/guardian/commit/d55b0b38d6fe3ae5186efe5f0df44d9a17251c5d](fix displaying sub menu for safari)
