### ISSUE TITLE
Tutorial Voiceover

### ISSUE THREAD

**Issue by envisionblockchainpm** [hashgraph/guardian#189]
**Requirements**
High-Priority Community User, I want to hear a Tutorial on using the Guardian via a Voiceover

**Pre-requisite**
- Discovery Meeting

**Definition of Done**
- Voiceover Output File

**Acceptance Criteria:**
- Voiceover Output File

**Comment by envisionblockchainpm** [comment]
We decided not to do the Video Guide and make it all text based, therefore voice is not needed, closing the ticket.

**Comment by prernaadev01** [comment]
Duplicate of #182
