### ISSUE TITLE
Dependencies between policy and guardian service cause guardian service hanging

### ISSUE THREAD

**Issue by samuraitruong** [hashgraph/guardian#1892]
### Problem description
When guardian service startup it will initialise the policy to policy service. If anything happy to guardian service (memory, cpu, manual restart, error....) causes this service restart  it will stuck at the startup forever.

### Step to reproduce
1.  Start the full guardin stack
2. Wait until system up and running
3. Restart guardian service
4. Guardian service will be hang
5. Restart policy service
6. Restart guardian service again -> this time it will working because policy service has the fresh state

### Expected behavior
When process the policy, policy service maybe remove or check if the same policy already register to remove the dependencies between these 2 services so they can restart/self recovery themself

**Comment by samuraitruong** [comment]
also what if policy service crash and restart, will that get sync again?

**Comment by prernaadev01** [comment]
@samuraitruong Thank you for raising the ticket. 
We have discussed this internally and would like to know that all the actions performed are recorded in DB. Once there is service crash, the following actions are not recorded. Hence, when there is a restart, the last action, which was recorded in DB will be synced.
