### ISSUE TITLE
2.10 - get-block-data timeout

### ISSUE THREAD

**Issue by samuraitruong** [hashgraph/guardian#1893]
### Problem description
We successfully upgrade our guardian services to 2.10, dMRV submission and token mintting working in background, but we cant not viewing any VP/VC table.  

On our system, it cause by the timeout when api-gateway sending request to guardian service to get block-data

![image](https://user-images.githubusercontent.com/1183138/224224177-5d9f9dfd-8d91-4336-b603-c1343bf05bfd.png)
![image](https://user-images.githubusercontent.com/1183138/224224397-b457190c-a017-4fb3-bb94-d6bd98700b2a.png)

with above chunk of code, the event name will be prefix with `name`

However, the response api does not have any prefix (I can only see 1 place  in the code response for this event name)

![image](https://user-images.githubusercontent.com/1183138/224224530-231cd990-083d-404f-9ade-13a3941a9fca.png)

**Comment by samuraitruong** [comment]
@prernaadev01 was you reproduce this, I think some of my local environment it works with 2.10, I still troubleshoot if that cause by our production setup only or actual the bug code.

**Comment by samuraitruong** [comment]
@prernaadev01 I think it not an issue. Happy to close the issue. We have the system works e2e above error still happening  but not affect anything

**Comment by prernaadev01** [comment]
@samuraitruong Thank you for the confirmation.
