### ISSUE TITLE
Glossary Writeup

### ISSUE THREAD

**Issue by envisionblockchainpm** [hashgraph/guardian#190]
**Requirements**

As a Guardian Admin, I want to delivery a glossary to my users so that they can Read a Glossary.

**Pre-requisite**
- Discovery Meeting

**Definition of Done**
- .MDD File with Glossary

**Acceptance Criteria:**
- .MDD File with Glossary

**Comment by envisionblockchainpm** [comment]
This is a Duplicate. We are now combining the coded version and the UI version into one User Guide.

**Comment by prernaadev01** [comment]
Duplicate of #181
