### ISSUE TITLE
TokenIds are in UUID format

### ISSUE THREAD

**Issue by paul-burtjr** [hashgraph/guardian#1913]
### Problem description
Using a local instance of the Guardian version 2.10.0, we are seeing that importing a policy that has a token created is posting that token information to IPFS for that policy and the tokenId is a UUID even after it is published.

### Step to reproduce
1. Go to the Guardian and import a policy that has an initialization token created when it is imported
2. Publish the policy
3. Go to the Standard Registry user topic in https://explore.lworks.io/
4. View the Payload tab and look at the token information in the ESG API payload 
5. Alternatively use the cid in the policy field to query ipfs and get the token information which has the UUID format for the tokenId.

Example cid link from the screenshot for data retrieved for the token from ipfs: https://ipfs.io/ipfs/bafkreiatcjjwz5hxoj23b5ren6bkftwwtfly7ja53yuyr27fpdk5krleda

### Expected behavior
The tokenId property should have the Hedera tokenId value.

### Screenshots
<img width="1409" alt="image" src="https://user-images.githubusercontent.com/106628341/226062327-1ce67cc7-786b-4efc-a74b-e903f2ed2d42.png">

**Comment by anvabr** [comment]
As of #1653 importing policy no longer triggers the creation of tokens immediately. However they do need an ID so they can be referred to in the policy - this is the UUID you are seeing.  Once these tokens have been created the UUID should have been replaced with the token ID - it seems that this is not happening on your system?

@paul-burtjr Please can you attach the policy document (that you have imported) and the logs from your system capturing the error so we can try to reproduce it.

**Comment by paul-burtjr** [comment]
@anvabr I was able to reproduce the issue this morning importing iRec7 with timestamp: 1674822624.800179003

Standard Registry topic Id: 0.0.3880270 has a payload that with IPFS cid: bafkreih3kgidbsdvsxymifaekzyzd3zdikeyi2if2isj2q3ezbphg2kuhm, which returns token data with a tokenId that is a UUID.

There is no error in the guardian system. The error is that the token information does not have a tokenId.

**Comment by anvabr** [comment]
@paul-burtjr as I said above tokenID will be UUID after import - this is correct behaviour. Can you please:send me the link to the published policy which has the UUIDs instead of tokenIDs?

**Comment by paul-burtjr** [comment]
@anvabr 
Published Policy: https://explore.lworks.io/testnet/topics/0.0.3880272
[guardianLogs.zip](https://github.com/hashgraph/guardian/files/11020385/guardianLogs.zip)

**Comment by paul-burtjr** [comment]
@anvabr we are expecting the tokenId retrieved from IPFS to be the Hedera tokenId after the policy is published.
