### ISSUE TITLE
Verra policy (e.g. REDD) -based demo

### ISSUE THREAD

**Issue by anvabr** [hashgraph/guardian#192]
### Problem description

Create another demo/sample policy set and the corresponding demo script so to demonstrate Guardian capabilities and validate that the current functionality scope is sufficient to support a variety of problem domains.

### Task lists

- Analyse the set of Verra methodology and select a set of policies most suitable for creating an impactful product demo
- Create a exhaustive set of the information/fields that need to be written in the policy/spec 
- Create functional requirements specification for new schemas, new capabilities in the product etc.
- Implementation of the functionality
- Creation of the demo script

**Comment by dubgeis** [comment]
I have updated this timeline as this is not accurate currently. It is not clear to me the exact timeline, but this needs to be done by the 14th in my opinion with a deliverable OS policy artifact and how to guide documentation. @anvabr Can we please make this more accurate? cc @sergmetelin

**Comment by dubgeis** [comment]
We need a populated backlog to show and properly estimate next steps here. The previous end date was 12/30.

**Comment by dubgeis** [comment]
cc @envisionblockchainpm

**Comment by dubgeis** [comment]
@envisionblockchainpm Can you please assign the tasks to sprints in GitHub? cc: @sergmetelin @justin-atwell @anvabr

**Comment by envisionblockchainpm** [comment]
@justin-atwell @sergmetelin @dubgeis The User-stories / Issues in this Epic which are NOT assigned to Sprint 4 have now been added to Sprint 5, although there has been an increase in scope as of today, so naturally dates may change on the Schedule, including the overall Delivery Date for this Epic.
