### ISSUE TITLE
Geographic raster imagery support in Guardian

### ISSUE THREAD

**Issue by anvabr** [hashgraph/guardian#1930]
### Problem description
As of #1563 implementation of geo-spatial data type it is now possible to introduce getJSON data objects in the VCs/VPs and scemas in the Guardian. However much of historic geographic data, specifically satellite imagery, is stored in geoTIFF format. Also see https://www.sentinel-hub.com data and API for such archives. Such data also needs to be natively supported by Guardian.

### Requirements
Introduce support for geoTIFF and other raster types of data such that:

- Guardian documents (i.e. in schemas) can reference raster data (in geoTIFF and other common formats) which are located on external (3rd party) systems.
- Guardian UI can display raster images and their georeferencing data when they are encountered in documents.
- Guardian policy can access and manipulate (use in calculations, etc) data from raster sources.

### Definition of done
- Introduced support for raster data into Guardian policies and documents
- Documentation updated accordingly
- At a minimum a single example of using raster data is introduced into Guardian sample policies 

### Acceptance criteria
- Guardian can work out of the box with raster data from **one** of the following sources:
  - https://www.sentinel-hub.com
  - https://qgis.org/en/site
  - https://www.arcgis.com/index.html
- Guardian supports at a minimum geoTIFF and other common image formats (jpeg, png, etc)
- Subsets of data from the raster image can be extracted into a variable (of a suitable type), and then further used in the policy calculations via custom logic block

#### Raster description

Rasters may be stored in any number of formats or containers.  They are typically stored in a binary format for the sake of efficiency, but plaintext formats are not uncommon.

Georeferencing information for raster images is embedded either directly in the header of the container file, or via ancillary files that are distributed with the raster. A world file is a common example of the latter approach, where a separate plaintext file describes the position in geographic space of the center of the upper-left pixel, as well as the x and y resolution of the raster. 

#### External references
- [Docs page](https://docs.qgis.org/2.18/en/docs/gentle_gis_introduction/raster_data.html#raster-data) offering good explanation of what raster data is.
- ['Official' list](https://gdal.org/drivers/raster/index.html) of (154) raster image formats
- Raster data model [description](https://gistbok.ucgis.org/bok-topics/raster-data-model)

**Comment by dubgeis** [comment]
@agryo-company please review

**Comment by agryo-company** [comment]
We will write down a small proposal of some of the important points that can support the guardian ecosystem.

**Comment by nextalias** [comment]
Typo; should be "geoTIFF"

ECW, and JPEG 2000 also popular compressed format.

Also ERDAS Imagine (IMG) is popular for multispectral data sets.
