### ISSUE TITLE
Issue while setup, after new release: unable to Finish Setup

### ISSUE THREAD

**Issue by anil8797** [hashgraph/guardian#1971]
Input sample 
    'attributes' : {
    	'ISIC': '051 062',
    	'geography' : 'USA CAN EU AUS',
    	'law': 'USA',
    	'tags': 'VERRA iREC'
  }

### Problem description
Error: credential is not valid JSON-LD: {
  "type": "MISSING_PROPERTIES_IN_CONTEXT",
  "details": [
    "credentialSubject.ISIC",
    "credentialSubject.geography",
    "credentialSubject.law",
    "credentialSubject.tags"
  ]
}
    at /usr/local/guardian-service/node_modules/@transmute/vc.js/dist/vc.js.cjs.production.min.js:1:5926
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)### Expected behavior

### Screenshots
![image](https://user-images.githubusercontent.com/121919823/229428745-a9e9c7f1-d49d-4c34-927c-d6a0677b1763.png)

**Comment by prernaadev01** [comment]
@anil8797 Thank you so much for raising the ticket.
We tried reproducing this but everything works fine at our end.
We would request you to send video with opened network, and opening preview of failed requests if possible. 
Thanks.
