### ISSUE TITLE
Improve message broker function by adopting nestjs

### ISSUE THREAD

**Issue by anvabr** [hashgraph/guardian#1975]
### Problem description
Currently Guardian system works directly with NATS message broker. This is not ideal as it requires implementation of message handling logic which already exists in other scalable broker management frameworks including [nestjs](https://docs.nestjs.com/microservices/nats). 

### Requirements
Introduce [nest.js ](https://docs.nestjs.com/microservices/nats) framework into Guardian architecture to achieve better scalability, stability and improve code reuse. This should also enable a switch to another message broker in the future should we need to.

### Definition of done

- Guardian architecture relies on [nest.js](https://docs.nestjs.com/microservices/nats) for messaging.
- No clients customisations are affected by the above.

### Acceptance criteria

- See DOD above

**Comment by samuraitruong** [comment]
NestJS is  great, we using NestJS for everything at Tymlez (includes microservice architecture)
