### ISSUE TITLE
Internal API Tests Written

### ISSUE THREAD

**Issue by envisionblockchainpm** [hashgraph/guardian#199]
**Requirements**
As a Guardian OS Architect or Software Developer / System Integrator, I would like to have a perfected, streamlined, functional, tested, and documented API.

**Pre-requisite**
- Internal Discovery Sessions
- All Dev Tasks
- All API Testing Complete

**Definition of Done**
- Testing and Development Are Approved by Stakeholders.

**Acceptance Criteria:**
- Unit Test Results

**Comment by envisionblockchainpm** [comment]
PM will check with Hedera Team to see what type of testing is expected , who will do UAT, etc.

**Comment by envisionblockchainpm** [comment]
As per @anvabr we will be doing API Tests. Moving to Sprint 6?

**Comment by envisionblockchainpm** [comment]
Next Step is to Produce the API Testing Tasks as per @Pyatakov

**Comment by envisionblockchainpm** [comment]
As per Alex this is in Progress. No Blockers.

**Comment by envisionblockchainpm** [comment]
We should be able to finish this tomorrow as per Alex.

**Comment by simvalery** [comment]
https://github.com/hashgraph/guardian/pull/388

**Comment by envisionblockchainpm** [comment]
This ticket is done as we were able to Demo the Testing Plan as of today.
