### ISSUE TITLE
Supply Chain and Macro Dynamics

### ISSUE THREAD

**Issue by prernaadev01** [hashgraph/guardian#2012]
### Problem description
Guardian instances and the corresponding policies and GHG inventories of various supply chain actors should eventually be able communicate, interact, and influence each other in a dynamic ecosystem of GHG inventories and decentralized MRV data. As materials, products, emissions, and offsets cascade down supply chains, the various implications for multiple scopes, reporting entities, standards, etc. need to be mapped out. 
To add complexity, GHG emissions, supply chains, and corporate structures are dynamic and continuously change for example, as logistics routes are optimized, suppliers and partners change, and corporate structures undergo mergers, acquisitions, and divestments. As GHG data and calculations become increasingly automated and performed in real-time, as the emissions themselves fluctuate dynamically, the corresponding GHG inventories of supply chain partners may need to be updated similarly. This will require Guardian instances to communicate, share data, and interact dynamically. 
Transparent and decentralized MRV and GHG accounting will enable better communication and alignment of emissions data between various supply chain actors and address these prevalent issues. However, to support a well-functioning GHG data ecosystem, the rules and dynamics of how GHG data and inventories are managed throughout the supply chain and across scopes must be clearly mapped out. Further, the Guardian must ultimately possess the necessary features to facilitate these dynamics.

### Requirements
Investigate and determine the rules that will govern supply chain and macro dynamics of a decentralized GHG data ecosystem. Key questions include but are not limited to: 

- How will the use of offsets and RECs influence upstream and downstream emissions? 

- How will the emissions of material inputs and intermediate products impact the emissions of final products?

- How will the emissions of final products impact scope 3 emissions of downstream customers?

- How can supply chain actors better coordinate data, approaches, and methodologies of emissions that are from the same source, but different scopes and categories throughout supply chains and product life cycles?  

- How can emissions be properly categorized, calculated, and allocated in a way that avoids double and under counting? 

- As emissions are measured and calculated in real-time, how can corresponding inventories be updated? 

- How can inventories be updated to reflect dynamic changes to supply chains and corporate structures? 

Identify and implement new Guardian features that facilitate the necessary supply chain and macro-dynamics. 

### Definition of done
Rules governing supply chain and macro-dynamics are mapped out and captured in writing. Necessary Guardian features are developed. 

### Acceptance criteria
It is determined that the Guardian possesses the necessary features to manage supply chain and macro-dynamics.

**Comment by Mpinnola** [comment]
The questions/issues above have been researched, brainstormed, and discussed in detail. The results are summarized in the PPTs attached. The research have also resulted in the identification of a number of new functionality requirements, for which new tickets are being drafted. Once drafted, these tickets will be referenced below.
