### ISSUE TITLE
use new env var to enable database name convention

### ISSUE THREAD

**Issue by samuraitruong** [hashgraph/guardian#2099]
### Problem description

I think it is better to introduce the new specific env var to control the DB name rather than checking the other dependencies 

<img width="1035" alt="image" src="https://user-images.githubusercontent.com/1183138/236729632-9f19a66a-8969-49df-8a0e-b6f4a36003ad.png">

### Step to reproduce
1. migrate existing system from 2.10 to 2.12 
2. Login with any pre-exist account
3. got 500 error

### Expected behavior
- Document update to specific which require to configure for the new changes

**Comment by anvabr** [comment]
As discussed in Slack, There is no need for migration, for DB name the following expression is used:
```
dbName: (process.env.GUARDIAN_ENV||(process.env.HEDERA_NET!==process.env.PREUSED_HEDERA_NET))?
            `${process.env.GUARDIAN_ENV}_${process.env.HEDERA_NET}_${process.env.DB_DATABASE}`:
            process.env.DB_DATABASE
```
Which means you’d need to make sure that in the evn variables of the service `GUARDIAN_ENV` is absent and that  `PREUSED_HEDERA_NET` does not equal `HEDERA_NET (PREUSED_HEDERA_NET=“”` would be enough) and then the name of the DB will equal  `DB_DATABASE`
