### ISSUE TITLE
Non-approved policy application shows spinning wheel on repeat

### ISSUE THREAD

**Issue by sergmetelin** [hashgraph/guardian#21]
As an installer, when I open a policy that hasn't been approved yet, I get a spinning wheel with no indication of what is happening. The spinning wheel doesn't go away. (v1.0.0-beta.2)

![Screen Shot 2021-10-20 at 4 51 40 PM](https://user-images.githubusercontent.com/2141500/138170609-6aea56e3-3244-487a-a96f-0d1b9df4fb74.png)

Expected behavior: a message saying "Waiting for approval" needs to be shown. This message needs to be dictated by the policy template.

**Comment by envisionblockchainpm** [comment]
This has been tested by @Pyatakov  and @Stepan-Kirjakov and is merged into the development branch.
