### ISSUE TITLE
Increase the `max_chunks` limit to support large messages. 

### ISSUE THREAD

**Issue by dlin-me** [hashgraph/guardian#2110]
### Problem description

Topic messages are limited to 20 chunks maximum by default. Each chunk is limited to 1024b (limited by HCS message size). We need a way to increase the `max_chunks` limit to support large messages.

Our system records MRVs with small values. Then, those MRVs aggregate to mint tokens.
In some of our use cases, It hit the limit of 20 chunks per message when more than 1000 MRVs aggregated to mint one token.. 

The default 20 chunks limit is set by default at:
https://vscode.dev/github/hashgraph/hedera-sdk-js/blob/develop/src/topic/TopicMessageSubmitTransaction.js#L84

But this can be set by the [`setMaxChunks`](https://vscode.dev/github/hashgraph/hedera-sdk-js/blob/develop/src/topic/TopicMessageSubmitTransaction.js#L210) method.

### Step to reproduce
 
Our system records MRVs with small values. Then, those MRVs aggregate to mint tokens.
In some of our use cases, it takes over 1000 MRVs aggregated to mint one token. When this happened, we came across the following error:

```
{
...
severity: "ERROR"
textPayload: "2023-05-08T06:37:49.705Z [guardian-service,5e07e18b-6cab-4280-8db7-871c3691b4b2,mintDocumentBlock,block-runtime,63dc7cbd6105ab8065a4b34c]: Message with size 21306 too long for 20 chunks NR-LINKING|MzQ5NzYzMXxBUE18QVBQTElDQVRJT058MTQxMDQ2NTM0Mg|guardian-guardian-service-5ffcfddcfc-c688s|||guardian-guardian-service|"
timestamp: "2023-05-08T06:37:49.706283529Z"
}
```

It hit the limit of 20 chunks per message. 

### Expected behavior

We need a way ( maybe an environment variable) to increase this limit to support large token mint messages.

**Comment by samuraitruong** [comment]
we can use the setMaxChunks function to fix this issue.  I have tested this approach and it can mint token with > 1000 dmrv
```

@timeout(HederaSDKHelper.MAX_TIMEOUT)
    public async submitMessage(
        topicId: string | TopicId,
        message: string,
        privateKey?: string | PrivateKey,
        transactionMemo?: string
    ): Promise<string> {
        const client = this.client;

        let messageTransaction: Transaction = new TopicMessageSubmitTransaction({
            topicId,
            message,
        }).setMaxTransactionFee(MAX_FEE)
        .setMaxChunks(50)


       ......
    }

```

**Comment by prernaadev01** [comment]
@samuraitruong Thank you for the suggestion. We have fixed this issue by adding the maxChunks parameter to .env of worker-service.
