### ISSUE TITLE
FastMQ needs TLS component and/or authentication method

### ISSUE THREAD

**Issue by anvabr** [hashgraph/guardian#215]
### Problem

FastMQ as it is currently in use has no TLS component to it or authentication method.

In situations where data needs to be sent from outside the VPC this represents a security deficiency that needs to be addressed.

### Solution

Implement TLS and/or authentication for FastMQ

**Comment by anvabr** [comment]
Originally from @voycey

**Comment by voycey** [comment]
FastMQ does not support TLS - as this is a primary component of the MRV area of the guardian it is going to need to be replaced or proxied with TLS as this needs to be public facing. Likely better to replace FastMQ with something else.
Creating a plugin adapter system for the queue component is better as its highly likely any integrations will be based around SQS or PubSub / Whatever Azures version is - we wouldn't introduce a new queue system to our infrastructure.

**Comment by prernaadev01** [comment]
@simvalery @anvabr @Pyatakov  Dan Voyce noticed that FastMQ too not being able to handle payloads > 64kb (which is easily hit with the number of VCs we have in our VPs). They are looking at implementing bull-queue and Redis.

**Comment by prernaadev01** [comment]
I am cancelling this ticket as our implementation plan is changed.
