### ISSUE TITLE
Replace all references to 'localhost' with container names

### ISSUE THREAD

**Issue by anvabr** [hashgraph/guardian#217]
### Description

Currently in many places Guardian deployment automation contains  the combination 'localhost' and 'port' which is not suitable for production/cloud deployment.

### Steps to reproduce

As part of our steps to move the Guardian into production we need to remove all references of localhost and instead point these to the container names.

Services like Fargate and GKE do not easily support localhost + port as a naming convention but instead rely on container names to communicate.

This should be a simple change but I wanted to discuss based on planned deployment targets for the wider community and any gotchas that might exist there.

### Hedera network

other

### Version

v1.0.0

**Comment by envisionblockchainpm** [comment]
@anvabr as a next step will need to look into this and evaluate it to make sure its clear from the engineering perspective. Andrey will reach out to the person in the community who posted this and communicate timeline / fix date.
