### ISSUE TITLE
I cannot build the guardian-cli

### ISSUE THREAD

**Issue by Neurone** [hashgraph/guardian#2185]
Following the instruction in the doc (https://docs.hedera.com/guardian/guardian/readme/built-with/guardian-cli#local-setup) I'm not able to build the guardian-cli. I also tried to install the deps, with `npm i` but that was not the solution.

I'm using `main` branch, that is currently tagged `2.12.2`

Here the output:

```sh
❯ git clone git@github.com:hashgraph/guardian.git
❯ cd guardian/guardian-cli
❯ npm run build

> guardian-cli@0.1.0 build
> tsc

sh: tsc: command not found
❯ npm i

added 3 packages, and audited 4 packages in 1s

found 0 vulnerabilities
❯ npm run build

> guardian-cli@0.1.0 build
> tsc

error TS18003: No inputs were found in config file '/Users/giuseppebertone/workspace/hedera/guardian/guardian-cli/tsconfig.json'. Specified 'include' paths were '["src/**/*","../interfaces/src/type/TopicType.ts"]' and 'exclude' paths were '["node_modules"]'.

Found 1 error.

**Comment by felipeneuhauss** [comment]
@Neurone problem solved: [fix here](https://github.com/hashgraph/guardian/pull/2510/files)
