### ISSUE TITLE
Block and policy discoverability/search

### ISSUE THREAD

**Issue by anvabr** [hashgraph/guardian#2281]
### Problem description
At present authors of Guardian policies have a number of tools they can use to assist with policy creation to avoid creating a policy 'from scratch'

- wizards
- policy blocks suggestions in the editor
- pre-built policy modules
- use sample policies available out-of-the box as a template and change/extend as required

However there is frequently a need to add elements to the policy to address specific use-cases. When such a need arises it would help policy authors to be able to quickly look-up other existing policies which use this element[s] and thus have examples or copy/paste sources.

### Requirements

- Introduce a capability into Guardian where a user can search, directly from the editor, examples of the usage of specific blocks
- The search scope should be inside a Guardian instance and, additionally, further through all published policies (to be implemented in #2629)
- There should be additional filters in the UI that would allow users to restrict the scope of the search based on:
   - date range
   - SR (list)
   - Presence/absence of tags and their scoring (e.g. 'minimum 50 thumbs-up tags')
   - name 

We will also be enhancing this functionality from single instance to global search. More information can be found in [#2629](https://github.com/hashgraph/guardian/issues/2629)

### Definition of done

- Functionality is implemented in the Guardian UI (no corresponding API is required)
- Documentation updated accordingly

### Acceptance criteria
Policy authors are able to quickly look-up the examples of usage for tags as per requirements above

**Comment by dubgeis** [comment]
@anvabr can you please share more on discoverability across guardian instances here?

**Comment by dubgeis** [comment]
@nodlRob ^ for awareness

**Comment by dubgeis** [comment]
@anvabr it would be great if we could use this across multiple instances of Guardian as as part of the definition of done and have it update our methodology library with listed undocumented policies for analytics. cc: @danielnorkin

**Comment by anvabr** [comment]
> use this across multiple instances of Guardian 

This is in scope, i.e. it specifies "and, additionally, further through all published policies"
