### ISSUE TITLE
HttpRequestBlock doesn't work 

### ISSUE THREAD

**Issue by JoeyZhaojin** [hashgraph/guardian#2282]
### Problem description
when I try to use Http Request block. I set a simple policy to access an API that returns a joke in JSON, it dry-runs successfully, but when I click "Go", it's stuck, without any return on Network, but shows: 
500 
Other Error
Http failure response for /api/v1/accounts/session: 0xUnknown Error
![7adf35950894906a85e7b7ec6ddcb2d](https://github.com/hashgraph/guardian/assets/105480577/39c79905-5f2f-4b29-bff9-81f1e3685417)

And my policy is to access an API, show page 1 if successful, and show page 2 if not successful.

![3c988690e724d3d3158758912a52e4f](https://github.com/hashgraph/guardian/assets/105480577/81303123-a4f2-4cdd-bf78-df7cba4ee762)

As for the parameters of Http Request block, I didn't set the body and header, because the joke API seems don't need any of them, and from the Network page of Browser F12, I also don't see any return of the joke API. In addition, as seen from the Guardian log, the Http Request block didn't run.

### Expected behavior
HttpRequestBlock can retrieve data

**Comment by JoeyZhaojin** [comment]
Hi @anvabr , thank you for your response. Sorry for any misleading, but this error actually happened in a dry-run mode, the sentence ' it dry-runs successfully' just means that my policy passes the primary logic check and can load the dry-run mode.

As for the return of that joke API, it just returns a simple json file such as below:

> {
>     "categories": [],
>     "created_at": "2020-01-05 13:42:27.496799",
>     "icon_url": "https://assets.chucknorris.host/img/avatar/chuck-norris.png",
>     "id": "LEsNukieSTarF7QOEA_pQw",
>     "updated_at": "2020-01-05 13:42:27.496799",
>     "url": "https://api.chucknorris.io/jokes/LEsNukieSTarF7QOEA_pQw",
>     "value": "Chuck Norris once took his pants off in a Thanksgiving Day parade. All the horses wept. Male and female."
> }

And I'm a little confused, do you mean I need to create a schema in advance to fit the API's return? Or do I need to choose the suitable API which returns a **valid well formed** VC document, and then fetch data from the VC document for later use (display or calculate)?

**Comment by anvabr** [comment]
Hi @JoeyZhaojin, you are getting the error because your document is not a well-formed VC - it won't pass verification. We will update Guardian to make sure the error reporting is more informative, but the actual issue is that this block expects a well-formed VC and your 'joke' document sent back is not one. Here is an example of a well-formed VC that would work.

```
{
  "id": "urn:uuid:817f5e43-58c0-4713-9d50-e065679e3a01",
  "type": [
    "VerifiableCredential"
  ],
  "issuer": "did:hedera:testnet:4v2g4nA8YLDkD1cV2jLV4wVqWSh3g44ttRKkNoPcwK6A_0.0.15013028",
  "issuanceDate": "2023-07-10T17:15:15.762Z",
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "ipfs://bafkreidrejuaah4o6ydsrxu6qdktszn676vlaxcr2gvyrz5w4o6awo6ha4"
  ],
  "credentialSubject": [
    {
      "categories": [],
      "created_at": "2001-01-01",
      "icon_url": "https://assets.chucknorris.host/img/avatar/chuck-norris.png",
      "updated_at": "2001-01-01",
      "url": "https://assets.chucknorris.host/img/avatar/chuck-norris.png",
      "value": "asdasdasdasdasdasdasdasdads",
      "policyId": "64ac0b6e6d13ea3f7cc0935c",
      "@context": [
        "ipfs://bafkreidrejuaah4o6ydsrxu6qdktszn676vlaxcr2gvyrz5w4o6awo6ha4"
      ],
      "type": "20b10537-72da-4ee6-b357-5aabfe64c56b&1.0.0"
    }
  ],
  "proof": {
    "type": "Ed25519Signature2018",
    "created": "2023-07-10T17:15:15Z",
    "verificationMethod": "did:hedera:testnet:4v2g4nA8YLDkD1cV2jLV4wVqWSh3g44ttRKkNoPcwK6A_0.0.15013028#did-root-key",
    "proofPurpose": "assertionMethod",
    "jws": "eyJhbGciOiJFZERTQSIsImI2NCI6ZmFsc2UsImNyaXQiOlsiYjY0Il19..aLJdmBw5pCaLsn7epED5BJNtN7w3hdNzQRfJflUjzgVrkIr--UzZ1AcEoDJTv9mk2sjEfAqy3Dp94mbS3DSXDQ"
  }
}
```
To answer your question about the schema, note that the VC above contains a reference to the schema

```
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "ipfs://bafkreidrejuaah4o6ydsrxu6qdktszn676vlaxcr2gvyrz5w4o6awo6ha4"
  ],
```
