### ISSUE TITLE
3rd Party Content Providers

### ISSUE THREAD

**Issue by blockchain-biopharma** [hashgraph/guardian#229]
### Problem description
Currently in the process of 'executing' a policy Guardian can receive and make use of two types of external data:

- MRVs from sensors (automatically) or inputted via the form by a human.
- Information submitted (by humans) via form data, e.g. when registering a project.

There are many use-cases when additional external data may need to be associated with MRV data sets, artefacts of policy execution, and/or tokens. Furthermore, this information may need to be used in the policy decision making process, determining for example:

- which branch (in the switch statement) should policy workflow execute
- what type of token to mint and the amounts
- whether to automatically authorise/approve something
- presented to the user who validates data or approves decisions
- accessible for review at any time after the decision/processing was performed  

Note that this information may have temporal shift wrt policy execution timeline, i.e. it cannot be assumed that it would arrive in the real time as needed. Also in some cases the information arriving into Guardian could have been passed through multiple processing/validations stages (e.g. MRV data validated by an AI model to be 'sensible' before being passed to Guardian).

### Requirements
- Guardian Policy Engine (PE) is required to support new blocks which would enable the functionality to use receive and use external data as described above.
- Guardian API is to be extended to include facilities for 3rd party data feeds for both push and pull models:
     - receiving and storing such information until the time that it is needed
     - proactively querying for the information when it is needed
     - pausing the execution of the policy and waiting for the availability of such information, and resuming once it becomes available
- Guardian roles/actors and trust chain to support the existence of external entities which can validate or process raw data before its arrival to Guardian
- Support information at least in the following formats:
    - json data
    - text
    - images
    - video
    - binary blob

### Definition of done
- API for 3rd party data processing is available and functioning as described above
- Policy definition language is extended to support the new elements for 3rd party data
- Policy engine executes 3rd party data processing workflow as described above
- 3rd party pre-validation of MRV and other data is supported and is visible in trust chain
- Demo policies include demonstration of these capabilities
- This functionality is documented

### Acceptance criteria

- Requirements are addressed as specified
- At least one use-case is demonstrated

**Comment by voycey** [comment]
@samuraitruong we should discuss this with Envision as we are already doing manually added data as part of our work
