### ISSUE TITLE
Verra VM0044 Webinar

### ISSUE THREAD

**Issue by prernaadev01** [hashgraph/guardian#2309]
### Problem description
Verra’s VM0044: Methodology for Biochar Utilization in Soil and Non-Soil Applications, v1.0 measures the removal of carbon through the use of biochar resulting from improved waste handling and disposal practices. These practices involve converting waste biomass into biochar at new biochar production facilities. The greenhouse gas (GHG) benefits are only credited for biochar that is used in eligible soil and non-soil applications, such as crop- and grasslands, as well as emerging non-soil products like biochar-amended concrete and building materials. This methodology can be applied worldwide and utilizes a standardized activity method to determine additional benefits. 

In this webinar we will go over the VM0044 methodology, policy creation, and have a demo of the Guardian. 

### Requirements
Design schemas for the VM0044 methodology, create a PowerPoint presentation, and conduct webinar. 

### Definition of done
Designing Schema
Development of Schema
Updating ReadMe and documentation

### Acceptance criteria
100% completion on design, development and documentation

**Comment by dubgeis** [comment]
@carbontarzan ^
