### ISSUE TITLE
1,000+ Max NFTs Hedera limitation Workaround 

### ISSUE THREAD

**Issue by envisionblockchainpm** [hashgraph/guardian#231]
### Problem description 
In each account, there is a Limit of 1,000 NFT's. We need to account for this limitation, being that one Private Key can be hosted by multiple Treasury Accounts. We need to be able to transfer and retire up to 10 Million Recs at a time. We need a UX for the user to not feel the pain of network memory constraints, this is a workaround over the limitations of Hedera tech.

It would enable the netting and burning of tokens at scale. At present for one account you can burn less than 1,000 tokens on less than 1,000 emissions. Development wise, we need this process to handle the netting and burning of Tokens.

### Requirements

- A single user account in Guardian should seamlessly map to (and manage) multiple Hedera accounts that belong to it.
- See Hedera HIP-XX (TBD) for the derivation of keys/accounts similar to [BIP-32](https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki). All accounts for a single user should be derived from its main account.
- The creation of a new (additional) Hedera account, and the allocation/withdrawal of tokens into/from that account should happen automatically. I.e. when an account gets full but more tokens are sent/given to the user a new account is allocated for the guardian user a new Hedera account is created automatically and the tokens are sent to it.

### DOD
- Acceptance criteria fulfilled
- Documentation updated to reflect the change
- Demo script updated to demonstrate the capability

### Acceptance Criteria

- Single user ownership of 10M+ NFTs
- Demonstrable ability to seamlessly transfer 10 Million Tokens, or fractions of these tokens, for a single user wallet without the need to manage multiple wallets/accounts etc.

**Comment by anvabr** [comment]
I have update the description of the ticket sufficiently, removing myself from the ownership now.

**Comment by anvabr** [comment]
Hedera token service allows issuance of a uint64 (2^64) of individual NFTs of the same type serial numbers) of tokens, each is an individual NFT with its own metadata
