### ISSUE TITLE
HIP: Scalable Token Transfer

### ISSUE THREAD

**Issue by envisionblockchainpm** [hashgraph/guardian#232]
## Requirement
As a Guardian User, I want to transfer more than 1,000 non fungible tokens to another user. This proposal is to enable a standardized way to send and allow a user to accept these tokens.  HIP is the Documentation, which is the HOW the story gets done.

## Definition of Done
- Writing the HIP and Publishing it to the community.

**Comment by anvabr** [comment]
No longer required as per the statement from @sergmetelin
