### ISSUE TITLE
DEV Implementation of Workaround

### ISSUE THREAD

**Issue by envisionblockchainpm** [hashgraph/guardian#233]
## Requirement
The Limit is you can only have 1,000 Tokens, so how the development would work is you would divide the total number of tokens by the token limit (1,000), and then generate accounts so that each account has less than 1,000 Tokens when done. The user needs to click a button, and this is what would happen in the code. This is a UX Feature for Guardian accounts .

UX:
1. Have an account, the UX would expand with this to show how many accounts you have. 

DOD: Any NFT Wallet will benefit from this, however, this is a requirement for any carbon offset just due to the nature of the volume that's being traded. 

## Pre Requisite
- Discovery Session with Hedera Team

## Definition of Done
- Need @anvabr and @Pyatakov help to define this, this is TBD. @danielnorkin

**Comment by anvabr** [comment]
This is no longer required as per @sergmetelin .
