### ISSUE TITLE
Docker compose is failing on policy service buildstep

### ISSUE THREAD

**Issue by mattsmithies** [hashgraph/guardian#2430]
### Problem description

I have attempted to pull down and run the latest Guardian code, from main branch (last tag v2.14.2)

Attempts have been made on three different systems/OS:

- Digital Ocean (Ubuntu 20.04.2 LTS)
- OSX iMac (13.4.1 - Ventura)
- OSX iMac (12.x - Montgomery)

All systems have failed to run the docker build at **Step 11/11** is failing for _ERROR [policy-service policyservicebuilder 11/11] RUN yarn run build:prod_

See screenshot below.

### Step to reproduce

Following the documentation:

1. Configure `GUARDIAN_ENV="develop"` in .env
2. Add `OPERATOR_KEY`, `OPERATOR_ID`, and `IPFS_STORAGE_API_KEY` for web3.storage.
3. Run `docker compose up -d --build`

### Expected behavior

Docker compose builds and runs the service.

### Screenshots

I have listed two screenshots first from my local environment and second from my digital ocean droplet, both failing error messages are the same.

## From my local system

<img width="1247" alt="Screenshot 2023-07-19 at 16 36 21" src="https://github.com/hashgraph/guardian/assets/6974163/8edc38ee-a443-4e03-aa50-652fcfc65e10">

## From my digitalocean droplet

<img width="1640" alt="Screenshot 2023-07-19 at 16 39 24" src="https://github.com/hashgraph/guardian/assets/6974163/e128c7af-ce88-4eb1-bfd5-939cf5767d26">

**Comment by mattsmithies** [comment]
@prernaadev01 @anvabr flagging this for you both, as it breaking deployment of upgrading to the newest version of the guardian. 🕊

**Comment by prernaadev01** [comment]
@mattsmithies Thank you for raising ticket. We are checking it asap.
