### ISSUE TITLE
Inject Dummy Data

### ISSUE THREAD

**Issue by blockchain-biopharma** [hashgraph/guardian#253]
## Requirement
- Unsure of how to define this requirement. Need help from @anvabr 

## Pre Requisite
- Discovery Session with Hedera Team

## Definition of Done
- Need @anvabr and @Pyatakov help to define this, this is TBD. @danielnorkin

**Comment by prernaadev01** [comment]
This ticket is duplicate of [#1167](https://app.zenhub.com/workspaces/guardian-618c27c08661c0001461263a/issues/hashgraph/guardian/1167)
