### ISSUE TITLE
Ability to Pull In Data

### ISSUE THREAD

**Issue by blockchain-biopharma** [hashgraph/guardian#254]
## Requirement
- Unsure of how to define this requirement. Need help from @anvabr 

## Pre Requisite
- Discovery Session with Hedera Team

## Definition of Done
- Need @anvabr and @Pyatakov help to define this, this is TBD. @danielnorkin

**Comment by prernaadev01** [comment]
This is duplicate ticket of [#229](https://app.zenhub.com/workspaces/guardian-618c27c08661c0001461263a/issues/hashgraph/guardian/229)
