### ISSUE TITLE
Icon displays wrong for GeoJson type nested schemas

### ISSUE THREAD

**Issue by kirill-tolochko** [hashgraph/guardian#2545]
### Description of the problem

The icon is displayed incorrectly

### Steps to reproduce behavior:
1. Create policy, add nested schemas with type "GeoJson" and open the policy in the dry run mode
2. Click on the "Add entity" button

### Expected behavior
The icon is displayed correctly

### Actual behavior
The icon is displayed incorrectly.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdXdTIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--56e4ad8a5049940aab15249928de135ce0dc6dc2/image_2023_08_17T14_34_38_813Z.png)

**Comment by felipeneuhauss** [comment]
@kirill-tolochko Hi! Would you mind giving more e details or prints? I've followed the steps but where could I find the "Add entity" button?
