### ISSUE TITLE
Running out of funds when minting tokens - inconsistent state, no recovery path

### ISSUE THREAD

**Issue by anvabr** [hashgraph/guardian#2560]
### Problem description
It is easy to run out of account funds during a minting operation of Guardian policy as users cannot always know in advance how many tokens their account would be minting. When this happens at present the following problems occur:
- Guardian does not report the error clearly
- Guardian policy execution appears to be left in an inconsistent state
- Once the user is away of the problem, and mitigated it by replenishing the account, there is no clear 'restart' or 'recovery' path to take

### Step to reproduce
See description above

### Expected behavior

- Guardian checks if the user has enough fund to perform the required operation, and reports to the user if this is not the case
- Guardian policy execution 'pauses' at the point when it becomes clear there are insufficient funds
- In the case of the error of running out of funds there is a clear and simple way for the user to 'unpause' the execution once the account has been topped-up

### Screenshots
N/A

**Comment by Pyatakov** [comment]
Implemented in #2905
