### ISSUE TITLE
Message-broker on Docker Build - Cannot find name 'AbortSignal'. 

### ISSUE THREAD

**Issue by mattsmithies** [hashgraph/guardian#26]
**Describe the bug**
When using the installation documentation finishing with `docker-compose up -d --build` the message-queue module was hitting an **AbortSignal** issue whereby there was a clash with particular interface definitions.

**To Reproduce**
1. Follow the installations instructions for building with docker

**Expected behavior**
Docker completes installation and runs all services.

**Desktop (please complete the following information):**
- MacOS 10.15.7
- Node v16.7.0 (Using NVM)
- Docker version 20.10.5

**Additional context**
Will provide a PR to resolve the issue.

**Expected Solution**
Update tsconfig.json (message-broker) with skipLibCheck to bypass ts interface checks that have clashes. Once there is production-ready stability for the guardian there should be a view to remove this flag.

**Comment by envisionblockchainpm** [comment]
As per @Pyatakov We just need to merge this code. Adding to Sprint 2

**Comment by simvalery** [comment]
@mattsmithies can you create pull request to develop branch?

**Comment by anvabr** [comment]
This appears to have been done
