### ISSUE TITLE
Prepare Demo of REDD / APD Workflow

### ISSUE THREAD

**Issue by blockchain-biopharma** [hashgraph/guardian#263]
USER STORY: 
As a Root Authority User I want to be able to mint VCU Tokens based on the Verra / REDD APD Policy, this includes multiple roles such as project proponents, a Root Authority, and a VVB. 

DOD:
- New Schemas are created; project details, baseline scenario emissions, project scenario emissions, and a monitoring report. 
- New schema types are created; image
- Use the appropriate methodology to calculate the creation of VCU's
- Policy can be exported and imported into new instances

**Comment by envisionblockchainpm** [comment]
Needs story point estimate. This is work for Max and @anvabr . Adding to Sprint 5

**Comment by envisionblockchainpm** [comment]
Next step is on Andrey @anvabr to discuss with Max

**Comment by envisionblockchainpm** [comment]
Next step is to add the new Blocks and extensions of the Blocks  to the definition of done. Daniel needs help defining these Policy Blocks.

**Comment by envisionblockchainpm** [comment]
As of today, this is in Development. Valery is currently working on the backend side of the changes. Artem is doing the UI.

**Comment by envisionblockchainpm** [comment]
Alex will send over info of specific development steps that need to happen to put into ticket #280.

**Comment by envisionblockchainpm** [comment]
This is being worked on in parallel with the FUNC TION TO REDIRECT ticket. Can't finish this task because of the issue with the auto - generated fields. Shawn to add Blocker tomorrow.

**Comment by envisionblockchainpm** [comment]
As of today, the flow has been created but we have a Blocker with Auto-Generated Fields. It is unclear as per Alex how we can proceed with this. Auto Generated Fields needs to be implemented first.

**Comment by envisionblockchainpm** [comment]
This is still blocked by 367.  This will have to be moved to next Sprint. 367 will be completed this Sprint. We need to discuss with Andrey and Daniel.

**Comment by prernaadev01** [comment]
Playing around to test the release report
