### ISSUE TITLE
httpRequestBlock produces error even when successful

### ISSUE THREAD

**Issue by AlexIvanHoward** [hashgraph/guardian#2632]
### Problem description
"Document is not VC" error appears for all POST requests, even when those requests were executed successfully.

### Step to reproduce
1. Import and publish the following policy: 1693940954.386167003.
2. Under the 'Execute POST Request' tab, click on 'Perform POST request'. 
3. Complete the presented schema and click 'Create'. Note: Provide a valid web3.storage API token to the 'IPFS API token' field of the schema. This token will be uploaded to IPFS as part of the VC, so make sure you use a token that can be discarded immediately after this exercise.
4. Wait a few seconds and notice the "Document is not a VC" error that appears in the bottom-right corner of the screen. Navigate to your web3.storage account and see that the VC was in fact uploaded successfully to web3.storage.
5. Discard the API token that you used in step 3.

### Expected behavior
The "Document is not VC" error should not appear for successful POST requests.

### Screenshots
![image](https://github.com/hashgraph/guardian/assets/11308324/3bf32ef1-72d7-4c81-aa09-4461ebc0441b)

**Comment by anvabr** [comment]
@AlexIvanHoward perhaps there is a slight mis-understanding here. This block requires/expects a VC document with a valid schema returned to it, but in this case it does not get it - it gets a CID instead. 
```
 {
  cid: 'bafkreibkrwdxnsrgyexsvftfwjjojfmbokjo2zg66iijghpikfwdyag3pm',
  carCid: 'bagbaierafjq5zjwerxbvsbdvdl5idlsuvzggvxzvlvn5da2niyh3aphbhwpa'
}
```

**Comment by AlexIvanHoward** [comment]
> @AlexIvanHoward perhaps there is a slight mis-understanding here. This block requires/expects a VC document with a valid schema returned to it, but in this case it does not get it - it gets a CID instead.
> 
> ```
>  {
>   cid: 'bafkreibkrwdxnsrgyexsvftfwjjojfmbokjo2zg66iijghpikfwdyag3pm',
>   carCid: 'bagbaierafjq5zjwerxbvsbdvdl5idlsuvzggvxzvlvn5da2niyh3aphbhwpa'
> }
> ```

Hi Andrey. It's a POST request, though, so why would it be expecting a VC? I understand that it should receive a well-formed VC when executing a GET request, but not a POST request.

**Comment by anvabr** [comment]
> Hi Andrey. It's a POST request, though, so why would it be expecting anything in return? I understand that it should receive a well-formed VC when executing a GET request, but not a POST request.

It is a fairly common practice for both POST and GET to receive a result. In this case the block 'takes' any json document, and expect to receive a valid VC document in return  - this VC will them be passed to the next block for processing or embedding into a VP etc.

**Comment by anvabr** [comment]
It is a deliberate design decistion to only accept valid VC documents for security and consistency.
