### ISSUE TITLE
Testing of Implementation

### ISSUE THREAD

**Issue by blockchain-biopharma** [hashgraph/guardian#264]
USER STORY:
As a Root Authority User I want to make sure that the Verra / REDD APD Policy passes validation. 

DOD: 
- Once the policy is implemented and the workflow is created, the appropriate number of VCU's are minted.
- The Policy Workflow Passes Validation

**Comment by envisionblockchainpm** [comment]
Needs story point estimate. This is work for Max and @anvabr . Adding to Sprint 5
