### ISSUE TITLE
Aligning Digital MRV Specification for standardizing project comparison

### ISSUE THREAD

**Issue by prernaadev01** [hashgraph/guardian#2649]
### Problem description
Currently, in Guardian Schemas, we are using different Schema types such as String, Integer etc, which are used to defined data scope and project comparison. 

To make our current project comparison much more standardized as per IWA, we need to refer to Digital MRV specification, which can be found in : https://interworkalliance.github.io/TokenTaxonomyFramework/dmrv/spec/#enumdef-classificationcategory. In the above spec document, we noticed that we have an interesting attribute called : "Property", which would be very much useful in comparing project in more standardized manner.

### Requirements
1. Parse current dMRV spec and map with our current schema data types available in Guardian.
2. Create a new Schema entity called "Property" or similar to be in alignment with IWA dMRV spec. Doing so will accept allow mapping of standardized data types such as specific Strings, enums, etc.
3. Create project comparison leveraging the new Property entity.

### Definition of done
1. We should be able to get an IWA dMRV Standardized results during projects comparison results.
2. Testing the comparison functionality to make sure it meets all the standards.
3. Documentation to be completed.

### Acceptance criteria
Achieving Standardized project comparison results.

**Comment by dubgeis** [comment]
@Neurone @sergmetelin @justin-atwell @AlexIvanHoward @mattsmithies FYI

**Comment by dubgeis** [comment]
@cyndymo ^
