### ISSUE TITLE
Please help: "Transaction timeout exceeded" errors preventing manual Guardian installation

### ISSUE THREAD

**Issue by AlexIvanHoward** [hashgraph/guardian#2684]
### Problem description
I've been trying to set up a Guardian instance via the manual setup process detailed [here](https://docs.hedera.com/guardian/guardian/readme/getting-started/installation/build-executables-and-run-manually).

I started with an Ubuntu 20.04 distro, then installed and set up MongoDB (v6.0.3), NodeJS (v16), Yarn (v3.6.3), NTP Server (because NATS didn't want to work without it, although the manual Guardian installation guide does not say anything about installing NTP Server), [IPFS via Kubo](https://docs.ipfs.tech/how-to/command-line-quick-start/#prerequisites) (also not covered by the manual Guardian installation guide), and finally NATS (v2.9.8; the [prerequisites](https://docs.hedera.com/guardian/guardian/readme/getting-started/prerequisites) list v1.12.2, but the Guardian's Docker setup uses v2.9.8, so I figured it's safe to use v2.9.8 instead).

I then executed steps 1 - 7 of the manual Guardian setup guide and everything went OK. However, both steps 8 and 9 (building and starting **worker-service** and **guardian-service**) fail with a "Transaction timeout exceeded" error (see screenshot). Steps 10 - 12 succeed again.

I tried the following to remediate the issue, to no avail:
1. Allowing all possibly required ports through UFW (3000, 3002, 3003, 3006, 3012, 4001, 4222, 5001, 5005, 5006, 5007, 5008, 5009, 6555, 8080, 8081, 8200, 8222, 9080, 9090, 27017, 50000-60000).
2. Disabling UFW completely.
3. Tested the IPFS installation by retrieving files from and writing files to IPFS, without any Guardian involvement.
4. Increased the MAX_HEDERA_TIMEOUT variable in ./worker-service/configs/.env.worker.develop from 600 to 1200.
5. Increased the TASK_TIMEOUT variable in ./worker-service/configs/.env.worker.develop from 300 to 900.
6. Increased the IPFS_TIMEOUT variable in ./worker-service/configs/.env.worker.develop from 720 to 1500.
7. Changed the IPFS_NODE_ADDRESS variable in ./worker-service/configs/.env.worker.develop from 'http://localhost:5001' to explicitly 'http://127.0.0.1:5001'.
8. Specifying the hex version of my Hedera private key (instead of the DER encoded version).
9. Using `sudo` to start the services vs. not using `sudo` to start the services.
10. Explicitly increased the read and write buffer sizes to 2500000 (`sudo sysctl -w net.core.rmem_max=2500000; sudo sysctl -w net.core.wmem_max=2500000`)

### Step to reproduce
Reproduce all the steps I took above to try and set up a Guardian instance manually.

### Expected behavior
The **worker** and **guardian** services should not fail when trying to start them up via `yarn workspace worker-service start` and  `yarn workspace guardian-service start`.

### Screenshots
![image](https://github.com/hashgraph/guardian/assets/11308324/28bad193-86fa-4ec2-a29a-87328aa3e431)

**Comment by AlexIvanHoward** [comment]
Any update on this? Would really appreciate any help! Thank you in advance.

**Comment by prernaadev01** [comment]
@AlexIvanHoward Thank you for raising this ticket. We have internally discussed this issue and would request you to check if auth-service is running? Also, can you please send us logs file, it would give us more information on this issue.Thanks

**Comment by AlexIvanHoward** [comment]
Hi Prernaa. Please don't close this ticket yet as the issue has not been resolved yet. I was out on fieldwork last week, so wasn't able to respond to your response then. I will pay attention to it again this week.

**Comment by prernaadev01** [comment]
[like]  Prernaa Agarwal reacted to your message:
________________________________

**Comment by AlexIvanHoward** [comment]
Hi All

> @AlexIvanHoward Thank you for raising this ticket. We have internally discussed this issue and would request you to check if auth-service is running? Also, can you please send us logs file, it would give us more information on this issue.Thanks

auth-service is running, yes.


Please find the output of setup steps 5 ("Build and start logger-service service") to 8 ("Build and start worker-service service") in the text file attached. The error occurs at step 8. If you need more information, please let me know.

Thank you once again for taking the time to have a look at this. Much appreciated.

[log-setup.txt](https://github.com/hashgraph/guardian/files/13208448/log-setup.txt)

**Comment by anvabr** [comment]
Hi @AlexIvanHoward, we've been looking at this. We suspect the issue has been fixed in the newly released Guardian.  Would you be able to try it on the 2.18.0 please? We fixed a number of issues in this area, which should fix it.

**Comment by prernaadev01** [comment]
[like]  Prernaa Agarwal reacted to your message:
________________________________
