### ISSUE TITLE
Support for IF-THEN-ELSE branching in the policy definition language

### ISSUE THREAD

**Issue by anvabr** [hashgraph/guardian#271]
### Description
As a policy creator, when I am faced with a use-case where project questionnaire can change (new sections/questions added/removed) depending on (previous) answers, I would like to be able to use IF-THEN-ELSE elements to configure logical flow.

### Details
The example use-case for this is the VERA/REDD methodology where the flow (the documents or information that's required from the project) can change depending on the answers to various other questions about the project.

'IF' clause requires the existence of other operators:
- comparison: equals/not-equals
- AND/OR

Schemas containing the logical branching could end up being very large in size, which can results in bad UX filling out these questionnaires. As part of this ticket we should consider whether we need to introduce a Wizard type of forms, where screens (with sections) get added/removed as per IF-THEN-ELSE logic.

###DOD

- Logical branching IF-THEN-ELSE is supported in the product end-to-end (Schemas/UI)
- Acceptance criteria below is fulfilled. 

### Acceptance Criteria

- VERA/REDD policy use-case is supportable with the new schema language elements
- All changes to schema language are backward compatible.
- Documentation is updated

**Comment by prernaadev01** [comment]
This issue was closed on March 11th
