### ISSUE TITLE
Creation of Policy

### ISSUE THREAD

**Issue by envisionblockchainpm** [hashgraph/guardian#278]
USER STORY:
As a Root Authority User I want to see the Verra / REDD / APD Policy. 

DOD:
- Policy created and deployed to MAIN Branch

**Comment by envisionblockchainpm** [comment]
Assigning to you @Pyatakov for estimating. Please estimate. Adding to this Sprint as requested and this has been put into the Verra Development Epic as requested.

**Comment by anvabr** [comment]
Closed as duplicate of the 'prepare Demo' issue
