### ISSUE TITLE
Issue with duplication of projects in Verra policies

### ISSUE THREAD

**Issue by Celiant** [hashgraph/guardian#2824]
### Problem description
Projects are displayed incorrectly 

### Step to reproduce
1. Import Verra VM0007 (2.0.0) or Verra ARR policy and open policy in Dry run
2. Open "Projects" tab and create new project by Project_Proponent
3. Add this project by Administrator
4. Assign this project to VVB by PP
5. Validate the project by VVB
3. Open "Projects" tab and click on button "Add report " by PP
4. Open "Monitoring Reports"  and click on button "Add report " by VVB

### Expected Behavior
Projects are not duplicated by VVB

### Actual Behavior
Projects are duplicated by VVB

### Screenshots
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVdJQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7b8e197050d0070a50bcfa1bc2b27288c42876cd/1.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWVJQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6d2fbdd19e81c4292333906af7d642f4a5c860ca/2.png)

**Comment by artembuslaev** [comment]
**Verra VM0042** - 1698754542.390084003
**Verra VM0017** - 1698754789.539832483
**Verra VM0007 (3.0.0 - groups)** - 1698754217.516521003
**Verra VM0007 (2.0.0)** - 1698754116.549916003
**Verra ARR** - 1698755139.718108003
**Gold Standard AR** - 1698755331.068409570
**CDM AR-ACM0003** - 1698755906.758865003
**CDM AMS-III.D** - 1698756329.359347003
**CDM AMS-III.AR** - 1698756576.572245003
**CDM AMS-II.G** - 1698751171.908275443
