### ISSUE TITLE
Revamp Guardian user/roles and permissions model

### ISSUE THREAD

**Issue by anvabr** [hashgraph/guardian#2844]
### Problem description
Current user/roles model in Guardian is somewhat simplistic, and often does not map perfectly on business operations. For example policy authors is a very different level of responsibility to policy reviewer/approver, and even more so to token issuance account/role. Currently all these responsibilities are mapped to the same Standard Registry role.

### Requirements

- Fundamentally separate the concept of users, roles and permissions in Guardian
- Introduce granular concept of permissions which could be assigned to users, a user could then perform a specific function within the role if its assigned role 'contains' this permission. These should include (but not limited to):
  - Policy edit/submit for review
  - Policy view
  - Policy approval & publish
  - ...
- Introduce a "user admin" role, which allows:
  - defining new roles from permissions
  - assigning of roles to users
- Create a permissioning system which verifies actor role before any action has been taken throughout Guardian
- Package in suitable most-common role set into Guardian so it can be operated immediately 'out of the box' without the need for additional configuration
- Create a concept of 'delegation' where a user with a particular role/permission can explicitly 'delegate' this role/permission to another user
- Introduce the functionality to produce a report (page, download) which lists all users and their roles/permissions mapping in the system

### Definition of done

- Roles/permissions functionality is created as specified above
- The new functionality is documented

### Acceptance criteria

- Users are able to fine-tune the user/permissions/roles settings on their system at a granular level
- Guardian comes with an out-of-the box set of roles/permissions which allow immediate usage of the system in the most common generic use-cases
- It should be possible, for example, for an organisation to set up an SR and then invite multiple users to that SR account, which then will work in the same workspace on different policies but in the same instance
  - the same for project developers
  - the same for VVBs

**Comment by dubgeis** [comment]
@Neurone please add your thoughts cc: @sergmetelin @justin-atwell @prernaadev01 @anvabr regarding CURD operations

**Comment by dubgeis** [comment]
@anvabr Can we update to include the new user management via VCs enabled by the DID spec? cc @Neurone

**Comment by dubgeis** [comment]
This should be done via VCs and VCs should be revokable, which would be the key behavior we need to enable.

**Comment by anvabr** [comment]
List of permissions, grouped by type. The standard CRUD model is supported across most of the items. Other 'non-standard' permissions need to be processed and grouped into some generic one which can mean different things for different items.

[Guardian Permissions.xlsx](https://github.com/hashgraph/guardian/files/15248686/Guardian.Permissions.xlsx)
