### ISSUE TITLE
Custom Actors

### ISSUE THREAD

**Issue by envisionblockchainpm** [hashgraph/guardian#288]
Created as per @sergmetelin . Will also insert into the Roadmap

**Comment by sergmetelin** [comment]
This should be a continuation of https://github.com/hashgraph/guardian/issues/51

**Comment by envisionblockchainpm** [comment]
We just need confirmation from Serg / To Explain to Serg

**Comment by envisionblockchainpm** [comment]
Next step is for Serg to confirm this has been completed already and can be closed.
