### ISSUE TITLE
irec-policy-config.txt has incorrect url for MRV endpoint in individually built Nodes

### ISSUE THREAD

**Issue by gavinerasmus** [hashgraph/guardian#29]
The irec-policy-config.txt has the url of the message-broker set as "targetUrl": "http://message-broker:3003/mrv" which works in docker but not when you stand up each component yourself - it should be changed to "targetUrl": "http://localhost:3003/mrv". 

Suggest adding to the GitHub ReadMe to change this url for the non Docker build option.

**Comment by envisionblockchainpm** [comment]
This Ticket is slated to go into Development Next Week 11/22.
