### ISSUE TITLE
Issue in MongoDB node module

### ISSUE THREAD

**Issue by kirill-tolochko** [hashgraph/guardian#2909]
### Problem description
In some cases there is an error in mongodb node module

### Step to reproduce
1. Import Verra\Verra Redd\VM0044 policy
2. Run it in dry run, create Project_proponent user, create project, add it by administrator
3. Create VVB user, assing created project to this user
4. Check status history and console of policy service

### Expected behavior
Waiting for validation should be presented 2 times (or 1?) 

### Actual behavior
Now "Waiting for validation" is presented 3 times. 1 time right after it was added by administrator, and 2 times after it was assigned to VVB. 

Also there is an error in the policy service console:

2023-11-17T11:24:53.693Z [GUARDIAN_SERVICE,3ddad476-20bf-4103-803e-6eb793b1b690,sendToGuardianBlock,save_assign,6554ca6d393ee331e0a7d633]: runAction
MongoRuntimeError: File not found for id 65574d3951582bf6ebd2ca47
    at GridFSBucket.delete (C:\Users\...\guardian\node_modules\mongodb\lib\gridfs\index.js:70:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  [Symbol(errorLabels)]: Set(0) {}

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNi9sQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--165203a77f678c5d1ae8f3376ae03cda02cb98a7/image.png)

**Comment by simvalery** [comment]
#2145

**Comment by kirill-tolochko** [comment]
Now there are only 2 "waiting for validation" messages, that's ok.

**Comment by artembuslaev** [comment]
Fixed partially, duplicate events are a special case. Issue may occur when we are trying to update documents in parallel threads and it requires a more complex solution.
