### ISSUE TITLE
Policies stop working in MGS

### ISSUE THREAD

**Issue by CyndyMo** [hashgraph/guardian#2958]
### Problem description
Specific to MGS, individual policies across multiple tenants, which were previously working, suddenly stop working and present a Gateway timeout error with message "Policy doesn't exist". This has occurred 3 times now: in testnet twice,  under 2 separate admin accounts (I think this is 2 instances), as well as once in mainnet in the same instance as the testnet example shown in the video attached. If the policy that "doesn't exist" is exported and re-imported into the same or different instance, it works successfully. I exported and re-imported in mainnet in order to be able to mint. 

This issue needs to be resolved before MGS starts charging for policies published by an account, when re-publishing is the only way to fix this. It also leaved a "dead" policy that can't be deleted because it has data but can no longer be used.

This also needs to be resolved before real time usage of MGS to mint assets (that aren't transcription). Asking a validator to re-validate a project or push a button again because the policy suddenly stopped working is not a good look. 

Policy (attached) extension changed to a .zip so github will accept it. 

### Step to reproduce
1. Publish policy
2. Mint successfully
3.  Something mysterious happens (I really don't know what. Releases of MGS haven't occurred, the policy hasn't changed, no idea why this keeps happening.)
4. Try to open policy and get "Policy doesn't exist" with a Gateway timeout

### Expected behavior
Policies should not suddenly stop working.

### Screenshots
Video of the problem: https://drive.google.com/file/d/1qa-mWULJEAh68vLaBrkxo-4ZDNBKo5V8/view?usp=sharing
[policy_1701293040845.zip](https://github.com/hashgraph/guardian/files/13505671/policy_1701293040845.zip)

**Comment by prernaadev01** [comment]
@CyndyMo Thank you so much for raising the ticket. I will get this escalated to MGS team and get this solved asap.

**Comment by CyndyMo** [comment]
Thanks Prernaa! I know this is one of the tricky ones because there is no
clear cause and it’s tough to reproduce. If you need any additional details
or help in figuring it out please lmk!

**Comment by CyndyMo** [comment]
Did you close this ticket because of the policy deprecation and data
migration work? If so, I don't believe that actually solves the problem and
I also don't know that the feature would work to repair the work of the
project developer. Andrey has stated it can not be guaranteed. This is a
real issue in mainnet and until it is resolved the pay per policy
subscription model for MGS should not be implemented.

**Comment by prernaadev01** [comment]
@CyndyMo As this ticket was related to MGS and new version of MGS is released, which will solve this issue. This issue was solved in the latest version.

**Comment by CyndyMo** [comment]
Are you sure that that's true? There was no analysis in the issue as to
root cause or link to a ticket with action so I couldn't tell. If I see it
happen again am I supposed to just open a new ticket?

**Comment by prernaadev01** [comment]
We were facing this issue with MGS as some of the services were going down but we tested that before releasing our latest version and we didnt find that issue. 
I would request you to please test it once on testnet if that would be easy and let us know if it reoccurs. 
Once you confirms, I will close this ticket, I reopened it for now.
Thanks,
Prernaa

**Comment by CyndyMo** [comment]
OK TY. It may be a minute because of the refresh but I will.
