### ISSUE TITLE
Code audit: support and resolution of issues

### ISSUE THREAD

**Issue by anvabr** [hashgraph/guardian#2989]
### Problem description
Guardian codebase includes application code and on-chain logic (in Solidity) as well as some SDK-based chain operations. The complexity and diversity of this codebase presents a potential security risk, which can be reduced via audit by a 3rd party firm.

### Requirements

- Define scope and organise code audit and application penetration testing by a reputable 3rd party security firm.
- Support audit team with Q&A and setting up environments etc
- Resolve critical issues found.

### Definition of done
Code audit executed, all critical issues are addressed

### Acceptance criteria
No critical issues found during audit left unattended.

**Comment by swidnikk** [comment]
All sub-issues closed.
