### ISSUE TITLE
Analytics and Versioning Comparison Feature

### ISSUE THREAD

**Issue by envisionblockchainpm** [hashgraph/guardian#307]
EPIC USER STORY: 
These are the new steps that came into the policy with an explanation of why. Must display simply within the Guardian. In the case of DOVU, may communicate with 1000 farms. This is a User Story Wes wanted use to create. From the analytics of it, we have added X Type of Roles, showing the coverage analytics of each step, As per Wes, we could do a check, are we on the latest policy Yes/No? 

As per Daniel, when we create a new version it should be int the Memo Fields. 

DEFINITION OF DONE: 
- You can cross reference to token against the version of the policy its been created on .

**Comment by anvabr** [comment]
Closing as per discussion with Stakeholders on 19 Jan 2021, moving the requirements for the visibility of policy versions into the main tickets' (#310, #311) DODs
