### ISSUE TITLE
Discoverability of data on RootAuthorities, Policies, Auditors, Installers etc

### ISSUE THREAD

**Issue by blockchain-biopharma** [hashgraph/guardian#309]
### Problem description
As a Guardian user I would like to be able to navigate easily across and see all interrelated items of all types (RootAuthority and other users/roles, VCs, tokens, schemas, policies, etc) as well as to be able to extract the data in an appropriate format for import into or use by other programs (for further analysis). 

### Requirements
- Introduce a dashboard view of a single entitie's immediate relationship with other **types** of entities. The dashboard contains multiple tables - one for each type (e.g. Auditors) - each showing the list of entities of this type that the current entity is somehow related to. Content changes when the user clicks on the entity (navigating from the RootAuthority to an Auditor for example) in such a way that now the clicked entity becomes the focus of view and thus new tables appear showing direct relationships with the 'current' entity. There is a back and forward buttons to navigate the relationships.
- Introduce a dynamic graphical view of the interrelationships between Guardian entities presented in a form of [Force-Directed-Graph](https://www.highcharts.com/demo/network-graph) or a similar display. Consider the possibility of using [D3](https://github.com/d3/d3) or [Highcharts](https://www.highcharts.com) libraries for this. 
- Introduce ability to export this analytics data in the JSON format for import/transformation by other analytics programs (see [neo4j](https://neo4j.com/labs/apoc/4.1/export/csv/) for inspiration)

### DOD
- Ability to view, navigate and understand through the UI the relationships between all entities under a single RootAuthority
- A useable API interface for others (possibly used by the export functionality above) to retrieve the data
- Acceptance criteria fulfilled

### Acceptance criteria
- Via using The UI and APIs described above users are able to answer the following types of queries:
    - what roles and actors have been given credentials by this RootAuthority, what permissions they have
    - which policies (single or multiple) those actors work on
    - how many credentials have they given to a specific device or project
    - show quantitative output of those roles and actors in project token
    - how many actors are tied into what projects
    - what type of transactions on what project
    - show aggregates of the 'ecosystem' such as X Amount of Project Initiators, X Amount of Tokens, X Amount of Subcategory, X Amount of classifications, Metric Tonnage in Emission or Offsets
    - how many tokens created by a policy,  how many tokens created by the policy over a period of time
    - what are the quantitative amounts in units of account (could be a metric ton of carbon) represented by the created tokens
    - where tokens encumbered
    - where were the tokens sent
    - what is the price of the token

See [TRM Labs](https://www.trmlabs.com/) or [Chainanalysis](https://demo.chainalysis.com/kryptos/?utm_source=google&utm_medium=cpc&utm_campaign&utm_term=trm%20labs&utm_content=570509014559&gclid=EAIaIQobChMI0eLHvazN9QIVkZ-yCh2weAn7EAAYASAAEgLQyPD_BwE) for inspiration.

**Comment by envisionblockchainpm** [comment]
Next step is for Andrey to Review.

**Comment by anvabr** [comment]
@envisionblockchainpm while I understand the general direction here, I don't understand specifically for the scope of this ticket:

- does the analytics cover single (this, current) Guardian instance or should it show information that may have been created through a different Guardian instance
- how do those notes above relate to the 'single policy' - reading them they seem to be very broad and talking about single 'RootAuthority' not a single policy

**Comment by anvabr** [comment]
Brainstorming with Wes and Max - changed the title ('single policy analytics') as it was misleading. The analytics that is required is to show everything related to everything, rooted in the 'RootAuthority' entity down the tree all the way to the tokens. To give user the ability to see related entities of all types in the system, and the navigate the focus layer by layer, e.g. for a Policy to see who issued the policy, who uses the policy, which tokens been created under this policy etc.

**Comment by anvabr** [comment]
Next step: to find a suitable UI concept visually depicting interrelationships between entities and the corresponding statistics.

**Comment by anvabr** [comment]
Having thought more about this, I believe we aim to use both grid (with filtering) to navigate the data and chart - specifically '[force directed graph'](https://www.highcharts.com/demo/network-graph) to display the relationship visually. I previously had good experience with Highcharts library. 

Next steps:
- @Pyatakov is it technically feasible to use Highcharts in the OS Guardian?
- @sergmetelin and @danielnorkin is [Highcharts license model ](https://shop.highsoft.com/?_ga=2.220689244.599435497.1642433439-1692624684.1642433439)(free for non-profits) compatible with the context of OS Guardian?
- @envisionblockchainpm need to ask @mendelenvisionblockchain to design UX for this

**Comment by Mpinnola** [comment]
Hi Team, please see attached an outline of some metrics and information that would be useful to be able to discover/capture. Please let me know if you have any qu
[Issue 309_Data Discoverability-Analytics Priority Metrics 2-8-22.docx](https://github.com/hashgraph/guardian/files/8028091/Issue.309_Data.Discoverability-Analytics.Priority.Metrics.2-8-22.docx)
estions or comments. @anvabr
