### ISSUE TITLE
Cannot create standard registry user

### ISSUE THREAD

**Issue by AlexIvanHoward** [hashgraph/guardian#3095]
### Problem description
Since upgrading our Guardian instance to v2.20.1 (released on 10 January 2024) I cannot set up a standard registry user - whether it be the built-in "demo" StandardRegistry or a new one. 

### Step to reproduce
1. On the Guardian login screen go to "Demo Admin Panel" and click "Standard Registry".
2. Enter an operator ID and operator key or click "Generate" to generate a new ID-key pair, then click Next.
3. Enter valid values in all four fields (geography, law, tags and ISIC) and click "Connect" (Screenshot 1).
4. See the error that appears when the process reaches the "Publish VC Document" point (Screenshot 2). The exact text of the error is given in Screenshot 3.

### Expected behavior
One should be able to create a standard registry user.

### Screenshots
Screenshot 1:
<img src="https://github.com/hashgraph/guardian/assets/11308324/d3628b6e-b8ee-434f-9652-9106f403e6a0" width=30% height=30%>

Screenshot 2:
<img src="https://github.com/hashgraph/guardian/assets/11308324/955d33fa-88ca-4bea-9c98-a7e9e959b3d3" width=30% height=30%>

Screenshot 3:
<img src="https://github.com/hashgraph/guardian/assets/11308324/1d344b62-d6ab-46f0-94b1-c421ee5dc34c" width=30% height=30%>

**Comment by armarik** [comment]
Subscribing to this issue since I'm also having the same problem.

**Comment by AlexIvanHoward** [comment]
Hey Rita. Envision suggested to me a few hours ago that I should create another w3 space and then regenerate the IPFS_STORAGE_KEY and IPFS_STORAGE_PROOF. I did it and it solved the problem. Super weird, though - my previous space, key and proof were all perfectly valid and functioning.

**Comment by armarik** [comment]
Hi @AlexIvanHoward, thanks for reaching out. That's weird, my IPFS provider is set to local instead of web3storage; I can try and switch it to web3storage and see if it makes any difference, I guess.
