### ISSUE TITLE
Versioning support in Policy documents.

### ISSUE THREAD

**Issue by anvabr** [hashgraph/guardian#310]
### Problem description
As a Policy user (creator/editor or an individual/company operating under the policy) I would like to be able to clearly specify/view the version of the Policy I am working with so I can be compliant with the latest requirements/standards.

### Requirements

1. Policies are assigned versions when they are published.
2. Policy version and publish date is displayed in the UI whenever a user can see or otherwise access the policy.
2. The system preserves all previous published versions of the policy documents, i.e previously published version is stored in the DB and can be retrieved from the UI.
3.  For the moment publishing a new version of the policy has no effect on existing configurations (installers, auditors etc continue working under the policy version they've been working on). This is to change in the future (will be specified in a separate ticket).
4. Policy file syntax should contain 'header' block with the JSON elements for the following:

    - current version in the '[semantic versioning](https://en.wikipedia.org/wiki/Software_versioning)' format
    - date (when this version was published)
    - reference (contains 'free form' text reference of the original (textual) specification this policy version was built to represent). Can be empty.
    - reference version (contains the version of the reference document, in the format used by the original document). Can be empty. 
    - supersedes (contains the latest version immediately prior to this one which is no longer the latest).

### DOD

- Acceptance criteria fulfilled
- Demo policies are updated to include versions

### Acceptance criteria

- Valid policy documents must contains version information, otherwise they are considered invalid and not processed
- Policy version is visible in the UI wherever the name of the schema is displayed
- All published version of the documents can be accessed by users

**Comment by envisionblockchainpm** [comment]
Developers are going through a Decision Stage on this ticket. We just clarified. The team is now going back to finish the design, and it will then be down the implementation.

**Comment by envisionblockchainpm** [comment]
This has been estimated and will be going into Development tomorrow.

**Comment by envisionblockchainpm** [comment]
As per the meeting today, please change the behavior to NOT create a new topic when a new version of the policy is created.

**Comment by envisionblockchainpm** [comment]
This was Demo'd and can be closed.
