### ISSUE TITLE
Versioning support in Schema documents.

### ISSUE THREAD

**Issue by anvabr** [hashgraph/guardian#311]
### Problem description

Policies are required to support versioning (see #310), since schemas are included in the policies the versioning concept needs to extend to them as well.

### Requirements
Similarly to policies, schema syntax needs to have provisions for declaring the following:

   - Schema version (in semantic versioning style)
   - Date (in which the version has been 'released') 
   - Supersedes (previous schema version which is now not the latest)

### DOD

- Acceptance criteria fulfilled
- Demo schemas updated to include versions

### Acceptance criteria

- Valid schema documents must contains version information, otherwise they are considered invalid and not accepted
- Schema version is visible in the UI wherever the name of the schema is displayed
- All published version of the documents can be accessed by users

**Comment by envisionblockchainpm** [comment]
Developers are going through a Decision Stage on this ticket. We just clarified. The team is now going back to finish the design, and it will then be down the implementation.

**Comment by envisionblockchainpm** [comment]
Development has been started on this ticket.
