### ISSUE TITLE
RootAuthority account information decentralized

### ISSUE THREAD

**Issue by anvabr** [hashgraph/guardian#325]
### Problem description
RootAuthority 'account' record should be recoverable from Hedera and/or IPFS storage into a new instance of Guardian. An individual with the knowledge of the seed phrase would be able to recreate the account and access the assets (Policies, Schemas, DID, VC).

### Requirements
When a new RootAuthority is created the following sequence of events is taking place:
1. Create Hedera Operator ID and Operator Key,
2. Which then creates Hedera Consensus Service Topics (fill the account with test hBar),
3. And creates a DID document,
4. And creates a Verifiable Credential.

Each of these documents needs to be stored in the local instance DB (as it is now), the creation of them needs to be recorded as an event in the Hedera topic (with the DID of the RootAuthority in the Memo field) and with the Verifiable Links resolving to and the public data (except secrets) which needs to be stored either on in IPFS.

### DOD
- Acceptance Criteria fulfilled.
- Demo script is updated to show the RootAuthority recovery process.

### Acceptance Criteria
A user is able to 'recover' the previously created RootAuthority account onto a newly instantiated Guardian instance knowing only the seed phrase which was used at the creation of the RootAuthority.

**Comment by envisionblockchainpm** [comment]
This ticket is not ready yet, so we won't put anything int the next Sprint @danielnorkin
