### ISSUE TITLE
Standard Registry Creation Issue in V.2.21.1

### ISSUE THREAD

**Issue by Rajeev-KrypC** [hashgraph/guardian#3269]
Hi Team,

We have upgrade our guardian system to 2.21.1 version. When we try to create a standard registry with a new operator id and operator key, we are getting below error even though we are passing the respective values.

credential is not valid JSON-LD: { "type": "MISSING_PROPERTIES_IN_CONTEXT", "details": [ "credentialSubject.ISIC", "credentialSubject.geography", "credentialSubject.law", "credentialSubject.tags" ] }

Attaching the screen shots , logs and configuration. Please guide us in resolving this error.
[Config.txt](https://github.com/hashgraph/guardian/files/14370155/Config.txt)
[Logs.txt](https://github.com/hashgraph/guardian/files/14370156/Logs.txt)
![GuardianError](https://github.com/hashgraph/guardian/assets/134472833/34efac49-7c4d-4d04-9158-d52164fe78de)
![StandardSetup](https://github.com/hashgraph/guardian/assets/134472833/246ca5fb-a05d-4dc1-88e9-b0db7797d2db)

Note:
We are using local ipfs node.

**Comment by Puneet1080** [comment]
@Rajeev-KrypC Thank you for raising this ticket. We have reviewed it internally and seems like you need to change your IPFS_PUBLIC_GATEWAY to "http://ipfs-node:8080/ipfs/${cid}". Please let us know if this works. Thanks

**Comment by Rajeev-KrypC** [comment]
@prernaadev01 The issue is resolved after changing the mentioned url to http from https.
