### ISSUE TITLE
Productise Guardian API

### ISSUE THREAD

**Issue by anvabr** [hashgraph/guardian#330]
### Problem Description
As per #194, Guardian API was streamlined to enable external developers to build their own UI and/or integrations with their systems using Guardian back-end. This is the continuation of that work, to ensure that the API and its lifecycle is developed and managed as a product.

### Requirements
Make Guardian API production ready by:
- Developing and maintaining a comprehensive set of API tests and automated testing infrastructure which ensures API correctness and backward compatibility
- Instituting the process of API life-cycle management: versioning, deprecation and discontinuation of API calls
- Architectural enhancements to the API implementation which would ease development and production deployment for external parties (e.g. API decoupling).

### DOD
Requirements demonstrably addressed.

### Acceptance Criteria

- API versions are verifiably backward compatible
- Documented process of deprecation which is reflected in the API specification docs.
- API architecture is compatible with best practices of API development

**Comment by envisionblockchainpm** [comment]
We need to maintain Semantic Versioning of the API as per @sergmetelin
