### ISSUE TITLE
Number of assets in VC's (Trust Chain) and Guardian UI are incorrect

### ISSUE THREAD

**Issue by CyndyMo** [hashgraph/guardian#3311]
### Problem description
When a mint request is not fulfilled for whatever reason, the number of assets reported in the VC do not indicate how many were really minted. The Guardian UI is also inaccurate. This is linked to [issue 2480](https://github.com/hashgraph/guardian/issues/2840) which claims it is resolved with the same behavior occurring. This is also linked to https://github.com/hashgraph/guardian/issues/2833, which has been rolled into the Hedera resilience model ticket.

### Step to reproduce
1. From a published policy (Guardian version 2.21.1), attempt to mint more assets than can be afforded in the Standard Registry wallet. In this example, 10,000 were attempted.
2. The Guardian Trust Chain UI shows 0 tokens were minted (attached)
![image](https://github.com/hashgraph/guardian/assets/109111517/44431e27-dafd-4099-a312-f110ab33c963)
3. The only VC attached to the token only indicates the 10,000 requested (attached)
4. Scanning the chain, you find that 1560 NFT were minted (https://explore.lworks.io/testnet/tokens/0.0.3597026/nfts/1) only identifiable as connected via the memo field. Probably a separate ticket, or maybe to roll into the resilience issue, but I would also like to know the specific serials generated as a result of a mint request. I would like that in a VC connected to the request VC.

### Expected behavior
1. Guardian should always mint the exact amount of assets to satisfy the requested amount (also covered in the resilience model ticket).
2. The VC documents produced in the chain should indicate exactly how many assets were minted and their serials, not just what was requested. If multiple mints are needed to satisfy the request, those VC should be recorded and linked to the single mint request VC.
3. The Guardian UI should also display the actual amount of tokens (NFT) minted in the Trust Chain tab, not 0 when there are not 0 minted.

### Screenshots
[ipfs_file2.txt](https://github.com/hashgraph/guardian/files/14483167/ipfs_file2.txt)

**Comment by prernaadev01** [comment]
@CyndyMo Can you please share the policy file with us,if possible. It would help us to reproduce the issues and resolve it asap.

**Comment by CyndyMo** [comment]
This is the exact policy that was used. If there is a block that can be
used to pull the "what was actually minted" and serials from the chain pls
LMK. I have asked and Swirlds didn't seem aware of it.

**Comment by prernaadev01** [comment]
@CyndyMo Can you please check if the policy was correctly attached?

**Comment by prernaadev01** [comment]
@CyndyMo Thank you for sharing the policy file. After looking at it, we found out that there was an issue with token association. Can you please check the below image.
Also, you can check on this link: https://hashscan.io/testnet/transaction/1709126875.338174003
![image](https://github.com/hashgraph/guardian/assets/79293833/786ced07-4389-45fb-badb-c7163af35c7b)

**Comment by CyndyMo** [comment]
I know there is. I was testing how to token associate to a custom account
and got an answer from Andrey on that. If you set the recipient account to
default the policy exhibits the same behavior noted in this bug.

**Comment by prernaadev01** [comment]
Thank you so much @CyndyMo .  We are looking at this.
