### ISSUE TITLE
Broken link in Readme: Postman Collection  Postman 

### ISSUE THREAD

**Issue by christiaanpauw** [hashgraph/guardian#332]
### Description

The link in the text "Collection that covers all available API endpoints could be found here." 

The link is currently:
https://github.com/hashgraph/guardian/tree/main/ui-service/api/Guardian%20API.postman_collection.json

I think it should be:
https://github.com/hashgraph/guardian/blob/main/ui-service/api/Guardian.postman_collection.json

### Steps to reproduce

Navigate to https://github.com/hashgraph/guardian#postman-collection

Click on link " [here."](https://github.com/hashgraph/guardian/tree/main/ui-service/api/Guardian%20API.postman_collection.json)

404

### Hedera network

other

### Version

Guardian Github page

**Comment by envisionblockchainpm** [comment]
Next step is for Alex to make this change.

**Comment by envisionblockchainpm** [comment]
Closing. This is in the Development Branch completed, and will be moved to Main Branch next Release.
