### ISSUE TITLE
Default Guardian Logo during launch

### ISSUE THREAD

**Issue by prernaadev01** [hashgraph/guardian#3335]
### Problem description
Currently, whenever Guardian is built and launched, we only see a blank header in the side menu, which can be changed by using Branding functionality in Guardian, but it would be good to add default Guardian logo during launch instead of placeholder.

### Requirements
1. Add Default Guardian logo in the left side menu when Guardian is launched. Sample design is shown in the figma link: https://www.figma.com/file/r4opkmPm3TPieVSXTb0pjK/Design-file-(Guardian)?type=design&node-id=344%3A20010&mode=design&t=tKz92C5Bc1n0tfvJ-1

Image: https://www.figma.com/file/r4opkmPm3TPieVSXTb0pjK/Design-file-(Guardian)?type=design&node-id=344%3A3669&mode=design&t=tKz92C5Bc1n0tfvJ-1

2. Make sure it is responsive on all the screen resolutions.

### Definition of done
1. Adding Default Guardian Logo as per the design mentioned above.

### Acceptance criteria
We should be able to see Guardian Logo with respective to the screen resolution in the left side menu during launch.

**Comment by Pyatakov** [comment]
Implemented in v3.0
