### ISSUE TITLE
Toggle VC view between Form (default) and Raw

### ISSUE THREAD

**Issue by anvabr** [hashgraph/guardian#335]
### Problem definition
As a user of Guardian I would like to be able to see VC document in an easily digestible format, but also should be able to 

### Requirements
Build a capability to switch between 'Form' view and 'Raw' view, with 'Form' being default. The view should be accessible on the:
- audit page (VC & VP)
- profile document view
- Block grid

### DOD
- Acceptance criteria fulfilled
- Documents and demo scripts are updated accordingly

### Acceptance criteria
- Graphical element switching the view as per requirement, without noticeable delay
- 'Form' default view

**Comment by envisionblockchainpm** [comment]
ETA to completion is Monday. Leaving in Sprint 5.
