### ISSUE TITLE
Improve UI/UX of edit button in Policy Page

### ISSUE THREAD

**Issue by prernaadev01** [hashgraph/guardian#3379]
### Problem description
Whenever policy is created/imported, Guardian new UI does not allow the user to see edit button right away. In order to click on edit button for a specific policy, user to have scroll to totally right and click on it, which is not a good practice as it might be missed and user would assume that policy is unable to edit it.

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmtLQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c9a78fcdf7744f05e021f2efe60314f3d27f188c/image.png" alt="image.png" />

### Requirements

1. Need to move the existing Edit button in the Manage Policies/Schemas page somewhere near the side menu to make sure it is visible.
2. Update the documentation with all the required screenshots.

### Definition of done
Update the Edit button in Manage pages.

### Acceptance criteria
Make the required Ui changes and documentation update.

**Comment by denischasovskikh** [comment]
https://www.figma.com/file/r4opkmPm3TPieVSXTb0pjK/Design-file-(Guardian)?type=design&node-id=1246%3A27372&mode=design&t=QWUlbXXcOpUzGof4-1

<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMU0wQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--65e468ac6fa93313c1ca28d25d27ccb2895b0958/Screenshot%202024-04-04%20at%2013.00.41.png" alt="Screenshot 2024-04-04 at 13.00.41.png" />
