### ISSUE TITLE
Introduce 'Projects' to express relationships between concepts/entities

### ISSUE THREAD

**Issue by anvabr** [hashgraph/guardian#357]
### Problem description
As a user of Guardian I would like to be able to see details and summaries of the relationship between various entities. It appears that currently there is no way to discover this information, i.e. there is 'relational DB' or a system to capture and record relevant events. Thus there is no easy way to discover this information, it's easy to verify its accuracy (owing to the nature of blockchains and cryptography) but it's currently impossible to have an exhaustive list of all that's been issued/created/signed etc. 

### Requirements
Add the concept of 'Project' to Guardian which groups together:
    - Root Authority (the same 'instance' participates in many projec ts)
    - Policy (+all related schemas) execution content
    - Entities with custom roles, e.g. Installer, Verifier, Sensor. Sensor and any other entity generating data can only belong to a single project.

The concept of the project has to appear throughout the UI and the API whenever  Policy Engine is run.

This ticket is needed for #387 

### DOD
- Documentation and demo updated to include the concept of the project

### Acceptance criteria
- Logical structure of the relationship between project and other entities is understandable and is expressed through the guardian UI.

**Comment by envisionblockchainpm** [comment]
Next step is to bring this up in todays Grooming.

**Comment by envisionblockchainpm** [comment]
Next step is the meeting next week with the Hedera Team.

**Comment by envisionblockchainpm** [comment]
This requires a Discovery Round 2 which has been scheduled for tomorrow with the Hedera Team.

**Comment by anvabr** [comment]
@Pyatakov to create a diagram depicting the relationships between entities and concepts in Guardian.

**Comment by anvabr** [comment]
The next step is to introduce the concept of Project and link it to policy/actors etc. Depict this on the diagram. @Pyatakov

**Comment by prernaadev01** [comment]
As Ticket #387 is being implemented, this ticket can be closed now.
