### ISSUE TITLE
QA: Scalability and capacity testing

### ISSUE THREAD

**Issue by danielnorkin** [hashgraph/guardian#36]
### Problem description
Guardian is required to operate at the 'enterprise-level', potentially handling large numbers of users, documents and transactions. At present there are no quantitative data about its ability to fulfil this requirement, and therefore no strategy or best practices can be developed for scaling the solution for different use-cases.

### Requirements

- Create an automated scalability and capacity testing framework using, ideally, OSS tools.
- Run and establish capacity baseline.
- Integrate these into our release pipeline so the changes can be monitored for every release. 
- Experiment and extend the test suite to identify bottlenecks and develop understanding of the system capacity behaviour in various deployment (scale) configurations.

### Definition of done

- Automatic test load scripts exists, using API. 
- Test can be triggered with minimal manual involvement.
- The test framework is extendable.

### Acceptance criteria

- Coverage for capacity and scalability testing end-to-end for iREC and VERRA demo policies.
- Token mints tests are included.

#### Notes
Benchmark: - Need a timebound of 3,000 TPS Across these categories for 24 hours and then 7 days as the benchmarks. If it goes down, need to reconnect. Hedera has one client on the CTE side is looking to do this number of transactions, so this is where this requirement is driven from.

**Comment by envisionblockchainpm** [comment]
Next step is for @envisionblockchainpm , @danielnorkin , and @anvabr to discuss where this ticket fits in priority-wise as it is in scope for Envisions work as per @dubgeis .

**Comment by mattsmithies** [comment]
Having an after-action retroactive is a must given that every root authority will be expected to push 300 TPS each, I believe there is a high likely hood that services might need to be reset mid-way through the test with fresh connections to the Hedera nodes.

You might be throttled if the step function troll comes to visit too.

This is what we produced after our scale test: https://dovu.earth/en/scaling-infrastructure-how-we-did-it/

**Comment by dubgeis** [comment]
@anvabr we're going to need to test at 100B DIDs per user requirement. cc @sergmetelin @justin-atwell. Please use this on the CET policy.

**Comment by anvabr** [comment]
> @anvabr we're going to need to test at 100B DIDs per user requirement. cc @sergmetelin @justin-atwell. Please use this on the CET policy.

I would love to know more about this please! @dubgeis
