### ISSUE TITLE
API JSON Commenting

### ISSUE THREAD

**Issue by envisionblockchainpm** [hashgraph/guardian#361]
### Requirement
As a Guardian User I would like to see in the API definition information on **mandatory** (or 'required') parameters and for **optional** parameters for API calls.

### Definition of Done
- Updated swager and postman API documentation
- Updated JSON file

**Comment by simvalery** [comment]
https://github.com/hashgraph/guardian/pull/394

**Comment by envisionblockchainpm** [comment]
Closing this Ticket. The Swagger and Postman API Documentation and JSON File were updated.
