### ISSUE TITLE
QA: Disaster Recovery Testing

### ISSUE THREAD

**Issue by blockchain-biopharma** [hashgraph/guardian#362]
### Problem description
In the event of a catastrophic failure of systems there is currently no defined way to restore Guardian operation.

### Requirements
Develop a DR test case to be performed regularly, for each release. Use procedure defined in #462 as a guide.

### Definition of done
They QA team is able to independently perform DR test on Guardian instances. 

### Acceptance criteria
- Semi-automated DR test.

**Comment by envisionblockchainpm** [comment]
We need to estimate this and Andrey needs to further flush out the user story. Adding it to this Sprint 6 to get this done.

**Comment by envisionblockchainpm** [comment]
As of today, Andrey is still thinking about this tickets Requirements. Andrey still have some Discovery to do with the Hedera Team, so this will be updated when he knows the Development Plan for this.
