### ISSUE TITLE
Create Scalability Testing Plan

### ISSUE THREAD

**Issue by blockchain-biopharma** [hashgraph/guardian#363]
## Context and scope 
Guardian scalability could be considered in two dimensions: 

- Ability of the instance of Guardian application/platform to scale its processing capacity up and down with fluctuations in demand. 
- Overall capacity of the distributed Guardian system to handle large demand/workloads across all instances. 

The latter is to a large degree determined by the scalability of the distributed services Guardian uses for persistence, namely Hedera blockchain and IPFS storage system.  

Currently there is a one-to-many relationships between Guardian instances and Standard Registries.  In other words, an individual Guardian instance can host multiple Standard Registries (SR), and an individual Standard Registry can only function in the context of a single Guardian instance at any time. This ensures the scalability ‘down’ - i.e. a multi-tenancy where a single hosting/platform provider can serve multiple low-demand SRs and their clients. 

Therefore, this scalability plan will consider the scalability of the single instance of Guardian hosting a single SR, with multiple policies, projects and users. Implementation of such testing will result in the highest ROI, the behaviour of the system in other configurations can be extrapolated from the findings. 

## Requirements
Each of the parameters listed below should be tested as both: 

- a static parameter indicating system capacity (determining at which scale/number the rest of the system will cease to operate within the acceptable SLAs). 
- an operational throughput metric (what is the rate of growth/increase of this number the system can handle). 

**Parameter 1**: Number of DIDs. 

**Parameter 2**: Number of active Policies. 

**Parameter 3**: Number of active Projects. 

**Parameter 4**: Number of Policy blocks (policy complexity) in an active Policy. 

**Parameter 5**: Number of MRV data sources in an active Policy. 

**Parameter 6**: Single policy MRV data processing throughput. 

**Parameter 7**: Token minting performance (throughput in tokens/second). 

Note: on-chain token management is excluded from this test plan for two reasons: firstly, the scalability of these would likely be fully determined by the capabilities of Hedera platform, and secondly because this functionality has not been implemented or designed yet. 

### Metrics
For all metrics the goal is to determine the saturation point (i.e. 100% capacity), following which monitor and report on the 80% capacity level. For the purposes of the test 80% capacity should be considered to be the safe level for sustained operation. 

- CPU utilization. 
- Memory utilization. 
- Local storage (cache) access and size. 
- Hedera requests (per type) per second. 
- Canary request API response time. 

For the minimum acceptable SLA, the limit of 5 second API call response time will be used. The team will select the appropriate API call (a.k.a. ‘canary API’) which can represent the overall system operational ‘health’ status. 

### Tests
All scalability testing will need to be performed through the API. A set of test automation scripts will be created targeting the functionality for each of the application parameters. The test loader performance must exceed that of Guardian, i.e. it must be capable of saturating Guardian instance with requests in every functional area. 

These tests would be run individually against the instance in the default configuration. This will determine the raw maximum capacity of the system for each of the parameters based on the resource utilization metrics and the response time SLA. 

The level of 5% resource consumption in each area will then be considered to be ‘background load’. This load will be used for the ‘constant’ parameters in further tests targeting at finding the bottlenecks and determining the scaling capacity of the system. 

### Monitoring
A running Guardian instance consists of as a set of micro-services, with message queue interface between them. It is therefore possible to vary the capacity of each service individually, either horizontally or vertically. 

The test harness will collect metrics for each service independently, which would enable precise analysis of bottlenecks and inform scaling configuration decisions.

### Hardware and tools
The tests are to be performed on two types of AWS hardware which should indicate the degree of vertical scalability: 

- EC2 – medium 
- EC2 - large

For test scripting use [K6](https://k6.io/open-source) (or other suitable tool - TBD).

## Definition of Done

- Scalability testing system exists and the tests are run for every release.
- Scalability tests results show the capacity of the system.

**Comment by envisionblockchainpm** [comment]
We need to estimate this and Andrey needs to further flush out the user story. Adding it to this Sprint 6 to get this done.

**Comment by envisionblockchainpm** [comment]
The next step is to flush out this ticket and estimate. We need more information on what Hedera is expecting for this ticket.

**Comment by anvabr** [comment]
[Guardian Scalability testing.pdf](https://github.com/hashgraph/guardian/files/8942767/Guardian.Scalability.testing.pdf)
@sergmetelin @justin-atwell @dubgeis your review and comments would be greatly appreciated.

**Comment by anvabr** [comment]
Useful document on hedera perf testing from [Dovu](https://dovu.earth/en/scaling-infrastructure-how-we-did-it/).
