### ISSUE TITLE
Indexer API

### ISSUE THREAD

**Issue by anvabr** [hashgraph/guardian#3637]
### Problem description
Users can access the Guardian-produced data and observe its usage via the UI of the platform developed in the course of #2629. Follow-up analytics #3341 and #3336 functionality enable complex data exploration use-cases using advanced queries and charts. However some applications require programmatic access to the same data/analytics instead of the hosted UI.

### Requirements
Add suitable API facilities which would allow programmatic access to the indexed data and analytics, which include policy structure data (such as formulas used in the various elements - e.g. Tools) as well as project data.

### Definition of done
API is available and documented

### Acceptance criteria
Programmatic access to the indexed data and analytics matches that of the UI.

**Comment by 0xAurelius** [comment]
Hey there, Marcus here, been working with tokenized carbon data for a few years.

Ideally this API should expose all relevant metadata about the project, including at least:
- name
- registry project ID
- description
- methodology
- location (ideally latitude/longitude or boundary polygons)
