### ISSUE TITLE
[UI/DATA BUG]: Dupplicated project after it has been approved by the SR

### ISSUE THREAD

**Issue by MarcAntoineLebourgeois** [hashgraph/guardian#3643]
### Problem description
Context: ACM0002

### Step to reproduce
When a PP create a project, it must be approved by the SR.
After the SR approves it, then the projects are dupplicated in the UI of the PP.

### Expected behavior
We can expect the project don't be duplicated 

### Screenshots
![image](https://github.com/hashgraph/guardian/assets/50228285/29b077fb-4084-4a0c-8abe-c4bec5cf18c9)

**Comment by MarcAntoineLebourgeois** [comment]
I have the same issue on my local guardian instance and in MGS.
Plus, a colleague of mine met the same issue.

**Comment by prernaadev01** [comment]
@MarcAntoineLebourgeois Thank you so much for raising this ticket. We are looking at it and will fix the policy asap. Will keep it posted.

**Comment by ilyozzz** [comment]
Hello @prernaadev01 

We've met the same issue in Verra VM0047 policy when working via API. VVB validates a project and sees several copies of it with different statuses. But it's not reproducible through UI

**Comment by prernaadev01** [comment]
@ilyozzz Thank you so much for the information. Only one ticket should work. We are working on it. Will keep you posted on it.

**Comment by prernaadev01** [comment]
@ilyozzz We tried it reproducing but we are unable to do it. So, can you please send us API requests and responses, which you are trying to execute the policy. That would be really helpful for us. Thanks.
