### ISSUE TITLE
Cover Functionality with Unit Test

### ISSUE THREAD

**Issue by danielnorkin** [hashgraph/guardian#37]

**Comment by danielnorkin** [comment]
This is a technical task that includes the creation of the Unit Tests for the critical functionality of the Guardian. The tests will include coverage of the following components:

- UI Service
- Guardian Service
- Message Broker Service

**Comment by envisionblockchainpm** [comment]
@Stepan-Kirjakov , is currently working on this and will be working on this the W/O 11/22.

**Comment by simvalery** [comment]
https://github.com/hashgraph/guardian/blob/develop/README.md
