### ISSUE TITLE
Climate Action Reserve's U.S. Landfill Protocol

### ISSUE THREAD

**Issue by prernaadev01** [hashgraph/guardian#3709]
### Problem description
Developed by the Climate Action Reserve (CAR), the U.S. Landfill Protocol facilitates the quantification, monitoring, reporting, and verification of greenhouse gas (GHG) emission reductions associated with the collection and destruction of landfill gas (LFG) at eligible U.S. landfills. This protocol supports projects that capture and destroy methane emissions, leading to significant environmental benefits and the generation of carbon offset credits.
Additionally, this methodology will be designed and digitized to create digital assets that quantify emissions reductions and environmental benefits, enabling more efficient project workflows and transparent reporting for landfill operations.

### Requirements
1. Creating Schema design for this methodology.
2. Development of the schema and policy.
3. Testing the policy development through Guardian UI and configurator.

### Definition of done
1. Policy is designed and developed and approved after testing.
2. Policy file is added in Github repo.
3. Policy is documented with complete detailed Step By Step process.
4. IPFS timestamp is created for Policy file.

### Acceptance criteria
Methodology is completed with detailed testing and approvals.

**Comment by dubgeis** [comment]
Suggestion from CAR to change to Mexico Forest Protocol or another more utilized
