### ISSUE TITLE
Swagger API documentation

### ISSUE THREAD

**Issue by danielnorkin** [hashgraph/guardian#38]

**Comment by danielnorkin** [comment]
This is a technical task that includes adding descriptions to all endpoints in services.

**Comment by envisionblockchainpm** [comment]
As a following up to todays Grooming Session with @danielnorkin  I am tagging @sergmetelin  as a reminder to have a data field for the ORG responsible for submitting the Swagger ticket.

**Comment by envisionblockchainpm** [comment]
This should be moved to Done on Monday morning and completed today as per 11/18 Scrum. This is almost finished.

**Comment by danielnorkin** [comment]
@sergmetelin and @dubgeis this ticket is ready for UAT. Do you want someone who is interested in this aspect go into the Develop branch and check it out so we can close this issue?
