### ISSUE TITLE
Linking VCs via API does not work

### ISSUE THREAD

**Issue by AlexIvanHoward** [hashgraph/guardian#3805]
### Problem description
Linking VCs via the API still does not work. This issue was originally raised as a [discussion](https://github.com/hashgraph/guardian/discussions/3270), but the problem still persists. My [first contributions](https://github.com/hashgraph/guardian/discussions/3270#discussioncomment-9118281) to the discussion were based on Guardian v2.21.1. I have since tested it on a newer version of Guardian (not entirely sure which one, because the version number does not show up when I go to 'Administration' > 'About', but I think it's v2.24.1 or v2.25.0), still without success. 

Attached is a screen recording I made just now.

Note that I have tested it on both `/api/v1/policies/{policyId}/tag/{blockTag}/blocks` and `/api/v1/policies/{policyId}/blocks/{blockId}`; neither was successful.

### Expected behavior
Linking VCs via POST requests to requestVcDocumentBlock elements of a policy should succeed.

https://github.com/hashgraph/guardian/assets/11308324/0c70694f-65a8-4f44-a86b-ac165139aa85

**Comment by anvabr** [comment]
@AlexIvanHoward thank you for the detailed explanation. Could you please upload a policy with which you have observed this behaviour so we are able to reproduce this exactly how you observe it?

**Comment by AlexIvanHoward** [comment]
@anavbar Here is the policy that I used in the screen recording:
[policy_1713185713329.zip](https://github.com/user-attachments/files/15937172/policy_1713185713329.zip)
