### ISSUE TITLE
Adapt VC processing for IPFS storage

### ISSUE THREAD

**Issue by anvabr** [hashgraph/guardian#384]
### Problem description

Current VC schema processing makes a number of assumptions about the content of the VC and the location of various resources. These assumptions are no longer true in the environment where decentralised storage is used.

### Requirements
- Implement json processing into json-ld compatible format
- Change blocks to reference Hedera topics instead of UUIDs
- Change the schema loader to load schemas using new IDs
- Adapt document loader to process IPFS references correctly for VC signing and validating

### DOD
Acceptance criteria fulfilled

### Acceptance criteria
VC operations are performed seamlessly (as before) for the new environment where referenced documents are stored on IPFS

**Comment by envisionblockchainpm** [comment]
Closing the ticket. Ticket Status is that this ticket will need additional effort to rationalize how we deal with Verified Credentials. We want to have a unified method of publishing. Next step is for Andrey to create a separate ticket and refine the ticket.
