### ISSUE TITLE
`INITIALIZATION_TOPIC_ID` web documentation

### ISSUE THREAD

**Issue by JackDiSalvatore** [hashgraph/guardian#3854]
The `INITIALIZATION_TOPIC_ID` is out of date and should be `0.0.1960` in docs
https://github.com/hashgraph/guardian/blob/main/docs/guardian/readme/getting-started/installation/launching-guardian.md

**Comment by prernaadev01** [comment]
Thank you so much for this ticket. We have made these changes and will be merged asap.
