### ISSUE TITLE
Change Error Messaging

### ISSUE THREAD

**Issue by envisionblockchainpm** [hashgraph/guardian#386]
## Change Error Messaging 
Change the error messaging from does not published to isn't published.

## Definition of Done
- Error messaging updated in code-base, and approved

**Comment by anvabr** [comment]
![Screenshot 2022-02-03 at 14 57 40](https://user-images.githubusercontent.com/32775532/152367937-702234c6-171d-4c4e-b94e-8d9ae1f57312.png)

**Comment by envisionblockchainpm** [comment]
The ticket can be closed and the Error Messaging has been updated. This will be in the MAIN Branch on the next Release which is February 8th.
