### ISSUE TITLE
Policies, Projects and Topics mapping

### ISSUE THREAD

**Issue by anvabr** [hashgraph/guardian#387]
### Problem description
In the real-world scale of potentially tens (or hundreds) of thousands of projects executed under the same policy it will be difficult to track/navigate relationships between Policies, Projects, VCs, Tokens and various other artifacts produced in the course of the lifecycle of the project. Guardian need a clear records mapping structure, so events associated with the above can be efficiently monitored by interested parties.

Pre-requisite: #357 

### Requirements
Implement the functionality so the following is true:
    - Each policy (all versions) has a its own (unique) Hedera Topic associated with it (where events e.g. 'new version of the policy has been produced' are published)
    - All events about the policy itself, and about initiation (only) of projects in compliance with this policy are posted into this topic
    - Each project under the Policy gets its own Topic, information about which is posted into the Policy Topic (as per above)
    - All events etc for a particular project are posted into its Topic, and no other Topics

List of the artefacts and Hedera locations:
| Document  | Created at | Hedera Topic | Content |
| ------------- | ------------- |------------- |------------- |
| DID document for Root Authority (RA)  |  registration  |  RA | IPFS location of the doc |
| VC document for Root Authority (RA)  |  registration  |  RA | IPFS location of the doc |
| DID document for User  |  registration  |  RA | IPFS location of the doc |
| VC document for User |  registration  |  RA | IPFS location of the doc |
| Policy document  |  creation  |  RA  | The 'Policy' topic where the updates would be published|
| Policy document  |  publishing  |  Policy | IPFS location of the doc |
| Schema document  |  creation/publishing  |  Policy | IPFS location of the doc |
| DID document for Project  |  creation  |  Policy | Topic where the updates would be published|
| VC document for User/Role  mapping |  role assignment  |  Project | IPFS location of the doc |
|Various VC documents created as a result of 'execution' of a particular policy in the context of a particular project| policy execution | Project | IPFS location of the doc |

With this model users would be able to navigate the entire map of concepts and entities.

![Entities and Topics mapping](https://user-images.githubusercontent.com/32775532/160054676-f2db8cc7-c361-49e1-ba6c-e2fb97d14610.png)

### DOD
- Acceptance criteria fulfilled
- Documentation updated

### Acceptance criteria
- Information flows are implemented as per requirements
- There is a **two-way** navigation between all related topics and entities. This includes minted tokens - users must be able to figure out which project and policy this token was minted under.

**Comment by dubgeis** [comment]
@anvabr Can we make sure there is a method to maintain the same auditor/VVB/custom actor DID consistently across policies/projects/RA's? cc: @justin-atwell @sergmetelin

**Comment by dubgeis** [comment]
Ideally we'll have indexes that score DIDs and tokens based on their reputations as a project and DIDs across projects and want to think about standards for this

**Comment by jayv80** [comment]
Just some comments on the identity components/Document:

- **DID Document** => This a dynamic document stored in a Verifiable Data Registry, which is determined by DID-Method Specification it utilizes. So to give maximum support for different DID methods, the easiest way is just to store the DID itself as reference and resolve the DID Document through the [Universal Resolver.]( https://github.com/decentralized-identity/universal-resolver)

This way, the guardian could support multiple and different Identity fabrics. 

- **Verifiable Credential** => VC itself are quite static and personal. This is stored encrypted and directly either on an edge based device (Wallet) or on a cloud based solution (Vault). The possible item that could be stored from an audit perspective is a Verifiable Presentation, which is used for proof or accessing services.
Also the Verifiable Presentation is something the User can control on disclosing certain attributes based upon consent. It also contains a nonce that can tie it to an transaction and avoid replay actions. (both legal and security aspects)

**Comment by dlin-me** [comment]
Is it part of the design to store parent topic id in child-topic's memo field ? 

If so, this allows navigation backward from MRV event => Project events => Policy events => RA events. This means the whole trust chain can be built on chain by filtering for interested events (and the associated content/documents) in the relevant topics. 

I am confused around  user registration where both RA and User take 'profiler filling' action to create VCs for user. Is this related to [#611](https://github.com/hashgraph/guardian/issues/611) ?

Also, roles are defined at the Policy level.  Assuming User can not be assigned with different roles amongst Projects under the same Policy,  shouldn't User/Role mapping be done at the Policy level ?
