### ISSUE TITLE
Postman API Documentation

### ISSUE THREAD

**Issue by danielnorkin** [hashgraph/guardian#39]
@anvabr and at myself really, Just a reminder from Wes: Please add Nicola to the “community notice” in addition to DOVU for DoD

**Comment by danielnorkin** [comment]
This is a technical task that includes adding descriptions to all endpoints in services.

**Comment by envisionblockchainpm** [comment]
@simvalery  Plans to create Swagger Documentation, and then add to Postman. We will need to create some fixes for Postman Config.

**Comment by danielnorkin** [comment]
@mattsmithies

**Comment by envisionblockchainpm** [comment]
@sergmetelin This has been completed. Here is the Link to Postman: https://github.com/hashgraph/guardian/blob/develop/ui-service/api/Guardian%20API.postman_collection.json
