### ISSUE TITLE
Same block works through the UI, but not through the API

### ISSUE THREAD

**Issue by ilyozzz** [hashgraph/guardian#3931]
### Problem description
VM0047 policy has a step where the SR adds project to the pipeline. It works through UI but when we call the same block through API then nothing happens. But in both cases the guardian just returns HTTP 200 empty responses

### Step to reproduce
1. Go to VM0047 policy
2. Create project as Project Proponent and login as Standard Registry
3. Add project to pipeline
4. Check the project is added to pipeline
5. Call API for the block which adds project to pipeline (the same as UI does)
6. Check the project is not added to pipeline

https://github.com/user-attachments/assets/b90aaeec-2dd6-4c05-bb84-fb999788b505

### Expected behavior
Behaviour and results should be the same through UI and API both

**Comment by prernaadev01** [comment]
@ilyozzz Can you please provide us more details on this such as API requests and the responses, you are currently getting it. As the current logic is that the UI and API should give same behavior. So, seems like there should be some issue with API requests so if you can share the requests, it would be of great help. Thanks
