### ISSUE TITLE
CI/CD for Repo Badges

### ISSUE THREAD

**Issue by danielnorkin** [hashgraph/guardian#40]
### Requirements

Configure CI/CD for adding the following badges:
- Test
- Build
- Release
- <and other appropriate badges>.

This issue depends on the implementation of #4 

### DOD

- A Technical Decision needs be made around which badges are appropriate.
- The ticket is considered done when the acceptance criteria is fulfilled.

### Acceptance Criteria

- Appropriate badges are added and displayed.

**Comment by danielnorkin** [comment]
@sergmetelin - What CI/CD tool should we use for this issue?

**Comment by sergmetelin** [comment]
Github Actions probably unless there's a requirement to use something else?

**Comment by envisionblockchainpm** [comment]
We will use GitHub Actions for this as per @sergmetelin . This should take one or two days to create the Config.

**Comment by anvabr** [comment]
Changed the definition of this issue to focus on badges only

**Comment by envisionblockchainpm** [comment]
This has been completed and the Badge is coming up this is the proof that its working: https://github.com/hashgraph/guardian/pull/134
