### ISSUE TITLE
Inability to Re-Access Tool Editing Interface

### ISSUE THREAD

**Issue by xj85770** [hashgraph/guardian#4050]
### Problem description

After creating a tool within the Managed Guardian Service (MGS) platform, users are unable to navigate back to the tool's editing interface once they have navigated away. This issue occurs specifically when attempting to upload a schema or make further adjustments to the tool. This limitation is significantly hindering workflow efficiency, as users cannot make necessary changes or updates to their tools after the initial setup.

### Expected behavior

Users should be able to navigate back to the tool's editing interface from any point within the platform. This would allow for continuous editing, schema uploads, and adjustments to the tool.

### Video

Please refer to the attached video that demonstrates the issue as it occurs during tool creation and subsequent attempts to navigate back to the editing interface.

https://github.com/user-attachments/assets/5c964d8c-e438-44a1-811f-d1d1df1fd400

**Comment by prernaadev01** [comment]
@xj85770  Thank you so much for raising this bug. We are looking at this ticket and will keep you posted once we have solution and fix for it.

**Comment by xj85770** [comment]
@prernaadev01 Thanks!
