### ISSUE TITLE
Support lists in schemas

### ISSUE THREAD

**Issue by danielnorkin** [hashgraph/guardian#41]
### Requirements

As a Guardian user, I want to be able to use lists within schemas.

### DOD

- Schema definition language includes provision for defining lists.
- Unit tests exists for the schema and the API.
- Schema documentation is updated to include description of lists functionality.

### Acceptance Criteria
- A user can define lists in schemas and specify whether they are multi-select or not.

**Comment by envisionblockchainpm** [comment]
This is a UX issue for the Front End. @danielnorkin  is getting together with the UX Designer to see when he can start. This is a pretty simple ask, it just needs to be developed out.

**Comment by envisionblockchainpm** [comment]
As of today, this is almost done, we just need to apply these changes. @mendelenvisionblockchain Please let us know status.
