### ISSUE TITLE
Ensure CODEOWNERS is properly defined on Guardian Repository

### ISSUE THREAD

**Issue by rbarkerSL** [hashgraph/guardian#4272]
**Description**:

Need to verify CODEOWNER file is valid and up-to-date. It should have the envision team on as codeowners for src/ and /**test**/ directories.

**Comment by mishomihov00** [comment]
@rbarkerSL When you refer to the envision team, do you mean this team - https://github.com/orgs/hashgraph/teams/envision-blockchain-hedera ?

**Comment by rbarkerSL** [comment]
@mishomihov00 I most surely do!

@gregscullard the envision-blockchain-hedera team currently has no members... Can you add a helpdesk ticket with the appropriate github handles?
