### ISSUE TITLE
Forms data validation

### ISSUE THREAD

**Issue by danielnorkin** [hashgraph/guardian#43]
**Requirements:**
As a Guardian user, I should be notified if the data entered is not in the appropriate format as defined in the schema.

**Definition of Done:** 
- The implementation passed the acceptance criteria.
- There is a test schema in the codebase which contains all supported types with which 'Forms Validation' functionality can be tested.
- There is a document which describes the currently supported types and their possible values.

**Acceptance Criteria:**
- Validation of the form data should match that of schema type definition, i.e. the same values that would be rejected by the schema type definition as invalid should be rejected by the form validation logic, and vice versa the same values that are considered valid by the schema type definition should pass form validation.
- When a user inputed a malformed value into a field, a clear and user-friendly message for the user showing which input field contains invalid value and why.

**Comment by envisionblockchainpm** [comment]
This is completely a UI issues. First of all we need to make a UI design for this issues, and after that, we can implement it. We need more context around this ticket. We need types of fields, types of validation, in some type of documentation. Two things we want to expose are GEO and TIME RANGE. Everything else, we will have to be a little bit tighter such as metric ton, etc. List types of fields that are possible and the type of validation for these fields. Ideally, this would be in the Repo, make this information as public as possible.

**Comment by envisionblockchainpm** [comment]
Adding this ticket as a Dependency for the SFDC Project.

**Comment by envisionblockchainpm** [comment]
As of now, we need time to apply the UX Design because this was just provided yesterday, Thursday the 23rd.
