### ISSUE TITLE
did issue in Policy

### ISSUE THREAD

**Issue by justin-atwell** [hashgraph/guardian#431]
### Problem description

When you export a policy with registered users the did is placed in the policy json. When you import that policy, there is a json format error saying you cannot import a policy that contains ".". I believe this is data that should be escaped for bson or whatever mongo uses.

### Expected behavior
My policy is imported without error

**Comment by prernaadev01** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Guardian-618c27c08661c0001461263a/issues/hashgraph/guardian/431?planning-poker) with ZenHub @anvabr

**Comment by prernaadev01** [comment]
This issue was completed on February 17th and closed on March 14th.
