### ISSUE TITLE
Guardian Thread blocking

### ISSUE THREAD

**Issue by prernaadev01** [hashgraph/guardian#432]
### Problem description
The VP generation when it contains a lot of VC's blocks the thread, as node is singe thread event.

### Step to reproduce
As the thread is blocked it cannot respond to the healthcheck
Cluster management kills the container / pod / task

### Solution 
Options suggested:
1. Shift to Worker Pool
2. Queue Implementation 
3. Fire and forget

### Expected behavior
VP generation should be 100% async

**Comment by anvabr** [comment]
This ticket will be done by the community, Guardian core team will assist them, and review the PR etc

**Comment by voycey** [comment]
This has actually been superseded by the replacement of the replacement of the message queue - this is in progress and we will send a PR when it is completed.
