### ISSUE TITLE
Attaching reference to PDD via programmatically built monitoring report

### ISSUE THREAD

**Issue by gautamp8** [hashgraph/guardian#4364]
**Context**

Usually external monitoring data is sent by an installer or sensor with a new DID. Technically, `ref` variable becomes the DID of the new device.

In metered energy policy, there is a need to prepare monitoring report schema programmatically by stitching daily usage data(sent by sensors) with PDD data originally entered by project proponent.

There's two approaches provided in the policy for creating a monitoring report.

1) Using Add Report button and filling the form manually

<img width="1369" alt="image" src="https://github.com/user-attachments/assets/ada45592-4b75-41ea-a23a-0cc9aa7c3d4d">

In this case a `ref` unique to the project gets attached to it automatically(notice the UUID row ). 

<img width="1395" alt="image" src="https://github.com/user-attachments/assets/c9dc7b0b-9e32-4f3b-bc42-6b0da27ef490">

2) External data comes in, goes via a calculate block to generate a monitoring report. In this case, `ref` is automatically added as DID. This MR doesn't have reference to existing project. 

<img width="1369" alt="image" src="https://github.com/user-attachments/assets/40cb1915-eb84-488a-862b-d5c836fdd4c1">

I need to figure out a way to keep the programmatically generated monitoring report via option 2 to retain original PDD reference.

**Attachments**
- Policy file, recording file and a vc_generator.py script are within the zip
[Archive.zip](https://github.com/user-attachments/files/17650264/Archive.zip)

Python script needs the path to .config file downloaded. It's not possible to send nested schema VCs with MRV sender component, hence script is needed.

**Comment by prernaadev01** [comment]
@gautamp8 Can you please confirm if the above comment works for you and if it is can we close this ticket?

**Comment by gautamp8** [comment]
@prernaadev01 It is certainly helpful, can you give me couple days before closing please? In final phases of testing, will share any blockers if I have.

**Comment by gautamp8** [comment]
We improved the structure of policy to reflect your suggestions @anvabr. Here's the updated policy file - 
[MECD 431_V1.2-latest.policy.zip](https://github.com/user-attachments/files/17872428/MECD.431_V1.2-latest.policy.zip)

I see that trust chain doesn't reflect the end to end process still when going via automatic monitoring report route. Project UUID is updated to DID. MRV config uses the same DID. MR generated uses a new UUID. Could you please check and give inputs on what might be missing?

**Comment by prernaadev01** [comment]
@gautamp8 Thank you so much for sharing the policy file. Our team is currently looking at this and will get back to you asap.

**Comment by gautamp8** [comment]
@anvabr Thanks a ton, really appreciate the efforts. When you say you made the changes, you've published it or you missed adding the updated policy file for me?

**Comment by prernaadev01** [comment]
@gautamp8 Can you please let me know if the above policy works?

**Comment by prernaadev01** [comment]
@gautamp8 Just wanted to follow up on the status of this issue.

**Comment by gautamp8** [comment]
@prernaadev01 Apologies for the delay, have had couple of busy weeks. We can close this issue, I'm in process of testing the new policy, will publish it soon. Appreciate the support!
