### ISSUE TITLE
UIUX design for data validation in forms

### ISSUE THREAD

**Issue by danielnorkin** [hashgraph/guardian#44]
**Requirements**
As a user of the Guardian reference implementation demo, I want to be able to see the changes made to Issue #43 on the User Interface.

**Pre-requisite**
Remediation of Blocker Tickets. Mendel to Address.

**Definition of Done**
TBD 

**Acceptance Criteria:**
TBD

**Comment by envisionblockchainpm** [comment]
We will assign this later once the Front End Developer starts this week.

**Comment by envisionblockchainpm** [comment]
Allocating 8 Story Points and assigning to Mendel

**Comment by envisionblockchainpm** [comment]
This needs to be updated with Requirements from @anvabr , but adding to this Sprint. We need to gather requirements on what form types we need to validate here. Only after that, this can be done by @mendelenvisionblockchain or another Designer. It can then be implemented by another developer.

**Comment by envisionblockchainpm** [comment]
This was provided by @mendelenvisionblockchain yesterday and @Pyatakov has confirmed this ticket is complete from the designs Mendel sent. Closing.
