### ISSUE TITLE
Guardian-service exits at first boot when Hedera fails to respond for > 2 minutes

### ISSUE THREAD

**Issue by anvabr** [hashgraph/guardian#453]
### Problem description
When the guardian is being run for the first time it may exit (unhandled exception) when Hedera fails to 'reply' for 2 minutes.

### Step to reproduce
Steps to reproduce the behaviour:
1. Rebuilt Guardian from scratch
2. Run it
3. Attempt to immediately run through the demo script (using the http://localhost:3002/ UI).
4. See error and the exit of the guardian-service

### Expected behaviour
Guardian does not fail and continues to operate, any errors and timeouts are handled gracefully.

### Work arounds
Wait for 2 minutes and then attempt to restart manually.

**Comment by simvalery** [comment]
https://github.com/hashgraph/guardian/pull/641

**Comment by prernaadev01** [comment]
This ticket was QA approved and closed on March 28th
