### ISSUE TITLE
Unexisting Block Error 

### ISSUE THREAD

**Issue by prernaadev01** [hashgraph/guardian#465]
### Problem description
When we are importing the policy, logging as installer and filling the form for approval. Once Root Authority approves, we are getting error.

### Step to reproduce
1. Import a Policy
2. Login as Installer
3. Fill the form and submit for approval
4. Approve it as Root Authority
5. Once approved, we are getting saying "Unexisting Block"

### Expected behavior
1. Once Root authority approves, we should be able to see Policy Blocks without any error
2. Please change the error from "Unexisting Block" to "Block does not exist"

**Comment by anvabr** [comment]
[policy_1645134524100.zip](https://github.com/hashgraph/guardian/files/8097341/policy_1645134524100.zip)

**Comment by Stepan-Kirjakov** [comment]
@prernaadev01 
1. Block 'Download Remediator Config Button' has no permissions.
2. Error text changed

**Comment by Stepan-Kirjakov** [comment]
Maybe I should change the error to 'Insufficient permissions'?

**Comment by prernaadev01** [comment]
> Maybe I should change the error to 'Insufficient permissions'?

Yes. Please

**Comment by Stepan-Kirjakov** [comment]
@prernaadev01 
I changed the text to `'${tag}': Insufficient permissions`
For example "'Download Config Button': Insufficient permissions"

**Comment by prernaadev01** [comment]
Thank you @Stepan-Kirjakov

**Comment by prernaadev01** [comment]
Even when we are changing permissions on the button, i see all 8 children blocks but they're all null. @Stepan-Kirjakov

**Comment by prernaadev01** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Guardian-618c27c08661c0001461263a/issues/hashgraph/guardian/465?planning-poker) with ZenHub @anvabr
