### ISSUE TITLE
Make sure you don't ignore package lock files.

### ISSUE THREAD

**Issue by mattsmithies** [hashgraph/guardian#467]
![Image from iOS](https://user-images.githubusercontent.com/6974163/154726384-71d7664f-dfea-4d5d-8524-26aa2c1b24e6.jpg)

**Comment by mattsmithies** [comment]
Please.

**Comment by mattsmithies** [comment]
In all seriousness though, without a package-lock file, this will increase the risk of inconsistency issues for different local developer configurations.

**Comment by mattsmithies** [comment]
I'm just going to leave another comment here to highlight and bump that we haven't received any feedback nor has any task has been assigned to anyone, this task is **absolutely vital** for local development consistency.

This task will take less than five minutes to complete, however, we are unable to complete it on our end and provide a pull request as we have not developed the system (we don't know what the exact packages are to build) and are unable to have a consistent foundational base for which to develop against.

_I have known software organizations to restructure contributors for not adding such a basic step in projects._

I would highly recommend for the Guardian product/engineering team take a look at this walkthrough of package-lock files and understand how critical they are https://nodejs.dev/learn/the-package-lock-json-file

cc: @sergmetelin @justin-atwell

**Comment by dubgeis** [comment]
@prernaadev01 @danielnorkin Please address this asap, thanks.

**Comment by prernaadev01** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Guardian-618c27c08661c0001461263a/issues/hashgraph/guardian/467?planning-poker) with ZenHub @anvabr
