### ISSUE TITLE
UIUX design for custom roles in policies

### ISSUE THREAD

**Issue by danielnorkin** [hashgraph/guardian#52]
**Requirements**
As a user of the Guardian, I would like to see the changes on the frontend that are related to issue #51. 

**Pre-requisite**
Front End UX?

**Definition of Done**
Front End UX QA Demo

**Acceptance Criteria:**
Unsure?? @anvabr ?

**Comment by envisionblockchainpm** [comment]
At @mendelenvisionblockchain adding this to the Sprint 3 and assigning to you.

**Comment by envisionblockchainpm** [comment]
We will issue 52 out Removing Policy Engine to the next Sprint or two.

**Comment by envisionblockchainpm** [comment]
As per todays Grooming Session, we will  wait to do this ticket until we are doing the UX for the WHOLE Policy Engine.
