### ISSUE TITLE
Filtering by Schema is missing

### ISSUE THREAD

**Issue by prernaadev01** [hashgraph/guardian#531]
### Problem description
Currently, we are having Filter by Entity Type, but we need to have filter by schema.

### Step to reproduce
I add my burner grid and uncheck “default selected” I still see ALL types of “collection (approve)” (installer, crusher and burner entities). It has a schema tag in it but doesn't seem to be honoring it.

### Expected behavior
Talking about the fact that for INSTALLER, CRUSHER and BURNER there should be different approve buttons in 1 column (if we are talking about 1 grid).

We need to have different approve buttons for each schema.

**Comment by niklatkin** [comment]
QA PASSED. The feature works as expected.

**Comment by prernaadev01** [comment]
This issue was completed and QA approved on Mar 15th
