### ISSUE TITLE
Mitigation Credits Research

### ISSUE THREAD

**Issue by danielnorkin** [hashgraph/guardian#54]
### Problem description
Non-offset GHG reductions, such as those resulting from corporate energy conservation or efficiency initiatives, are currently not supported in Guardian. These are generally measured as the delta between the baseline and current emission levels, there are no concepts/tools which would allow Guardian users to account for these, and link/reflect them on the Environmental scorecards ( #1017).

### Requirements
Introduce the ability to mint Mitigation Asset Type tokens as the result of the calculation of the diff between planned (and reported on the Environmental) and actual results of the calculations based on the MRV data for a reporting period. This would likely require:

- New type of blocks in the policy definition language specifying 'target' numbers.
- Policy Engine ability to mint different types of tokens depending on the conditions
- Needs to be linked with #1017 logic

### Definition of done

- Policy engine supports Mitigation Tokens
- Sample policy is created demonstrating workflow
- Documentation for the API and the sample policy

### Acceptance criteria
A company is able to automatically account for mitigation efforts through MRV data processing by the policy engine resulting in the production of mitigation tokens.

**Comment by envisionblockchainpm** [comment]
Should be assigned to Max to how we report to Mitigation. Would have to have CET's first to how we know how to deal at a business level.

**Comment by sergmetelin** [comment]
@anvabr @envisionblockchainpm is there an update on this?

**Comment by anvabr** [comment]
@sergmetelin as per the comment above this ticket is waiting for @Mpinnola's input

**Comment by Mpinnola** [comment]
I assume "mitigation" in this context refers to non-offset GHG reductions, such as those resulting from corporate energy conservation or efficiency initiatives? In general, this would be measured as the delta between the baseline and current emission levels. These reductions aren't typically traded/tradable. For example, if a Company A reduces (aka "mitigates") their emissions by 100 tCO2e compared to their baseline, but they only needed to reduce by 50 tCO2e to meet their goals, they can't just sell the other 50 to Company B, or at least that's not really how it works now. 

Just putting a random thought out there;  if we did want to enable such a transaction, perhaps instead of Company A selling Company B 50 "mitigation credits" they could instead accept 50 CETs from Company B at a certain price (i.e. Company B could essentially pay Company A to take 50 CETs off their hands). So maybe if an offsets trades at ~10$, maybe CETs can be traded at ~-10$. This would allow the monetization of mitigation without the need for a new asset type. 

I could use a bit if clarification of what a "mitigation asset" refers to, but if I am understanding clearly, I and not sure of the feasibility/utility/necessity of this new asset type.

**Comment by anvabr** [comment]
@Mpinnola In the blockchain space there are limited tools to represent real world concepts, chiefly a single tool - tokens.  Everything needs to be modelled as a token (of some type), to enable accounting/tracking of mitigation results they need to be recorded as tokens. They don't need to be tradable, although I think it would be prudent to leave the capability for this for the future.

**Comment by Mpinnola** [comment]
@anvabr 

One existing system that may be able to guide us here is the cap-and-trade system, which already provides a mechanism to incentivize mitigation. While this is a regulatory mechanism, perhaps it can guide us in the concept of a voluntary “mitigation credit.” 

Under Canada’s cap-and-trade system, subjected entities are given emissions limits. If measured emissions are below the limit, “surplus credits” are issued. If emissions are above the limit, the entity must make a payment, or purchase and retire surplus credits or offsets. In similar systems, entities are issued carbon allowances that represent their limit. After a compliance period, any surplus of allowances can be sold, or they can purchase additional allowances if they emit above their limit. 

https://www.canada.ca/en/environment-climate-change/services/climate-change/pricing-pollution-how-it-will-work/output-based-pricing-system/overview.html  
 
I think what we need to determine is; do these systems make the concept of a “mitigation credit” obsolete, especially if an entity is already subject to a cap-and-trade program? Effectively, a surplus credit or an allowance credit may achieve the same function as a hypothetical “mitigation credit” in the sense that mitigation can be measured as the delta between a limit (or baseline or target) and actual emissions, and rewarded via the issuance of surplus credits, or the actual surplus of allowance credits. 

My next question is, why not focus on tokenizing surplus credits, or allowances, and then perhaps facilitate voluntary cap-and-trade systems? In a voluntary system, the limit could be a voluntary target or a baseline. If emissions are lower that the limit, mitigation has occurred, and credits can be issued. If emissions are over the limit, credits must be purchased. We could call them “mitigation credits” if we want, but effectively this is a voluntary cap-and-trade system. 

Let’s model an example based on the concept of “surplus credits” 

- Company A has a baseline or target of 1,000 mtCO2e 
- Emissions are measured via CETs  
- At the end of 2022 they have a balance of 800 mtCO2e 
- 200 “mitigation credits” are issued
- Company B has a baseline or target of 1,000 mtCO2e
- At the end of 2022 they have a balance of 1,200 mtCO2e
- They are required to offset 200 mtCO2e or they can perhaps purchase 200 “mitigation credits” from company A

Or we can model the “allowance credit” system
 

- Company A has a baseline or target of 1,000 mtCO2e 
- 1,000 allowances are issued at the beginning of the monitoring period
- At the end of the at the end of 2022 they have a balance of 800 CETs
- 800 tokenized allowances are burned, and they have 200 left, that can be sold 

Both are modeling cap-and-trade systems, both can be tracked with tokenized credits and emissions, both measure and incentivize mitigation. In addition, there are existing systems and standards that can guide us. If we don’t want to go this path, the next step should be to identify what functions the hypothetical “mitigation credits’ would serve that are not captured by tokenizing a cap-and-trade system.
