### ISSUE TITLE
Not possible to filter logs by attributes

### ISSUE THREAD

**Issue by niklatkin** [hashgraph/guardian#544]
### Step to reproduce
1. Go to 'Admin Panel.'
2. Navigate to the 'Logs.'
3. Insert attributes in the Attributes filed
4. Click on the 'Apply filters'

### Expected behavior
A user should be able to filter logs by attributes.

### Screenshots
See a video attached for clarification
https://images.zenhubusercontent.com/416030891/57be59ec-3d45-49e5-8e3c-fcfdc2a1cf78/admin_bug.mov

**Comment by prernaadev01** [comment]
This ticket was QA approved and closed on March 18th.
