### ISSUE TITLE
Admin Panel - Clear all filters functionality

### ISSUE THREAD

**Issue by niklatkin** [hashgraph/guardian#545]
### Problem description
It would be nice to implement functionality where a user can clear filters/set filters to default.

### Requirements
Exact requirement for the product - what needs to be done?

### Definition of done
A user can clear applied filters in the Admin panel by clicking the 'Clear Filters' button.

### Acceptance criteria
When a user with access to the Admin panel navigates to the Admin panel,
Then a user sees clickable the 'Clear filters' button.
Then a user enters any values into the filters fields and clicks on the 'Clear filters' button.
And a user should be able to clear all values entered before.

**Comment by niklatkin** [comment]
We have to change the label for the clear button
Let's make it 'Clear filters' instead of 'X'
The functionality works as expected.

![Screen Shot 2022-03-18 at 9.52.50 AM.png](https://images.zenhubusercontent.com/6228d071c8dbf81a23fe7447/5e697f5c-da2f-4d50-a2f3-0924b49fb200)

**Comment by niklatkin** [comment]
QA PASSED. It works as expected.

**Comment by prernaadev01** [comment]
This ticket was closed on March 18th
