### ISSUE TITLE
Import from IPFS causes error: Failed to load resource: the server responded with a status of 500 (Internal Server Error)

### ISSUE THREAD

**Issue by niklatkin** [hashgraph/guardian#548]
### Problem description
This issue happens when a user tries to import a policy from IPFS, providing a timestamp

### Step to reproduce
1. Go to the 'Policy' tab
2. Click on the 'Import' button
3. Select 'Import from IPFS' option
4. Enter hedera message timestamp (_1644847114.111298000_)
5. Click the 'Ok' button
6. See the 500 error that occurred

### Expected behavior
A user should be able to import a policy from IPFS without errors

### Screenshots
![Screen Shot 2022-03-18 at 8.13.23 AM.png](https://images.zenhubusercontent.com/6228d071c8dbf81a23fe7447/ddab65f4-2cea-4b25-8bf9-49b8fdea9f81)

**Comment by niklatkin** [comment]
[Uploading... Screen Recording 2022-03-18 at 8.06.47 AM.mov]

**Comment by niklatkin** [comment]
[Uploading... Screen Recording 2022-03-18 at 8.06.47 AM.mov]

**Comment by niklatkin** [comment]
QA PASSED. It works as expected.

**Comment by prernaadev01** [comment]
This ticket was closed on March 18th
