### ISSUE TITLE
Retirement process for assets MVP

### ISSUE THREAD

**Issue by danielnorkin** [hashgraph/guardian#55]
### Problem definition
As a user of the Guardian, I would like a retirement process for ESG assets (see #290 for matched). This is the other end of the token lifecycle, opposite to the 'creation' process, which also needs its own ruleset.

Assets may include:

- Carbon Emission Tokens (CET)
- Carbon Removal Units (CRU)
- Core Carbon Principals (CCP)

### Requirements

- Expand Policy definition language to have provisions to specify rules for retirement (not only for creation as it is now) of sustainability tokens
- Implement smart contract functionality enforcing these rules.

### DOD
- Acceptance criteria fulfilled
- Documentation updated accordingly

### Acceptance criteria
- Policy creators are able to specify rules for the retirement of assets, including for 'matched' assets as per #290
- Hedera enforces these rules for all created tokens with or without the instance of the Guardian present through a retirement smart contract associated with each policy.
- Guardian has an API to retire tokens

**Comment by envisionblockchainpm** [comment]
What type of emission is it? For instance, this CET is offsetable by this type of assets? How do we know if things are being measured the same. The Token Burn is separate from the asset. WE need to think through the use case of this. We need to draw some diagrams on how this would work. As far as Documentation we ned to keep Max looped in on. We need to know how somebody NETS? Can I Net out my assets and what type of reporting do I need? Can I produce a report of every single transaction prior to this burn? Could be a MINT, could be a TRANSFER? Max will bring the sustainability for How We Net, will feed into how we technically design an elegant solutions. Whoever is involved should be in the IWA Meetings. Assigned to Andrey

**Comment by Mpinnola** [comment]
Test comment

**Comment by Mpinnola** [comment]
Here are some notes from the Interwork Alliance that may help add some clarity: 

- Core Carbon Principle tokens (CCP) represent credits that can be used to offset or decrease (netting) a reporting organization’s effective emissions for the reporting period  
- When an offset is applied to reduce actual emissions, the offset is spent and cannot be reused or sold and generates a lower effective emissions balance 
-  CCPs can be held for their value or spent to offset reported emissions. When an owner offsets a CCP, it is applied towards an ESG Goal or another target and is retired or burned and cannot be offset again
- Effective balances for a period can be calculated from the ledger based on the actual CET transferred or issued in the period for the organization minus the CCPs or CRUs it spends in the period 

In other words (if I understand this correctly): 

When a CRU or a CCP token is spent/retired/burned, it is effectively retired to offset an effective CET balance. As such, the CRU/CCP tokens cannot be used again. However, the CET and CCP assets and their associated history, data, and info still exist, they will just be marked as spent, disabled from being reused, and the effective emission balance will be reduced. For example, let’s say in a given monitoring period, Company A generates 10 CETs, and spends/burns 8 CCPs, their scorecard will show 10 CETs and 8 spent/retired CCPs, and an effective balance of 2 CETs. That being said, could the retirement/ netting process be as simple as setting CCP assets as "spent," disabling their reuse, and calculating an effective emission balance for the scorecard?  

Please let me know if this helps and if I am on the right track to addressing this issue.

**Comment by Mpinnola** [comment]
For some extra context, there three token types: 

CET: This is an emission token, one CET token represents 1 mtCO2e emitted by a company (or organization, etc.). A demand side user of the Guardian receives and possess CETs based on MRV data and policy schemas. 

CCP: This is an offset token generated by projects that remove CO2 from the atmosphere. One CCP represents 1 mtCO2e removed from the atmosphere. CCPs are generated and possessed by supply side users of the Guardian (such as Verra Project Proponents). 

CRU:  This is like a CCP, but an NFT. 

CCPs and CRUs can be traded, held for their value, or burned/retired to offset CETs. Demand side users who generate and possess a balance of CETs can purchase CCPs or CRUs from supply side users or a registry. Once in possession of both CETs and offset tokens (CRUs and/or CCPs), they can retire or burn CCPs and/or CRUs to offset CETs and lower their effective balance of CETs. Initiating a burn can be performed by smart contracts. 

CETs can be effectively cancelled out by CCPs or CRUs at a one-to-one ratio. Effective balances for a period can be calculated from the ledger based on the actual CET transferred or issued in the period for the organization minus the CCPs or CRUs it burns or retires in the period.  

More information on the token types and their functionality can be found in the IWA paper attached.
 
In short, as a demand side user of the Guardian, my main objective is to exhibit and verify the lowering of my net GHG emissions. This value will effectively equal my CETs generated minus retired/burned CCPs and CRUs within a certain timeframe.
 
One thing we need to decide is if the cancelling out process should involve burning or retiring. For example, with retiring, a ledger would show something like 100 CETs and 80 retired CCPs and an effective balance of 20 CETs. In this scenario, the 80 retired CCPs still exist, but in a retired state where they can no longer be used to offset CETs. If we are to burn the CETs and CCPs, the ledger will simply show a balance of 20 CETs. 80 CETs and 80 CRUs would be burned and effectively cease to exist. I believe @dubgeis indicated he prefers a burn. However, the IWA paper seems to indicate retirement. @dubgeis, would you like to chime in on this?
[Voluntary_Ecological_Markets_Overview_Revised.pdf](https://github.com/hashgraph/guardian/files/7884505/Voluntary_Ecological_Markets_Overview_Revised.pdf)

**Comment by envisionblockchainpm** [comment]
Andrey is updating the approach to this ticket prior to the AWA Meeting @anvabr

**Comment by Mpinnola** [comment]
I have done some research into retirement processes and matched asset compatibility and included some of my findings in the deck attached. I look forward to discussing. Please let me know if you have any questions. 
[Issue 55_Retirement Process and Matched Asset Compatibility_1-31-22.pptx](https://github.com/hashgraph/guardian/files/7983724/Issue.55_Retirement.Process.and.Matched.Asset.Compatibility_1-31-22.pptx)

**Comment by anvabr** [comment]
I refined the ticket, it is now ready to be picked up by development. I removed non-MVP features like smart contract-based retirement of tokens - this is covered by #235
