### ISSUE TITLE
Wrong Signatories in the Policy Block of Verra Red Trustchain 

### ISSUE THREAD

**Issue by prernaadev01** [hashgraph/guardian#550]
### Problem description
All the Parties in TrustChain is RootAuthority.

### Step to reproduce
1. Go to 'TrustChain'
2. Scroll down to chain
3. We have all the tags
4. In each of the tag, we have Parties, which should be either RootAuthority or VVB or Project Proponent.

### Expected behavior
We need to display Parties depending on action, who have completed that particular action of the tag.

### Screenshots
![image.png](https://images.zenhubusercontent.com/60fc4cffabe39716f47ed7fd/861cd78c-f870-4f82-befa-33d2469d01c8)

**Comment by prernaadev01** [comment]
This ticket will be closed by March 25th. This ticket is related with #565, once this is closed, even #565 will be closed.

**Comment by niklatkin** [comment]
QA PASSED. The feature works as expected.

**Comment by prernaadev01** [comment]
This ticket was closed on March 28th
