### ISSUE TITLE
Policy Validation

### ISSUE THREAD

**Issue by danielnorkin** [hashgraph/guardian#56]
**Requirements**
As a user of the Guardian, prior to publishing a Policy Workflow Execution Instance, I would like to validate requirements such as schemas, tokens, etc. If there is an issue, I will need to know what requirement the issue is related to and how to fix it. 

**Pre-requisite**
Reference Ticket? BLOCKER Ticket?

**Definition of Done**
Reference Ticket? BLOCKER Ticket?

**Acceptance Criteria:**
Reference Ticket? BLOCKER Ticket?

**Comment by envisionblockchainpm** [comment]
We had a Demo of this already. It can be closed.
