### ISSUE TITLE
Creation of list of Heavy loading tasks

### ISSUE THREAD

**Issue by prernaadev01** [hashgraph/guardian#564]
### Problem description
Lots of tasks are dependent on each other

### Requirements
Need to create a list of heavy loading tasks to be made.

### Definition of done
Complete list of tasks to be made

### Acceptance criteria
What are the criteria by which we determine if the issue has been resolved?

**Comment by prernaadev01** [comment]
@anvabr @Pyatakov @simvalery Need a detailed discussion on finalizing the list.

**Comment by simvalery** [comment]
`Create new token (TokenCreateTransaction)
newToken
guardian-service/src/hedera-modules/hedera-sdk-helper.ts:68

Get balance account (AccountBalanceQuery)
balance
guardian-service/src/hedera-modules/hedera-sdk-helper.ts:130

Get associate tokens and balance (AccountInfoQuery)
accountInfo
guardian-service/src/hedera-modules/hedera-sdk-helper.ts:146

Minting fungible token allows you to increase the total supply of the token (TokenMintTransaction)
mint
guardian-service/src/hedera-modules/hedera-sdk-helper.ts:325

Minting a non-fungible token creates an NFT with its unique metadata for the class of NFTs defined by the token ID (TokenMintTransaction)
mintNFT
guardian-service/src/hedera-modules/hedera-sdk-helper.ts:357

Wipes the provided amount of fungible tokens from the specified account (TokenWipeTransaction)
wipe
guardian-service/src/hedera-modules/hedera-sdk-helper.ts:393

Transfer tokens from some accounts to other accounts (TransferTransaction)
transfer
guardian-service/src/hedera-modules/hedera-sdk-helper.ts:428

Transfer non-fungible token from some accounts to other accounts (TransferTransaction)
transferNFT
guardian-service/src/hedera-modules/hedera-sdk-helper.ts:463

mintProcessing
guardian-service/src/policy-engine/blocks/retirement-block.ts:141

retirementProcessing
guardian-service/src/policy-engine/blocks/mint-block.ts:168`

**Comment by prernaadev01** [comment]
@simvalery @anvabr @Pyatakov To have a discussion on the above list.

**Comment by prernaadev01** [comment]
This ticket was QA approved and closed on March 30th
