### ISSUE TITLE
Filters by date range in Admin panel does not work correctly

### ISSUE THREAD

**Issue by niklatkin** [hashgraph/guardian#567]
### Problem description
This issue happens when a user tries to filter logs with date range and uses the end date as today's date.
For example, we have logs with timestamp _2022-03-22T16:36:29.768Z_, but when a user selects the start date 2022-03-21 and the end date 2022-03-22 applies filters, the result is empty. However, the logs appear if a user picks today +1 day in the end date range.

### Step to reproduce
1. Go to the 'Admin' tab
2. Click on the 'Logs' tab
3. Select date range filter and pick the start and end dates where the end date is "today" date
4. Click on the 'Apply filters' button

### Expected behavior
A user should see logs related to the user of the dates provided

### Screenshots
https://images.zenhubusercontent.com/416030891/1e5c319c-303e-43db-b748-de0c375668b0/screen_recording_2022_03_22_at_12_21_54_pm.mov

**Comment by prernaadev01** [comment]
This ticket was QA approved and closed on March 24th
