### ISSUE TITLE
Policy Validation UIUX design

### ISSUE THREAD

**Issue by danielnorkin** [hashgraph/guardian#57]
**Requirements**
As a user of the reference implementation version of the Guardian, prior to publishing a Policy Workflow Execution Instance, I would like to see the validated requirements such as schemas, tokens, etc. If there is an issue, I will want to see the issue and see how to fix it. This is related to issue #56.

**Pre-requisite**
BRD. IA Diagram?

**Definition of Done**
BRD. IA Diagram?

**Acceptance Criteria:**
BRD. IA Digram?

**Comment by envisionblockchainpm** [comment]
We will leave this one until Front End Developer starts.

**Comment by envisionblockchainpm** [comment]
@mendelenvisionblockchain sent over the Design yesterday and it was approved by the Dev Team.
