### ISSUE TITLE
Not possible to filter by message in logs if search input contains special characters 

### ISSUE THREAD

**Issue by niklatkin** [hashgraph/guardian#575]
### Problem description
This issue happens when a user filters logs by messages and input contains special characters. For example - ")".

### Step to reproduce
1. Go to the 'Logs.'
2. In the message input field, insert value contains a special character "("
3. Click on the 'Apply filters' button

### Expected behavior
A user should see a message in a result (if a message/s with provided text exists)

### Screenshots
See video in attachment for clarification
https://images.zenhubusercontent.com/416030891/d2594396-d61d-49af-90b8-463d1f94d8db/screen_recording_2022_03_23_at_10_40_17_am.mov

**Comment by artembuslaev** [comment]
Also added detail column with detailed log information, changed search by attributes logic, hide long messages/attributes.

**Comment by prernaadev01** [comment]
This ticket was QA approved on 24th March. Closed on 25th March
