### ISSUE TITLE
Remove console logs in API Gateway

### ISSUE THREAD

**Issue by prernaadev01** [hashgraph/guardian#576]
### Problem description
We have found console logs in some of the API gateways.

### Step to reproduce
There are console logs in the following APIs:

1. api-gateway/src/api/service/profile.ts
2. api-gateway/src/helpers/ipfs.ts

### Expected behavior
Need to remove all the console logs in the specified APIs

**Comment by simvalery** [comment]
https://github.com/hashgraph/guardian/pull/580

**Comment by niklatkin** [comment]
QA PASSED.

**Comment by prernaadev01** [comment]
This ticket was QA passed and close on March 24th.
