### ISSUE TITLE
Method renaming

### ISSUE THREAD

**Issue by prernaadev01** [hashgraph/guardian#578]
### Problem description
There is a method called "registerPingPongAnswers", which needs to be renamed.

### Step to reproduce
To check all places where this method is used.

### Expected behavior
Need to check all the places where method , "registerPingPongAnswers"  is used and then rename the method everywhere

**Comment by simvalery** [comment]
https://github.com/hashgraph/guardian/pull/581

**Comment by niklatkin** [comment]
QA PASSED.

**Comment by prernaadev01** [comment]
This ticket was closed on March 24th.
