### ISSUE TITLE
UI config missing attribute for interfacedocumentssourceblock 

### ISSUE THREAD

**Issue by samuraitruong** [hashgraph/guardian#579]
### Problem description
According to document here - https://docs.hedera.com/guardian/available-policy-workflow-blocks/interfacedocumentssourceblock
this Block require the UI to have configure for filter option 
<img width="942" alt="image" src="https://user-images.githubusercontent.com/1183138/159861640-8c2d76b9-f7ce-40c2-b3ce-f374dbd47830.png">

in v1.2.0, filter option sis missing from UI  we still able to configure using JSON

Also, I register the new device (sensor) from GUI or API it was successful. I can see VC documents was created in database but the Grid doesn't show any item?

### Expected behaviour
- UI have to have option for update filter
-  Not sure why the grid not display data, API also return empty data array

### Screenshots
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/1183138/159861919-1572e2b5-8f57-4aa5-8b00-a6fe16c1f20c.png">

<img width="1776" alt="image" src="https://user-images.githubusercontent.com/1183138/159862602-954e888f-ab5d-4399-8da5-6c6db714b169.png">

<img width="1729" alt="image" src="https://user-images.githubusercontent.com/1183138/159862786-a334795d-3956-4623-8feb-f7fe72b7e6d6.png">

Note: The Inverter status is `CREATE`

**Comment by prernaadev01** [comment]
This ticket is related to #610. 
As we have solved #610, this ticket is also solved.
