### ISSUE TITLE
Tutorials: For Custom Policies

### ISSUE THREAD

**Issue by sergmetelin** [hashgraph/guardian#6]
As a User of the Guardian, I would like to create my own policy workflow execution instance, using Step by Step Guidance. Currently there isn't one available, there fore this needs to be created. 

Definition of Done: Step by Step Guidance is published in the Repo in either a README, OR a GitBook. 

Consider using https://www.gitbook.com/ or Wiki or something similar to publish documentation

**Comment by envisionblockchainpm** [comment]
@sergmetelin I am investigating GitBook to follow up and will add to REPOSITORY Epic.

**Comment by envisionblockchainpm** [comment]
We really  need to focus on writing a Tutorial on how to implement a Custom Policy. The Tutorial @sergmetelin  is asking for is the technical documentation on how to create a custom policy.

**Comment by envisionblockchainpm** [comment]
Next Step is for our team to look at the iRec Policy, and then reproduce it with us recording.

**Comment by envisionblockchainpm** [comment]
The next step for this ticket, is that this week Stepan will record himself recording the coding of an iRec

**Comment by envisionblockchainpm** [comment]
The team has started the Glossary, its not completed. Team will put a big push next week.

**Comment by envisionblockchainpm** [comment]
Andrey is going to be working on this this week.
