### ISSUE TITLE
Server is not available

### ISSUE THREAD

**Issue by prernaadev01** [hashgraph/guardian#609]
### Problem description
Users are facing 505 error when pulling the latest code from Main.

### Step to reproduce
Clone the main branch
setup the code and run it locally.

### Expected behavior
Application to run without anyServer errors.

### Screenshots
![image.png](https://images.zenhubusercontent.com/60fc4cffabe39716f47ed7fd/e4ed5e27-414b-4fdf-af08-c68de670830f)

**Comment by samuraitruong** [comment]
From what I test, it will available after awhile , 30 sec most of the time. But sometime it will not started especially when your laptop is heavy load, it will happen

**Comment by prernaadev01** [comment]
@niklatkin Please confirm if we are getting this issue as we have resolved #612

**Comment by whimzyLive** [comment]
@niklatkin @prernaadev01 

I am also facing this issue when running via docker. Seems related.
Shouldn't the rest of the service containers be waiting for the Guardian service before they are started?

Although, when I run the services manually it works.

**Comment by prernaadev01** [comment]
@whimzyLive We have solved this issue and will be making live in our upcoming release. 
We would suggest you to wait for the completion of the Initialization process. We have also updated our docs. Please check. Thanks
