### ISSUE TITLE
InterfaceDocumentsSourceBlock required documentssourceaddonblock to display data 

### ISSUE THREAD

**Issue by samuraitruong** [hashgraph/guardian#610]
### Problem description
InterfaceDocumentsSourceBlock  will not display data if it doesnt have child element documentssourceaddonblock
It seem problem at the code here - https://github.com/hashgraph/guardian/blob/main/guardian-service/src/policy-engine/helpers/decorators/data-source-block.ts#L34
this issue affect both UI and API
### Step to reproduce
- create the sensor_grid without child documentssourceaddonblock
- add few sensor from UI
- the grid show only head no data row
- update InterfaceDocumentsSourceBlock to include the block of documentssourceaddonblock
- refresh the grid, data show up
- 
### Expected behaviour
If that is by design -> we need update document and sameple irec policy
If that is the bug, probably need to update the logic to getSource here - https://github.com/hashgraph/guardian/blob/main/guardian-service/src/policy-engine/helpers/decorators/data-source-block.ts#L34

**Comment by prernaadev01** [comment]
We have updated the documentation. Will be making it live in our next release.
