### ISSUE TITLE
UI/UX to be improved to show Policy and Schema relationship

### ISSUE THREAD

**Issue by prernaadev01** [hashgraph/guardian#616]
### Problem description
There is no clear UI/UX to show relationship between Policy and Schema

### Requirements
We need to improve UX to show clear relationship with Policy and Schema.
Meaning, how many Schemas are present in each Policy.

### Definition of done
Improvement of UI/UX

### Acceptance criteria
UI is completed to show clear relationship with Policy and Schema

**Comment by niklatkin** [comment]
QA PASSED.
https://images.zenhubusercontent.com/416030891/e47585b4-8c4d-4a23-bbcd-aa3f06b8906d/screen_recording_2022_04_15_at_12_51_24_pm.mov

**Comment by prernaadev01** [comment]
This ticket was closed on April 15th.
