### ISSUE TITLE
Token Authenticity

### ISSUE THREAD

**Issue by prernaadev01** [hashgraph/guardian#647]
### Problem description
Token authentication and authorization to specific role is missing

### Requirements
We need to show complete relationship between the token and user roles such as Root Authority/ Project Proponent etc.

### Definition of done
When we are able to show complete token authenticity and relationship to the user.

### Acceptance criteria
Successful Token Authenticity

**Comment by anvabr** [comment]
This ticket is complete in the course of the Policies/Topics mapping work. The flow for validation of the token is as follows:
Sequence

1. Begin at the NFT token instance (it has a serial number)
2. Confirm the token identifier is appropriate for this Guardian
3. Find tx that minted the NFT
4. Examine mint tx memo - value is an HCS tx timestamp
5. Query mirror for the HCS message tx - it represents the creation and logging of an VP(VC(MRV))
6. Confirm the topic identifier is valid for this Guardian
7. Examine message contents, grab URL param - it is an IPFS CID
8. Resolve CID to retrieve VP(VC(MRV))
9. Examine VP(VC(MRV)
    - Confirm it maps to the appropriate tokenID (this is logically a challenge that the VP represents a response to)
    - Verify signatures, retrieve DIDs as necessary
    - Confirm the MRV data meets the criteria of the policy
