### ISSUE TITLE
UI - Calendar date picker selector goes out of calendar bounds

### ISSUE THREAD

**Issue by niklatkin** [hashgraph/guardian#650]
### Problem description
This issue happens when a user manually add a date, creating a new project under a policy

### Step to reproduce
1. Go to 'Create a new project' under Verra Redd Policy
2. Scroll down to 'Monitoring Period'
3. Click on the calendar icon to pick a date
4. See the UI issue happens

### Expected behavior
The date picker selector should not go over a calendar bounds

### Screenshots
![Screen Shot 2022-03-28 at 1.42.15 PM.png](https://images.zenhubusercontent.com/6228d071c8dbf81a23fe7447/0ce02f06-fe56-42f8-ab01-46ab2ecfed21)
![Screen Shot 2022-03-28 at 12.27.34 PM.png](https://images.zenhubusercontent.com/6228d071c8dbf81a23fe7447/2caff023-f3df-44d2-b44e-4bce88fa595f)

**Comment by niklatkin** [comment]
QA PASSED

**Comment by prernaadev01** [comment]
Ticket closed on April 5th
