### ISSUE TITLE
Removal of some functions from Block

### ISSUE THREAD

**Issue by prernaadev01** [hashgraph/guardian#656]
### Problem description
As we are now implementing Topics and mapping process , we have some functions in existing Blocks, which are not needed.

### Requirements
We need to remove all the functions from the existing Blocks, which are not needed after implementing Topics and mapping.

### Definition of done
Functionality needs to be working after functions are removed.

### Acceptance criteria
Expected functionality to be working.

**Comment by simvalery** [comment]
https://github.com/hashgraph/guardian/pull/682

**Comment by prernaadev01** [comment]
This ticket is closed on April 5th
