### ISSUE TITLE
Policy roles are missing in Demo Admin Panel Dropdown

### ISSUE THREAD

**Issue by prernaadev01** [hashgraph/guardian#659]
### Problem description
When launching Guardian, we are not able to see roles in the top right menu in Login and after login screens.

### Step to reproduce
1. Launch the application
2. Need to add Roles column in the Policy table of Users.
3. Need to add Policy name in Tokens Tab

After Login screens:
Show only the roles of the imported Policies.

### Expected behavior
Roles column in Policies table and Policy name in Tokens Tab

**Comment by niklatkin** [comment]
I see roles in the Admin tab, but a user should refresh a browser to see everything correctly. See screen recording in attachments for clarification. 

https://images.zenhubusercontent.com/416030891/fef9361b-d1c4-4055-b021-04921914b371/screen_recording_2022_04_06_at_2_38_23_pm.mov

**Comment by prernaadev01** [comment]
QA Passed on April 7th and Ticket closed on April 11th.
