### ISSUE TITLE
Description is incorrect

### ISSUE THREAD

**Issue by prernaadev01** [hashgraph/guardian#671]
### Problem description
When we Import new iREC policy, under review we are getting "test" in Description.

### Step to reproduce
1. Go to Policies
2. Click on Import
3. Import new iREC Policy.zip and click on preview
4. Under Preview, we see "Test" as Description. But in the json it has iREC Description.

### Expected behavior
Frontend description should match the json description

### Screenshots
![image.png](https://images.zenhubusercontent.com/60fc4cffabe39716f47ed7fd/1a73e5c6-93bf-4bdf-8da2-42b13f3dc6e4)

**Comment by niklatkin** [comment]
QA PASSED.

**Comment by prernaadev01** [comment]
Ticket closed on April 5th
