### ISSUE TITLE
Documentation of manual building of every component to be updated

### ISSUE THREAD

**Issue by prernaadev01** [hashgraph/guardian#679]
### Problem description
When we are following the instructions described in the documentation for manually building the components, we are not able to run without using the docker.

### Step to reproduce
1. Go to https://docs.hedera.com/guardian/getting-started/getting-started/installation
2. We have manually building process in the document
3. When we follow the process, we are not able to run the application without the docker.
4. Need to correct the process in documentation : ReadMe and Gitbook

### Expected behavior
I should be able to build every component manually successfully by following the step by step process of documentation.

**Comment by niklatkin** [comment]
The error I see when manually run installation proccess
`src/api/file.service.ts:1:44 - error TS2307: Cannot find module 'interfaces' or its corresponding type declarations.

1 import { CommonSettings, MessageAPI } from 'interfaces';
                                             ~~~~~~~~~~~~

src/api/file.service.ts:8:24 - error TS2307: Cannot find module 'logger-helper' or its corresponding type declarations.

8 import { Logger } from 'logger-helper';
                         ~~~~~~~~~~~~~~~

src/app.ts:2:24 - error TS2307: Cannot find module 'logger-helper' or its corresponding type declarations.

2 import { Logger } from 'logger-helper';
                         ~~~~~~~~~~~~~~~`

**Comment by niklatkin** [comment]
QA PASSED. The feature works as expected.

**Comment by prernaadev01** [comment]
This ticket is closed on April 5th
