### ISSUE TITLE
Update documentation for updated block names

### ISSUE THREAD

**Issue by dlin-me** [hashgraph/guardian#692]
### Problem description

1. block names were updated in the latest releases. e.g. 'requestVcDocument' => 'requestVcDocumentBlock'
2. However, some docs are still using old block names, for example:
   -  Steps in [Getting Started with the Policy Workflows](https://docs.hedera.com/guardian/policy-workflow-creation-using-the-guardian-user-interface/getting-started-with-the-policy-workflows)
   - `Demo Artifacts/irec-policy-config.txt`

Please change the block names otherwise these examples are not working

### Step to reproduce
1. Create a policy manually based on the given example: `Demo Artifacts/irec-policy-config.txt`
2. Try publishing this newly created policy.
3. See error: 'unknow block 'requestVcDocument` 

### Expected behavior
All examples updated to work.

**Comment by niklatkin** [comment]
Docs need to be updated in https://github.com/hashgraph/guardian/tree/develop/Demo%20Artifacts

![Screen Shot 2022-04-12 at 12.07.06 PM.png](https://images.zenhubusercontent.com/6228d071c8dbf81a23fe7447/38513c1f-7019-4d15-8d53-cf66e4c63065)

**Comment by niklatkin** [comment]
QA Failed - An error occurred when a user validates the Policy and an error occurred when a user published a policy
Docs from here https://github.com/hashgraph/guardian/blob/develop/Demo%20Artifacts/irec-policy-config.txt need to be updated

See the video attached here: https://drive.google.com/file/d/1uaUU-tLQYIl0vTZeCHu3wSGeYxLJQIQJ/view?usp=sharing

![Screen Shot 2022-04-12 at 2.40.51 PM.png](https://images.zenhubusercontent.com/6228d071c8dbf81a23fe7447/55e4200e-15be-414e-afeb-eb54fe22c6bb)

**Comment by niklatkin** [comment]
QA PASSED.
