### ISSUE TITLE
Need vc-modules published on npm

### ISSUE THREAD

**Issue by samuraitruong** [hashgraph/guardian#707]
### Problem description
We are deploy guardian stack on separate code base with out API backend. which we have the logic to generate the mrv (mrv-sender custom). The code in our custom mvr sender is not on the same place with guardian repo  but we need access to vc-modules (use for vc-document loader). it is better to have guardian vc-modules published on npm so we dont need to copy and maintain the code

Hope that make sense?

### Requirements
vc-modules  should  published on npm

### Definition of done
How do we know we've fully dealt with it?

### Acceptance criteria
What are the criteria by which we determine if the issue has been resolved?

**Comment by prernaadev01** [comment]
@samuraitruong Just an FYI, in our next release, as we are changing in the structure, we have removed vc-modules from the code, but we would like to know your comments if you really need it after. Thanks

**Comment by samuraitruong** [comment]
@prernaadev01  make sure you update document accordingly so I can depreciated the vc-modules on our code. Hope the change also update the sample mrv-sender . Thanks

**Comment by prernaadev01** [comment]
We have updated the documentation and also tested it. Thank you for checking with us.

**Comment by prernaadev01** [comment]
We have updated the documentation and also tested it. Thank you for checking with us.
