### ISSUE TITLE
Typos in iREC Policy 

### ISSUE THREAD

**Issue by prernaadev01** [hashgraph/guardian#712]
### Problem description
Need to correct typos in iREC Policy file:
1. In policy file it should be "wait_for_approve" under registrant workflow.
2. the next block has `save_application_status(appove) which should be approve.
3. "Block_73" should be named "token_history_source_filter"
4. "mit_token" should be "mint_token"
5. "sign_issue_by_isuer" should be "sign_issue_by_issuer"
6. "devace_report(approved)" should be "device_report(approved)"
7. "devace_report(submit)" should be "device_report(submit)"
8. "sign_farm_by_isuer" should be "sign_farm_by_issuer"

### Expected behavior
All Typos to be corrected.

**Comment by artembuslaev** [comment]
new timestamp of policy: "1650012656.610312000"

**Comment by prernaadev01** [comment]
@niklatkin Need to check old iREC policy.

**Comment by artembuslaev** [comment]
new actual timestamp of policy: 1650030274.139448151

**Comment by niklatkin** [comment]
QA Failed. Proof attached below

![Screen Shot 2022-04-15 at 10.50.42 AM.png](https://images.zenhubusercontent.com/6228d071c8dbf81a23fe7447/5160176f-70e1-47db-9672-95abe475c12f)
![Screen Shot 2022-04-15 at 10.47.36 AM.png](https://images.zenhubusercontent.com/6228d071c8dbf81a23fe7447/52bd93d4-2d6a-4ce3-8866-7e87a5e3969d)![Screen Shot 2022-04-15 at 10.36.16 AM.png](https://images.zenhubusercontent.com/6228d071c8dbf81a23fe7447/d489c1de-f91c-4b88-9572-82d776122041)

**Comment by artembuslaev** [comment]
New iRec Policy timestamp: 1650282926.728623821
New iRec Policy 2 timestamp: 1650283305.363066755

**Comment by prernaadev01** [comment]
This ticket was closed on April 18th
