### ISSUE TITLE
Typos in Verra Redd policy

### ISSUE THREAD

**Issue by niklatkin** [hashgraph/guardian#726]
### Problem description
We have typos in the Verra Redd policy

### Expected behavior
We have `wait_fo_approve` instead of `wait_for_approve.`
Plus, we have some names for blocks like `Block47` I do not know if we should have names like that or now, but based on the work for ticket #712, I expect that we need to fix typos for Verra Redd as well.

### Screenshots
![Screen Shot 2022-04-15 at 4.41.32 PM.png](https://images.zenhubusercontent.com/6228d071c8dbf81a23fe7447/c4b331d6-70fd-44f6-bc8a-d858f44a8ee2)

**Comment by artembuslaev** [comment]
new REDD policy timestamp: 1650299796.080140000

**Comment by prernaadev01** [comment]
This ticket was QA passed and closed on April 18th
