### ISSUE TITLE
Infinity spinning  when cancel policy import

### ISSUE THREAD

**Issue by niklatkin** [hashgraph/guardian#738]
### Problem description
A user sees infinity spinning when a user imports a policy from a local machine but then cancels uploading

### Step to reproduce
1. Go to 'Policies'
2. Click on the 'Import' button
3. Click on the 'Import from file' button
4. Click on the Cancel when the directory with files appears

### Expected behavior
A user should be navigated back to the Policies without seeing infinity spinning in the import modal

### Screenshots
![Screen Shot 2022-04-18 at 7.02.52 AM.png](https://images.zenhubusercontent.com/6228d071c8dbf81a23fe7447/74a587d3-c306-4ab5-b417-9f29ce117c65)

**Comment by prernaadev01** [comment]
@artembuslaev Needs to do more research to replicate and solve this issue.

**Comment by prernaadev01** [comment]
This ticket was closed on April 21st.
