### ISSUE TITLE
Release docker to docker hub or public github docker registry

### ISSUE THREAD

**Issue by samuraitruong** [hashgraph/guardian#741]
### Problem description
When we run guardian in production, we dont want to rebuild all the docker image and push to our private registry

### Requirements
- Each release of guardian, the docker image should be built by CI on tag and publish to docker hub/github registry

### Acceptance criteria
What are the criteria by which we determine if the issue has been resolved?

**Comment by prernaadev01** [comment]
We need to create a Docker account to store all the docker images. We are working on it.

**Comment by samuraitruong** [comment]
Thanks @prernaadev01, We can using github docker registry if you have any problem with docker hub however, i believe that you will have no issue at

**Comment by voycey** [comment]
@prernaadev01 just as an FYI - I am in the process of writing a full stack Terraform setup for this - as part of this I am pulling down the hashgraph/guardian repo, building all of the Docker images and pushing them to Docker Hub (that the user needs to provide credentials for).
If Envision can publish these docker images it will simplify things but there needs to be strict adherence to versions that match the Git release tags so we can specify a version number

**Comment by sergmetelin** [comment]
Is it ok if we publish to GCR? @voycey @samuraitruong

**Comment by voycey** [comment]
Yep as long as they are public we are fine with wherever!
________________________________

**Comment by simvalery** [comment]
https://github.com/hashgraph/guardian/pull/868

**Comment by derek-meeco** [comment]
Is the image available in the public registry?

On 3 May, @sergmetelin mentioned "GCR", which i interpret as "Github Container Registry" https://ghcr.io
On 12 May, @prernaadev01 says "GCP", which i interpret as "Google Cloud Platform" , which has a container registry (https://cloud.google.com/container-registry), but not public as far as i know?

**Comment by voycey** [comment]
> Is there a container image available in a public registry?
> 
> On 3 May, @sergmetelin mentioned "GCR", which i interpret as "Github Container Registry" https://ghcr.io On 12 May, @prernaadev01 says "GCP", which i interpret as "Google Cloud Platform" , which has a container registry (https://cloud.google.com/container-registry), but not public as far as i know?

https://console.cloud.google.com/gcr/images/hedera-registry/GLOBAL/ << its all here :)
