### ISSUE TITLE
[API] - Undocumented response when import new policy from zip file

### ISSUE THREAD

**Issue by niklatkin** [hashgraph/guardian#769]
### Problem description
In our API documentation, when a user sends `policies/import/file` the response should be `201` but currently request returns `200.`

### Expected behavior
We should either change the documentation or fix the response from the  API request

### Screenshots
![Screen Shot 2022-04-20 at 10.33.00 AM.png](https://images.zenhubusercontent.com/6228d071c8dbf81a23fe7447/c00d9cbe-21fc-4cdf-b7d1-cbac153a5ab8)

**Comment by artembuslaev** [comment]
Documentation should be double checked for changes:
Changes in code:
POST /schemas/{topicId}/import/message 200 -> 201
POST /schemas/{topicId}/import/file 200 -> 201
POST /policies 200 -> 201
POST /policies/import/message 200 -> 201
POST /policies/import/file 200 -> 201
POST /external 201 -> 200
POST /ipfs/add 200 -> 201

Changes in swagger yaml: 
POST /policies 200 -> 201
POST /external 201 -> 200
POST /ipfs/add 200 -> 201

**Comment by niklatkin** [comment]
- [ POST /schemas/{topicId}/import/message 200 -> 201 
POST /schemas/{topicId}/import/file 200 -> 201
POST /policies 200 -> 201
POST /policies/import/message 200 -> 201
POST /policies/import/file 200 -> 201
POST /external 201 -> 200
POST /ipfs/add 200 -> 201

Changes in swagger yaml: 
POST /policies 200 -> 201
POST /external 201 -> 200
POST /ipfs/add 200 -> 201]

**Comment by prernaadev01** [comment]
Documentation also updated. Ticket is closed on April 26th
