### ISSUE TITLE
Develop GET /policies Automation Test Case

### ISSUE THREAD

**Issue by niklatkin** [hashgraph/guardian#772]
### Problem description
As a QA engineer, I need to develop an automation test case for the `GET` request for policies.

### Requirements
1. Develop a test case for the `GET` request for /policies
2. Develop a test case for the `GET` request for /policies/{policyId}

### Definition of done
Test Case created, and a correct response returned with `HTTP` code 200 and w. response body.

**Comment by prernaadev01** [comment]
This ticket is closed on April 26th.
