### ISSUE TITLE
ERROR TypeError: window.showOpenFilePicker is not a function appears in Firefox console

### ISSUE THREAD

**Issue by niklatkin** [hashgraph/guardian#776]
### Problem description
The issue happens when a user imports policy using Firefox browser

### Step to reproduce
1. Click on the 'Import policy'
2. Click on 'Import from file'

### Expected behavior
A user should be able to upload policy using local files

### Actual behavior 
In the browser console I see the error message `ERROR TypeError: window.showOpenFilePicker is not a function`

### Screenshots
![Screen Shot 2022-04-22 at 1.03.26 AM.png](https://images.zenhubusercontent.com/6228d071c8dbf81a23fe7447/9f7f3241-69eb-468e-886f-72950ab8d26f)

**Comment by prernaadev01** [comment]
To solve this issue, we have finalised to implement drag and drop functionality for importing a File

**Comment by prernaadev01** [comment]
This ticket is QA passed and closed on April 26th
