### ISSUE TITLE
Cannot submit generated profile

### ISSUE THREAD

**Issue by niklatkin** [hashgraph/guardian#777]
### Problem description
The issue happens when a user generates a new profile. A user sees RootAuthority, but it looks like a user needs to select it again (See a video in the attachments for clarification)

### Step to reproduce
1. Go to the 'Profile' tab
2. See RootAuthority is selected
3. Click on the 'Generate' button
4.`OPERATOR ID` and `OPERATOR KEY` generated but submit button is not clickable

### Expected behavior
Since a user sees RootAuthority selected, it does not make sense to set it again to be able to submit a profile.

### Screenshots
https://images.zenhubusercontent.com/416030891/2d59dd6e-f3d6-49e9-bca4-7b3b520dd553/screen_recording_2022_04_22_at_4_14_34_am.mov

**Comment by prernaadev01** [comment]
This ticket is QA passed and closed on April 26th
