### ISSUE TITLE
Should we use jest?

### ISSUE THREAD

**Issue by samuraitruong** [hashgraph/guardian#801]
### Problem description
ATM, the test is using mocha frameworks, I would like to open consideration to moving to Jest + TS-Jest . At the moment, the test in guardian-service is not very good written (my opinion) it is still using pure js and import file from 'dist' to run the test

### Requirements
 - setup jest and ts-jest
 - migrate js to. ts for test file inside guardian-service test
 - setup jest module alias so the test can run on the source ts file instead of dist
 - add more test for other share components such as interface

Please note: if you don't want to using jest, mocha still able to do all above requirements but it not easy as Jest.

### Definition of done
How do we know we've fully dealt with it?

### Acceptance criteria
What are the criteria by which we determine if the issue has been resolved?

**Comment by niklatkin** [comment]
@samuraitruong Thanks for your suggestion. We are currently implementing the https://www.cypress.io/ framework for our e2e tests. We are planning to use this framework for API and UI tests. Implementation of JEST is not in our roadmap. But you are right current API tests are not written well and need to be cleaned.
