### ISSUE TITLE
Policy Workflow Enhancements

### ISSUE THREAD

**Issue by prernaadev01** [hashgraph/guardian#839]
### Problem description
There are some enhancements in the Policy Workflow such as Undo/Redo of the action, Copying the block

### Requirements
1) Copy Paste blocks
2) Undo Redo and Restore latest state in policy configuration
3) "Parallel block" - analog of step block, but runAction on child blocks is called independently and parallel.

### Definition of done
Completion and tested of all the above enhancements.

### Acceptance criteria
Enhancements features to be working 100%

**Comment by artembuslaev** [comment]
Also added displaing available nested block based on char:
![image](https://user-images.githubusercontent.com/68849616/167837497-90908d3a-07d4-4c34-93cc-a37d83df0ee4.png)

**Comment by artembuslaev** [comment]
There was no need for "Parallel" and "Go To" blocks, since the switch block covers this functionality.
