### ISSUE TITLE
Community Standards

### ISSUE THREAD

**Issue by dubgeis** [hashgraph/guardian#841]

**Comment by dubgeis** [comment]
@anvabr can we work on a section of standards with:

1) A proposal of how to define standards 

2) Technical Proposals for the Guardian at a lower level

3) Message Standards (Discoverability)

4) Policy Standards (Implementations by RAs)

@sergmetelin @justin-atwell let me know if I'm missing anything here.

**Comment by prernaadev01** [comment]
This Epic is taken by IEU team. Reference Epic : Community Standards RFP
