### ISSUE TITLE
URLs and Ports to be documented

### ISSUE THREAD

**Issue by prernaadev01** [hashgraph/guardian#845]
### Problem description
Currently, we do not have all the Ports and URLs being documented in Gitbook to be more clear and precise.

### Requirements
Need to add all the ports and URLs, used in Guardian such as MRV - sender, localhost API docs, etc.

### Definition of done
Adding all the details in Gitbook

### Acceptance criteria
When documentation is made live

**Comment by artembuslaev** [comment]
In Docker:
	WEB-INTERFACE: 	localhost:3000
	API_GATEWAY: 	localhost:3000/api/v1/
	MRV_SENDER: 	localhost:3000/mrv-sender/
	TOPIC_VIEWER: 	localhost:3000/topic-viewer/
	API_DOCS: 		localhost:3000/api-docs/v1/
	
Not In Docker:
	WEB-INTERFACE: 	localhost:4200/
	API_GATEWAY: 	localhost:3002/
	MRV_SENDER: 	localhost:3005/
	TOPIC_VIEWER: 	localhost:3006/
	API_DOCS: 		localhost:3001/
