### ISSUE TITLE
Schema creation set field name as `field{index}`

### ISSUE THREAD

**Issue by samuraitruong** [hashgraph/guardian#884]
### Problem description
Schema creation set field name as `field{index}`

For example :

```
 "field1": {
      "title": "installerName",
      "description": "installerName",
      "readOnly": false,
      "$comment": "{\"term\": \"field1\", \"@id\": \"https://www.schema.org/text\"}",
      "type": "string"
    },

```
### Requirements
the fieldName should automatically set to title. If it has any disallow character we can remove it)
Expect 
```

 "installerName": {
      "title": "installerName",
      "description": "installerName",
      "readOnly": false,
      "$comment": "{\"term\": \"installerName\", \"@id\": \"https://www.schema.org/text\"}",
      "type": "string"
    },

and 
also the required property

 "required": [
    "@context",
    "type",
    "installerId",
    "field1",
    "field2",
    "field3",
    "field4",
    "field7",
    "field8",
    "field9",
    "field19",
    "field20",
    "policyId"
  ],

```

### Definition of done
How do we know we've fully dealt with it?

### Acceptance criteria
What are the criteria by which we determine if the issue has been resolved?

**Comment by anvabr** [comment]
@samuraitruong it's a neat idea, but some effort is involved in making this change. I can see that perhaps this cosmetically makes the json a little more human-readable, are there other benefits beyond that?

**Comment by samuraitruong** [comment]
@anvabr in our solution, we not using the UI to create schema instead we use api that is working fine, however, to get json for API we use the guardian UI to design our schema then copy json into our source code. but when you copy all the field name got messy up.  Also. when you have the correct json created by API, but open it using UI and the propertyname also changed.

**Comment by samuraitruong** [comment]
Also I noticed there no front-end option that allow enter description for the field

**Comment by anvabr** [comment]
> Also I noticed there no front-end option that allow enter description for the field

In the front-end the words from the 'Name' go into the description field.

**Comment by anvabr** [comment]
> @anvabr in our solution, we not using the UI to create schema instead we use api that is working fine, however, to get json for API we use the guardian UI to design our schema then copy json into our source code. but when you copy all the field name got messy up. Also. when you have the correct json created by API, but open it using UI and the propertyname also changed.

I see your issue, however I don't feel this is a sufficiently generic use-case to outweigh problems that this solution would bring. Here are my thoughts:

- We can't really auto-generate the field name on the basis of the title because title is free text - can have spaces and various characters, can be very long etc. Yes we can truncate, remove  undesirable symbols etc but then the resulting string would be more random than before. As a general case this would become more confusing, so it's a no-go.
- We could allow the user to specify the field name, however this would introduce another field on the form which does not have any real meaning to the user and only relevant to those looking at the code. Not a good UX practice, on the balance also a no-go.

Unless there is some other reason why would do this I am inclined to close this.

**Comment by voycey** [comment]
I wasn't on the call last night when this was discussed, I think this adds some important context to the schema.

Introducing Schema lookup to this is going to add additional complexity, UUID would solve the uniqueness, but it lacks the context of the description. 

We are thinking ahead to how we look at on-chain traceability for this - having to further look-up what a UUID is or field3 is increasingly adds complexity to an already complex (and time expensive) process

**Comment by samuraitruong** [comment]
@anvabr you don't need to generate anything, just need to respect the input that user enter' As user I name my field is 'abc' and I enter the name is 'abc' so you can use 'abc' as the field name instead of 'field1'

In my VC document, I want my data is 

```
{
.... 
abc: 'value'
}

```

Not below 

```
{
.... 
field1: 'value'
}

```

We can not use `uuid`, because some standard will required the fieldName to be specific. for example 'CO2Emissions' not field1 or field2

**Comment by prernaadev01** [comment]
@samuraitruong After deep discussion with the team, we have come with below solution :
We can have an Advanced tab , where user can change the default key of each field.
We have also discussed this solution in today's community meeting, all the community members gave us a go ahead.
But as this was pointed by Tymlez team, we just wanted to check if it is ok for you?
![image](https://user-images.githubusercontent.com/79293833/173917487-ce2b25d4-dca1-4e32-b70b-038a2cd67c76.png)

**Comment by samuraitruong** [comment]
> @samuraitruong After deep discussion with the team, we have come with below solution : We can have an Advanced tab , where user can change the default key of each field. We have also discussed this solution in today's community meeting, all the community members gave us a go ahead. But as this was pointed by Tymlez team, we just wanted to check if it is ok for you? ![image](https://user-images.githubusercontent.com/79293833/173917487-ce2b25d4-dca1-4e32-b70b-038a2cd67c76.png)

@prernaadev01 thanks, that should works, I think we can default to advanced (my personal view is we only need advanced mode)

I think we need 3 field
- fieldName (which is fieldKey)
- fieldTitle (file Name)
- and description

**Comment by anvabr** [comment]
@samuraitruong thank you for your comments, we very much appreciate your input. However in the interest of broader community we will keep 'simplified' as the default. Also reviewing your suggestions for the fieldName and fieldTitle, I feel it can lead to confusion in the broader community and less technical users. As per community review and 'ok' of the original design we are going to keep fieldKey and fieldName as described on the screenshots.
