### ISSUE TITLE
504 Gateway Timeout error when trying to View TrustChain from Token Histroy of REDD Demo Policy

### ISSUE THREAD

**Issue by bdub** [hashgraph/guardian#912]
### Problem description

After following the VERRA REDD Demo instructions to the point of minting... As the Verra RootAuthority  clicking the [Mint] button produces Gateway Timeout error, but upon page refresh the token does get minted. 

Then, under the Token History tab, when clicking the [View TrustChain] for that token mint, the page spins for about 30 sec then throws a 504 Gateway Timeout error. 

### Step to reproduce

1. Following the [Verra Redd+ Demo Guide](https://docs.hedera.com/guardian/demo-guide/verra-redd+-demo-guide) to point 15.
2. (at instruction 16) click [Mint] -> page times out, but mint is successful.
3. (as per instruction 17) navigate to the Token History tab, click on View TrustChain 

### Expected behavior
Should see Presentation View of Trust Chain

### Screenshots

![image](https://user-images.githubusercontent.com/185901/169858211-557630b4-767f-4506-babc-fee712df4671.png)

**Comment by samuraitruong** [comment]
this bug maybe related to https://github.com/hashgraph/guardian/pull/946
