### ISSUE TITLE
Error when using ref schema

### ISSUE THREAD

**Issue by samuraitruong** [hashgraph/guardian#916]
### Problem description
I have a policy `A` which using Schema S1, inside schema S1 I use reference to schema S2 and S3

When I publish policy A, only schema 'S' got published but not S2 & S3

The policy still get published successfully however, the VC form will error when we use this schema on policy

### Step to reproduce
see above

### Expected behavior
- Reference schema should get published along with parent schema before publish the policy

### Screenshots
![image](https://user-images.githubusercontent.com/1183138/170171528-6b36e62f-094a-4ba2-aeba-5a1c33c98f05.png)

For example in this screenshot, my Installer using Address and Person but they are not published. 

when you view the published installer schema , below  are example of the ref field

```    
"registeredOfficeAddress": {
            "title": "registeredOfficeAddress",
            "description": "registeredOfficeAddress",
            "readOnly": false,
            "$comment": "{\"term\": \"registeredOfficeAddress\", \"@id\": \"https://ipfs.io/ipfs/bafkreibxtwbyjehm2gtiezilkwxasyz4bpmfsfjrxtzd6cnhpqiun76wwi#1d735afd-0dbb-4fc6-819b-c7de3c469d45\"}",
            "$ref": "#73cb6280-fab6-4e83-b0a2-b68c04f8931d"
        }
```

Below are error : 

![image](https://user-images.githubusercontent.com/1183138/170171844-6fab86f7-b2b6-4bff-ba87-acc4bc35a210.png)

### Updated:
After I manual updated and publish schema , the schema view look correct but when update policy I still get this error

```
can't resolve reference #65e5df79-012f-487b-9323-fdeeb0053e1c&1.0.0 from id #4efdf0dd-f5cd-41fe-94fc-c31b381ff4c6&1.0.0

```

Tried to look in the code but could not find where the error throw.

example schema : https://ipfs.io/ipfs/bafkreiggwsr5yiq2fu32q2fgalzrd26j2wzhrbjz6tsmjjqbxyieyhc4sa#65e5df79-012f-487b-9323-fdeeb0053e1c&1.0.0

**Comment by prernaadev01** [comment]
@samuraitruong We have reviewed this bug and found that it is because of the invalid Schema. The example Schema don't have defs array in it. Please check the attached screenshot.

Your Schema Shared:
![image](https://user-images.githubusercontent.com/79293833/170731161-eee99acd-ff61-43cc-8271-12ab45f58d62.png)

Please check the example JSON format:
 {
    "$id": "#4f2ad28f-93b5-4e0b-b0b8-c3c643ef4ba5&1.0.0",
    "$comment": "{\"term\": \"4f2ad28f-93b5-4e0b-b0b8-c3c643ef4ba5&1.0.0\", \"@id\": \"https://ipfs.io/ipfs/bafkreifp6kpp3cisp42rgn73wlq6ubl7rlivcyfomxpqjsggattnyshoou#4f2ad28f-93b5-4e0b-b0b8-c3c643ef4ba5&1.0.0\"}",
    "title": "I-REC Registrant & Participant App",
    "description": "I-REC Registrant & Participant App",
    "type": "object",
    "properties": {
        "@context": {
            "oneOf": [
                {
                    "type": "string"
                },
                {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            ],
            "readOnly": true
        },
        "type": {
            "oneOf": [
                {
                    "type": "string"
                },
                {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            ],
            "readOnly": true
        },
        "id": {
            "type": "string",
            "readOnly": true
        },
        "field0": {
            "title": "Date",
            "description": "Date",
            "readOnly": false,
            "$comment": "{\"term\": \"field0\", \"@id\": \"https://www.schema.org/text\"}",
            "type": "string",
            "format": "date"
        },
        "field1": {
            "title": "Applicant Details",
            "description": "Applicant Details",
            "readOnly": false,
            "$comment": "{\"term\": \"field1\", \"@id\": \"https://ipfs.io/ipfs/bafkreihxsmllnneje7shxerizd4nmjj3mg4mexaskixzkskqpdsksyd6qe#1ad6e7eb-f3df-453e-ac50-5e02f707955c\"}",
            "$ref": "#1ad6e7eb-f3df-453e-ac50-5e02f707955c"
        },
        "field2": {
            "title": "Primary Contact Details",
            "description": "Primary Contact Details",
            "readOnly": false,
            "$comment": "{\"term\": \"field2\", \"@id\": \"https://ipfs.io/ipfs/bafkreihxsmllnneje7shxerizd4nmjj3mg4mexaskixzkskqpdsksyd6qe#d396eee9-1ce1-4e34-9695-b91cb094bcc4\"}",
            "$ref": "#d396eee9-1ce1-4e34-9695-b91cb094bcc4"
        },
        "field3": {
            "title": "Lead User Details\t",
            "description": "Lead User Details\t",
            "readOnly": false,
            "$comment": "{\"term\": \"field3\", \"@id\": \"https://ipfs.io/ipfs/bafkreihxsmllnneje7shxerizd4nmjj3mg4mexaskixzkskqpdsksyd6qe#4a8719f0-b9c5-45cf-8a20-b30c3a493aef\"}",
            "$ref": "#4a8719f0-b9c5-45cf-8a20-b30c3a493aef"
        },
        "policyId": {
            "title": "policyId",
            "description": "policyId",
            "readOnly": true,
            "$comment": "{\"term\": \"policyId\", \"@id\": \"https://www.schema.org/text\"}",
            "type": "string"
        },
        "ref": {
            "title": "ref",
            "description": "ref",
            "readOnly": true,
            "$comment": "{\"term\": \"ref\", \"@id\": \"https://www.schema.org/text\"}",
            "type": "string"
        }
    },
    "required": [
        "@context",
        "type",
        "field1",
        "field2",
        "field3",
        "policyId"
    ],
    "additionalProperties": false,
    "$defs": {
        "#1ad6e7eb-f3df-453e-ac50-5e02f707955c": {
            "$id": "#1ad6e7eb-f3df-453e-ac50-5e02f707955c",
            "$comment": "{\"term\": \"1ad6e7eb-f3df-453e-ac50-5e02f707955c\", \"@id\": \"https://ipfs.io/ipfs/bafkreihe55hxacf32sxuybe3s3otblhfs3y5qlk3lccjvksh7kncwf6ura#1ad6e7eb-f3df-453e-ac50-5e02f707955c\"}",
            "title": "Applicant Details",
            "description": " Applicant Details",
            "type": "object",
            "properties": {
                "@context": {
                    "oneOf": [
                        {
                            "type": "string"
                        },
                        {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    ],
                    "readOnly": true
                },
                "type": {
                    "oneOf": [
                        {
                            "type": "string"
                        },
                        {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    ],
                    "readOnly": true
                },
                "id": {
                    "type": "string",
                    "readOnly": true
                },
                "field0": {
                    "title": "Applicant Legal Name",
                    "description": "Applicant Legal Name",
                    "readOnly": false,
                    "$comment": "{\"term\": \"field0\", \"@id\": \"https://www.schema.org/text\"}",
                    "type": "string"
                },
                "field1": {
                    "title": "Registered address line 1",
                    "description": "Registered address line 1",
                    "readOnly": false,
                    "$comment": "{\"term\": \"field1\", \"@id\": \"https://www.schema.org/text\"}",
                    "type": "string"
                },
                "field2": {
                    "title": "Registered address line 2",
                    "description": "Registered address line 2",
                    "readOnly": false,
                    "$comment": "{\"term\": \"field2\", \"@id\": \"https://www.schema.org/text\"}",
                    "type": "string"
                },
                "field3": {
                    "title": "Registered address line 3",
                    "description": "Registered address line 3",
                    "readOnly": false,
                    "$comment": "{\"term\": \"field3\", \"@id\": \"https://www.schema.org/text\"}",
                    "type": "string"
                },
                "field4": {
                    "title": "Postal (ZIP) code",
                    "description": "Postal (ZIP) code",
                    "readOnly": false,
                    "$comment": "{\"term\": \"field4\", \"@id\": \"https://www.schema.org/text\"}",
                    "type": "string"
                },
                "field5": {
                    "title": "Country",
                    "description": "Country",
                    "readOnly": false,
                    "$comment": "{\"term\": \"field5\", \"@id\": \"https://www.schema.org/text\"}",
                    "type": "string"
                },
                "field6": {
                    "title": "Legal Status",
                    "description": "Legal Status",
                    "readOnly": false,
                    "$comment": "{\"term\": \"field6\", \"@id\": \"https://www.schema.org/text\"}",
                    "type": "string"
                },
                "field7": {
                    "title": "Country of company registration/private residence",
                    "description": "Country of company registration/private residence",
                    "readOnly": false,
                    "$comment": "{\"term\": \"field7\", \"@id\": \"https://www.schema.org/text\"}",
                    "type": "string"
                },
                "field8": {
                    "title": "Corporate registration number/passport number",
                    "description": "Corporate registration number/passport number",
                    "readOnly": false,
                    "$comment": "{\"term\": \"field8\", \"@id\": \"https://www.schema.org/text\"}",
                    "type": "string"
                },
                "field9": {
                    "title": "VAT number",
                    "description": "VAT number",
                    "readOnly": false,
                    "$comment": "{\"term\": \"field9\", \"@id\": \"https://www.schema.org/text\"}",
                    "type": "string"
                },
                "field10": {
                    "title": "Website URL",
                    "description": "Website URL",
                    "readOnly": false,
                    "$comment": "{\"term\": \"field10\", \"@id\": \"https://www.schema.org/text\"}",
                    "type": "string"
                },
                "field11": {
                    "title": "Main business (e.g. food retailer)",
                    "description": "Main business (e.g. food retailer)",
                    "readOnly": false,
                    "$comment": "{\"term\": \"field11\", \"@id\": \"https://www.schema.org/text\"}",
                    "type": "string"
                },
                "field12": {
                    "title": "Year of registration",
                    "description": "Year of registration",
                    "readOnly": false,
                    "$comment": "{\"term\": \"field12\", \"@id\": \"https://www.schema.org/text\"}",
                    "type": "integer"
                },
                "field13": {
                    "title": "Approximate number of employees",
                    "description": "Approximate number of employees",
                    "readOnly": false,
                    "$comment": "{\"term\": \"field13\", \"@id\": \"https://www.schema.org/text\"}",
                    "type": "integer"
                },
                "field14": {
                    "title": "Name of the Chief Executive Officer/General Manager",
                    "description": "Name of the Chief Executive Officer/General Manager",
                    "readOnly": false,
                    "$comment": "{\"term\": \"field14\", \"@id\": \"https://www.schema.org/text\"}",
                    "type": "string"
                },
                "field15": {
                    "title": "Chief Executive Officer/General Manager passport number",
                    "description": "Chief Executive Officer/General Manager passport number",
                    "readOnly": false,
                    "$comment": "{\"term\": \"field15\", \"@id\": \"https://www.schema.org/text\"}",
                    "type": "string"
                },
                "field16": {
                    "title": "Please state in which countries the organization is active",
                    "description": "Please state in which countries the organization is active",
                    "readOnly": false,
                    "$comment": "{\"term\": \"field16\", \"@id\": \"https://www.schema.org/text\"}",
                    "type": "string"
                },
                "field17": {
                    "title": "Please list the main (>10%) shareholders ",
                    "description": "Please list the main (>10%) shareholders ",
                    "readOnly": false,
                    "$comment": "{\"term\": \"field17\", \"@id\": \"https://www.schema.org/text\"}",
                    "type": "string"
                },
                "field18": {
                    "title": "Balance sheet total for last financial year (in USD)",
                    "description": "Balance sheet total for last financial year (in USD)",
                    "readOnly": false,
                    "$comment": "{\"term\": \"field18\", \"@id\": \"https://www.schema.org/text\"}",
                    "type": "number"
                },
                "field19": {
                    "title": "Email address for Accounts Department",
                    "description": "Email address for Accounts Department",
                    "readOnly": false,
                    "$comment": "{\"term\": \"field19\", \"@id\": \"https://www.schema.org/text\"}",
                    "type": "string",
                    "format": "email"
                }
            },
            "required": [
                "@context",
                "type"
            ],
            "additionalProperties": false
        },
        "#d396eee9-1ce1-4e34-9695-b91cb094bcc4": {
            "$id": "#d396eee9-1ce1-4e34-9695-b91cb094bcc4",
            "$comment": "{\"term\": \"d396eee9-1ce1-4e34-9695-b91cb094bcc4\", \"@id\": \"https://ipfs.io/ipfs/bafkreidwms3pistbvq472d3zkhpll7eth7azpwmftour4xmzrntvibhk2u#d396eee9-1ce1-4e34-9695-b91cb094bcc4\"}",
            "title": "Contact Details",
            "description": "Contact Details",
            "type": "object",
            "properties": {
                "@context": {
                    "oneOf": [
                        {
                            "type": "string"
                        },
                        {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    ],
                    "readOnly": true
                },
                "type": {
                    "oneOf": [
                        {
                            "type": "string"
                        },
                        {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    ],
                    "readOnly": true
                },
                "id": {
                    "type": "string",
                    "readOnly": true
                },
                "field0": {
                    "title": "Organization Name",
                    "description": "Organization Name",
                    "readOnly": false,
                    "$comment": "{\"term\": \"field0\", \"@id\": \"https://www.schema.org/text\"}",
                    "type": "string"
                },
                "field1": {
                    "title": "Address line 1",
                    "description": "Address line 1",
                    "readOnly": false,
                    "$comment": "{\"term\": \"field1\", \"@id\": \"https://www.schema.org/text\"}",
                    "type": "string"
                },
                "field2": {
                    "title": "Address line 2",
                    "description": "Address line 2",
                    "readOnly": false,
                    "$comment": "{\"term\": \"field2\", \"@id\": \"https://www.schema.org/text\"}",
                    "type": "string"
                },
                "field3": {
                    "title": "Address line 3",
                    "description": "Address line 3",
                    "readOnly": false,
                    "$comment": "{\"term\": \"field3\", \"@id\": \"https://www.schema.org/text\"}",
                    "type": "string"
                },
                "field4": {
                    "title": "Postal code",
                    "description": "Postal code",
                    "readOnly": false,
                    "$comment": "{\"term\": \"field4\", \"@id\": \"https://www.schema.org/text\"}",
                    "type": "string"
                },
                "field5": {
                    "title": "Country",
                    "description": "Country",
                    "readOnly": false,
                    "$comment": "{\"term\": \"field5\", \"@id\": \"https://www.schema.org/text\"}",
                    "type": "string"
                },
                "field6": {
                    "title": "Contact person",
                    "description": "Contact person",
                    "readOnly": false,
                    "$comment": "{\"term\": \"field6\", \"@id\": \"https://www.schema.org/text\"}",
                    "type": "string"
                },
                "field7": {
                    "title": "e-mail",
                    "description": "e-mail",
                    "readOnly": false,
                    "$comment": "{\"term\": \"field7\", \"@id\": \"https://www.schema.org/text\"}",
                    "type": "string",
                    "format": "email"
                },
                "field8": {
                    "title": "Telephone",
                    "description": "Telephone",
                    "readOnly": false,
                    "$comment": "{\"term\": \"field8\", \"@id\": \"https://www.schema.org/text\"}",
                    "type": "string"
                },
                "field9": {
                    "title": "Fax",
                    "description": "Fax",
                    "readOnly": false,
                    "$comment": "{\"term\": \"field9\", \"@id\": \"https://www.schema.org/text\"}",
                    "type": "string"
                },
                "field10": {
                    "title": "Existing I-REC Registry organization(s) to become subsidiary",
                    "description": "Existing I-REC Registry organization(s) to become subsidiary",
                    "readOnly": false,
                    "$comment": "{\"term\": \"field10\", \"@id\": \"https://www.schema.org/text\"}",
                    "type": "string"
                }
            },
            "required": [
                "@context",
                "type"
            ],
            "additionalProperties": false
        },
        "#4a8719f0-b9c5-45cf-8a20-b30c3a493aef": {
            "$id": "#4a8719f0-b9c5-45cf-8a20-b30c3a493aef",
            "$comment": "{\"term\": \"4a8719f0-b9c5-45cf-8a20-b30c3a493aef\", \"@id\": \"https://ipfs.io/ipfs/bafkreicwhwmdbu4r3zv3cfifbb47dd7y5bf7l6qzycf66ll6pskk2r7gyq#4a8719f0-b9c5-45cf-8a20-b30c3a493aef\"}",
            "title": "Lead User Details",
            "description": "Lead User Details",
            "type": "object",
            "properties": {
                "@context": {
                    "oneOf": [
                        {
                            "type": "string"
                        },
                        {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    ],
                    "readOnly": true
                },
                "type": {
                    "oneOf": [
                        {
                            "type": "string"
                        },
                        {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    ],
                    "readOnly": true
                },
                "id": {
                    "type": "string",
                    "readOnly": true
                },
                "field0": {
                    "title": "Family Name (surname)",
                    "description": "Family Name (surname)",
                    "readOnly": false,
                    "$comment": "{\"term\": \"field0\", \"@id\": \"https://www.schema.org/text\"}",
                    "type": "string"
                },
                "field1": {
                    "title": "Other (Given) Names",
                    "description": "Other (Given) Names",
                    "readOnly": false,
                    "$comment": "{\"term\": \"field1\", \"@id\": \"https://www.schema.org/text\"}",
                    "type": "string"
                },
                "field2": {
                    "title": "Title",
                    "description": "Title",
                    "readOnly": false,
                    "$comment": "{\"term\": \"field2\", \"@id\": \"https://www.schema.org/text\"}",
                    "type": "string"
                },
                "field3": {
                    "title": "e-mail",
                    "description": "e-mail",
                    "readOnly": false,
                    "$comment": "{\"term\": \"field3\", \"@id\": \"https://www.schema.org/text\"}",
                    "type": "string",
                    "format": "email"
                },
                "field4": {
                    "title": "Telephone",
                    "description": "Telephone",
                    "readOnly": false,
                    "$comment": "{\"term\": \"field4\", \"@id\": \"https://www.schema.org/text\"}",
                    "type": "string"
                },
                "field5": {
                    "title": "Fax",
                    "description": "Fax",
                    "readOnly": false,
                    "$comment": "{\"term\": \"field5\", \"@id\": \"https://www.schema.org/text\"}",
                    "type": "string"
                }
            },
            "required": [
                "@context",
                "type"
            ],
            "additionalProperties": false
        }
    }
}
