### ISSUE TITLE
bug: aggregatedocumentblock not support `sum`  function

### ISSUE THREAD

**Issue by samuraitruong** [hashgraph/guardian#931]
### Problem description
Please refer to this - https://docs.hedera.com/guardian/available-policy-workflow-blocks/aggregatedocumentblock

In the pass we use rule and threshold which very simple setup, what is the setup in the new way to archive the same result?

For example our current setup was rule = 'CO2eqEmissions` and threshold = 1

It mean that document will be aggregated until total CO2eqEmissions > =1 then it will going to next action (mint token). I had tried many setup in the new  way using  aggregateType = cumulative but can not get it works as expected.

After dig deeper in the code I found that below setup will solve the issue
```
  "expressions": [
              {
                "name": "total",
                "value": "CO2eqEmissions"
              }
            ],
            "aggregateType": "cumulative",
            "emptyData": false,
            "condition": "sum(total) >= 1"
```

I tested by hard code above setup in the code and it works as expected (see screenshot below)
![image](https://user-images.githubusercontent.com/1183138/170653212-ad01eb0a-3a84-42af-86f1-eb54cfaaaf0d.png)

However, this only works if we update policy without using the UI, the validation will stop us from publish the policy
![image](https://user-images.githubusercontent.com/1183138/170653178-8e0c2790-e694-493f-9bb9-55fa8787f490.png)

### Requirements
- For those feature we need very clear document so people don't need to dig deeper in the code to understand how to set it up. Better to have example  (I checked iRec policy we have no use of this block) 
- Fix the validation to support sum operator

### Definition of done
How do we know we've fully dealt with it?

### Acceptance criteria
 - this is quite urgent for us

**Comment by samuraitruong** [comment]
After dig deeper in the code I found that  below setup will solve the issue

```
  "expressions": [
              {
                "name": "total",
                "value": "CO2eqEmissions"
              }
            ],
            "aggregateType": "cumulative",
            "emptyData": false,
            "condition": "sum(total) >= 1"
```
I tested by hard code above setup in the code and it works as expected

However, this only works if we update policy without using the UI,  the validation will stop us from publish the policy

**Comment by anvabr** [comment]
@Stepan-Kirjakov had investigated this, turns out there is a very peculiar behaviour of the mathjs library - possibly a bug. We've added a temporary [fix in the develop branch](https://github.com/hashgraph/guardian/commit/a408830403e740b55e628a7ae64ca3f60ae216d4#diff-6f05c1eef221d5fb28c1bf6850fbe28cc0840b862a4cfc4dc8f3367cedfe7b7e), and will be reaching out to the mathjs maintainers to see if this can be done upstream.

**Comment by samuraitruong** [comment]
@anvabr  this bug block us from testing for our next release, so if you can release it earlier it will help.

**Comment by voycey** [comment]
+1 for hotfix here because we have dependencies on this for 2 clients right now

**Comment by anvabr** [comment]
v2.1.1 has been [released](https://github.com/hashgraph/guardian/releases/tag/v2.1.1).

**Comment by samuraitruong** [comment]
@anvabr  look like the CI setup is wrong and it published the image with same tag (2.1.0)

https://github.com/hashgraph/guardian/runs/6658862690?check_suite_focus=true#step:11:249

**Comment by voycey** [comment]
@anvabr this is really important to get right, this would have taken our production down had we been using this. The new guardian deployment I have been working on will pull the same tag (it is locked to a version number), can I recommend the use of Immutable tags to prevent this from happening in the future?

**Comment by voycey** [comment]
Actually - can the image also be tagged with the git-sha of the release version? This will help us lock it down in multiple ways if this is important - it doesnt look like GCR has immutable tag capability

**Comment by anvabr** [comment]
Apologies for that @samuraitruong, I build from the repo to test and have missed it. Please find [2.1.2 ](https://github.com/hashgraph/guardian/releases/tag/v2.1.2)with the fixed build.
