### ISSUE TITLE
Production Readiness - Integrate Hashicorp vault for most important secrets

### ISSUE THREAD

**Issue by voycey** [hashgraph/guardian#954]
### Problem description
Currently keys are stored in plaintext in the environment or in Mongo and displayed in the UI. As the Guardian default deployment is open this represents a significant security risk for applications deployed to production. Suggestions in our weekly call have been around the implementation of Hashicorp Vault in-cluster to be able to manage these secrets rather than the existing mechanism.

TYMLEZ have created a Terraform stack that includes Hashicorp Vault but there are some relatively big changes to the key infrastructure that need to be completed in order to utilise it - I suggest this is handled by Envision as we have no capacity currently with our go-live development.

Vault is a very simple KV storage system (although it has very powerful capabilities for the future - we should focus on the basics right now) - it is interacted via GET / PUT / DELETE HTTP verbs to Write and Read secrets, it will set the foundation for the future of all key management.

### Requirements

**Replace the current key storage mechanism of ENV and MongoDB with GET / PUT requests to Hashicorp vault**
- Add Hashicorp Vault to `docker-compose.yml` 
- Create a variable for "Vault Server" - default to the container hostname `vault` (this will allow for override if necessary)
- Create "write only" UI to replace current "read write" in the Guardian UI for `guardian_operator_key`
- Create "write only" UI to replace `guardian_ipfs_key`
- Remove writing of secrets to MongoDB
- Remove reading from Environment leaving only Vault as the main secrets manager.

### Definition of done
Vault is used for at least  `guardian_operator_key` and `guardian_ipfs_key`

### Acceptance criteria
Inspection of the UI will show no capability to read `guardian_operator_key` or `guardian_ipfs_key`
Inspection of the database (MongoDB) will reveal no passwords or secrets written here
Key functionality continues to work

**Comment by anvabr** [comment]
Need to be considered at the wider view of key management as per #58
