### ISSUE TITLE
Auditor account access multiple root authority VP

### ISSUE THREAD

**Issue by samuraitruong** [hashgraph/guardian#995]
### Problem description
The Auditor does not separate by root authority. If we have multiple root authority then anybody with Auditor roles will able to see all VP documents 

### Step to reproduce
1. Create new root authority and setup policy
2. Mint few tokens
3. Repeat 1 & 2 for few other root authority
4. Login as any 'Auditor'
5. all VP documents will display

### Expected behavior
- Editor should linked to RA (root Auhtority)
- When login, they can only see the VP of their RA

If that is by design, please provide the filter in UI/API that we can extracts VP for a specific RA

**Comment by prernaadev01** [comment]
@samuraitruong This ticket has a same solution as suggested by @anvabr on ticket #996. Thanks
