### ISSUE TITLE
Trustchain API does not support any filter & pagination

### ISSUE THREAD

**Issue by samuraitruong** [hashgraph/guardian#996]
### Problem description
- Guardian service implement GET_VP_DOCUMENT support filters however, api gateway does not  send any filter params that 
cause the trust chain API return all VPS
https://github.com/hashgraph/guardian/blob/main/api-gateway/src/api/service/trustchains.ts#L17

### Expected behavior
- trust chain api should support filters
- trust chain api should support pagination & ordering
- swagger document & documents need to be updated with the changes

**Comment by anvabr** [comment]
@samuraitruong as always thank you for the issue ticket. There are two APIs related to this and one that you mention indeed does not support filters/pagination. This API is designed to be 'raw', i.e. we are planning to change its implementation (but not the definition) to read data from Hedera directly and thus it is likely not going to contain the facilities you are requesting. We will revisit this when the new implementation is done.

The is a specific new block-level API which does contain pagination/filtering facilities and is meant to be used for the task like yours. Please take a look a the attached howto document our dev team has prepared for you, which should explain the technique.
[TrustChain API.docx](https://github.com/hashgraph/guardian/files/8938420/TrustChain.API.docx)

**Comment by prernaadev01** [comment]
@samuraitruong Can you please let us know if we can close this ticket?
